// Pagina del gioco (src/shell.html): menu, impostazioni, schermate fisse
// Ogni riga: [italiano, inglese, tedesco, francese]
addTranslations([
  ["Campo Aperto — calcio 3D", "Campo Aperto — 3D football", "Campo Aperto — 3D-Fussball", "Campo Aperto — football 3D"],
  ["Impostazioni", "Settings", "Einstellungen", "Paramètres"],
  ["Generale", "General", "Allgemein", "Général"],
  ["Lingua", "Language", "Sprache", "Langue"],
  ["Abbassa la risoluzione da sola se gli fps calano", "Lowers the resolution automatically if the frame rate drops", "Senkt die Auflösung automatisch, wenn die FPS fallen", "Baisse la résolution automatiquement si les FPS chutent"],
  ["Accedi", "Log in", "Anmelden", "Se connecter"],
  ["Accensione dei fari…", "Switching on the floodlights…", "Flutlicht wird eingeschaltet…", "Allumage des projecteurs…"],
  ["Account", "Account", "Konto", "Compte"],
  ["Account, monete, scommesse e negozio. Lascia vuoto per usare quello incluso nel gioco.", "Account, coins, bets and shop. Leave empty to use the one included in the game.", "Konto, Münzen, Wetten und Shop. Leer lassen, um den im Spiel enthaltenen zu verwenden.", "Compte, pièces, paris et boutique. Laisse vide pour utiliser celui inclus dans le jeu."],
  ["Aggiorna", "Refresh", "Aktualisieren", "Actualiser"],
  ["Aiuto ricezione", "Receiving assist", "Annahmehilfe", "Aide à la réception"],
  ["Amici", "Friends", "Freunde", "Amis"],
  ["Amici e sfide", "Friends and challenges", "Freunde und Herausforderungen", "Amis et défis"],
  ["Amici invitati", "Invited friends", "Eingeladene Freunde", "Amis invités"],
  ["Annulla", "Cancel", "Abbrechen", "Annuler"],
  ["Aperto", "Open", "Offen", "Ouvert"],
  ["Apri", "Open", "Öffnen", "Ouvrir"],
  ["Attiva", "Turn on", "Aktivieren", "Activer"],
  ["Audio", "Audio", "Audio", "Audio"],
  ["Bonus giornaliero", "Daily bonus", "Tagesbonus", "Bonus quotidien"],
  ["Bonus multipla", "Accumulator bonus", "Kombi-Bonus", "Bonus combiné"],
  ["Cambia", "Change", "Ändern", "Changer"],
  ["Cambia squadre", "Change teams", "Teams wechseln", "Changer d'équipes"],
  ["Cambia tasti", "Change keys", "Tasten ändern", "Changer les touches"],
  ["Campionato", "League", "Meisterschaft", "Championnat"],
  ["Campionato, torneo e coppe: calendario, classifica, tabellone", "League, tournament and cups: fixtures, table, bracket", "Meisterschaft, Turnier und Pokale: Spielplan, Tabelle, Turnierbaum", "Championnat, tournoi et coupes : calendrier, classement, tableau"],
  ["Campo", "Pitch", "Spielfeld", "Terrain"],
  ["Casa", "Home", "Heim", "Domicile"],
  ["Chi crea la partita fa da host: la simula sul suo computer e decide il risultato. Gli altri entrano con il codice e mandano solo i propri comandi.", "Whoever creates the match is the host: it is simulated on their computer, which decides the result. The others join with the code and only send their own controls.", "Wer das Spiel erstellt, ist der Host: Das Spiel läuft auf seinem Computer und er entscheidet das Ergebnis. Die anderen treten mit dem Code bei und senden nur ihre eigenen Eingaben.", "Celui qui crée le match est l'hôte : le match est simulé sur son ordinateur, qui décide du résultat. Les autres rejoignent avec le code et n'envoient que leurs propres commandes."],
  ["Clicca un tasto (o selezionalo e premi A) e poi premi quello nuovo. Esc annulla, Backspace toglie il tasto alternativo. Se il tasto era già usato, viene tolto dall'altra azione.", "Click a key (or select it and press A), then press the new one. Esc cancels, Backspace removes the alternative key. If the key was already in use, it is removed from the other action.", "Klicke auf eine Taste (oder wähle sie aus und drücke A) und drücke dann die neue. Esc bricht ab, Rücktaste entfernt die alternative Taste. War die Taste schon belegt, wird sie bei der anderen Aktion entfernt.", "Clique sur une touche (ou sélectionne-la et appuie sur A), puis appuie sur la nouvelle. Échap annule, Retour arrière retire la touche alternative. Si la touche était déjà utilisée, elle est retirée de l'autre action."],
  ["Codice partita", "Match code", "Spielcode", "Code du match"],
  ["Codice scommessa", "Bet code", "Wettcode", "Code du pari"],
  ["Collegamento…", "Connecting…", "Verbinde…", "Connexion…"],
  ["Comandi", "Controls", "Steuerung", "Commandes"],
  ["Competizione", "Competition", "Wettbewerb", "Compétition"],
  ["Competizioni", "Competitions", "Wettbewerbe", "Compétitions"],
  ["Con gli amici", "With friends", "Mit Freunden", "Avec des amis"],
  ["Conferma scommessa", "Confirm bet", "Wette bestätigen", "Confirmer le pari"],
  ["Contatore in alto a destra", "Counter in the top right", "Anzeige oben rechts", "Compteur en haut à droite"],
  ["Controller", "Controller", "Controller", "Manette"],
  ["Controller predefinito", "Default controller", "Standard-Controller", "Manette par défaut"],
  ["Controlli", "Controls", "Steuerung", "Contrôles"],
  ["Copia", "Copy", "Kopieren", "Copier"],
  ["Copia codice", "Copy code", "Code kopieren", "Copier le code"],
  ["Coppe", "Cups", "Pokale", "Coupes"],
  ["Cosa hanno giocato le persone, non probabilità.", "What people have bet on, not probabilities.", "Was die Leute gesetzt haben, keine Wahrscheinlichkeiten.", "Ce que les gens ont joué, pas des probabilités."],
  ["Crea", "Create", "Erstellen", "Créer"],
  ["Crea account", "Create account", "Konto erstellen", "Créer un compte"],
  ["Crea partita", "Create match", "Spiel erstellen", "Créer un match"],
  ["Crea sul server online", "Create on the online server", "Auf dem Online-Server erstellen", "Créer sur le serveur en ligne"],
  ["Cronaca", "Commentary", "Liveticker", "Direct"],
  ["Ctrl+Maiusc+D", "Ctrl+Shift+D", "Strg+Umschalt+D", "Ctrl+Maj+D"],
  ["Da 3 a 16 caratteri tra lettere, numeri e _. Password di almeno 8 caratteri. Parti con le monete di benvenuto.", "3 to 16 characters: letters, numbers and _. Password of at least 8 characters. You start with the welcome coins.", "3 bis 16 Zeichen aus Buchstaben, Zahlen und _. Passwort mit mindestens 8 Zeichen. Du startest mit den Willkommensmünzen.", "De 3 à 16 caractères parmi lettres, chiffres et _. Mot de passe d'au moins 8 caractères. Tu commences avec les pièces de bienvenue."],
  ["Dai giocatori", "From the players", "Von den Spielern", "Des joueurs"],
  ["Dai questo codice agli altri giocatori.", "Give this code to the other players.", "Gib diesen Code den anderen Spielern.", "Donne ce code aux autres joueurs."],
  ["Diagnostica di rete", "Network diagnostics", "Netzwerkdiagnose", "Diagnostic réseau"],
  ["Difficoltà", "Difficulty", "Schwierigkeit", "Difficulté"],
  ["Difficoltà IA", "AI difficulty", "KI-Schwierigkeit", "Difficulté de l'IA"],
  ["Disegno attuale", "Current rendering", "Aktuelle Darstellung", "Rendu actuel"],
  ["Durata di un tempo", "Length of a half", "Dauer einer Halbzeit", "Durée d'une mi-temps"],
  ["Effetti", "Effects", "Effekte", "Effets"],
  ["Elimina", "Delete", "Löschen", "Supprimer"],
  ["Entra", "Join", "Beitreten", "Rejoindre"],
  ["Esci", "Quit", "Beenden", "Quitter"],
  ["Esci al menu", "Quit to menu", "Zurück zum Menü", "Retour au menu"],
  ["Esci dall'account", "Log out", "Abmelden", "Se déconnecter"],
  ["Esci dalla lobby", "Leave lobby", "Lobby verlassen", "Quitter le salon"],
  ["Eventi", "Events", "Ereignisse", "Événements"],
  ["Fatto", "Done", "Fertig", "Terminé"],
  ["Fine partita", "Full time", "Spielende", "Fin du match"],
  ["Finestra", "Window", "Fenster", "Fenêtre"],
  ["Formato", "Format", "Format", "Format"],
  ["Formazione", "Formation", "Formation", "Formation"],
  ["Gioca", "Play", "Spielen", "Jouer"],
  ["Gioca online", "Play online", "Online spielen", "Jouer en ligne"],
  ["Gioca qui", "Play here", "Hier spielen", "Jouer ici"],
  ["Gli amici nella stessa rete entrano con il solo codice. Se il gioco non li trova, possono scrivere questo indirizzo in Unisciti, sotto «La partita non viene trovata?». Se Windows chiede il permesso del firewall, consentilo anche per le reti pubbliche.", "Friends on the same network join with just the code. If the game can't find them, they can type this address in Join, under “Match not found?”. If Windows asks for firewall permission, allow it for public networks too.", "Freunde im selben Netzwerk treten nur mit dem Code bei. Findet das Spiel sie nicht, können sie diese Adresse unter Beitreten bei «Spiel wird nicht gefunden?» eingeben. Wenn Windows nach der Firewall-Erlaubnis fragt, erlaube sie auch für öffentliche Netzwerke.", "Les amis sur le même réseau rejoignent avec le code seulement. Si le jeu ne les trouve pas, ils peuvent saisir cette adresse dans Rejoindre, sous « Le match est introuvable ? ». Si Windows demande l'autorisation du pare-feu, autorise-la aussi pour les réseaux publics."],
  ["Grafica", "Graphics", "Grafik", "Graphismes"],
  ["Guarda", "Watch", "Ansehen", "Regarder"],
  ["Guarda partita", "Watch match", "Spiel ansehen", "Regarder le match"],
  ["Il tuo calciatore: in partita è un attaccante della tua squadra. Gli altri vedono quello che hai indossato (letto dal server, non dal tuo computer).", "Your footballer: in matches, they're a striker in your team. Others see what you're wearing (read from the server, not from your computer).", "Dein Fussballer: Im Spiel ist er ein Stürmer deines Teams. Die anderen sehen, was du trägst (vom Server gelesen, nicht von deinem Computer).", "Ton joueur : en match, c'est un attaquant de ton équipe. Les autres voient ce que tu portes (lu sur le serveur, pas sur ton ordinateur)."],
  ["Il tuo indirizzo", "Your address", "Deine Adresse", "Ton adresse"],
  ["Il tuo nome", "Your name", "Dein Name", "Ton nom"],
  ["In attesa che l'host avvii la partita…", "Waiting for the host to start the match…", "Warte, bis der Host das Spiel startet…", "En attente que l'hôte lance le match…"],
  ["In attesa che l'host torni alla lobby…", "Waiting for the host to return to the lobby…", "Warte, bis der Host zur Lobby zurückkehrt…", "En attente que l'hôte revienne au salon…"],
  ["In corso", "In progress", "Läuft", "En cours"],
  ["Indietro", "Back", "Zurück", "Retour"],
  ["Indirizzo dell'host, quello grande nella sua lobby", "Host's address, the big one in their lobby", "Adresse des Hosts, die grosse in seiner Lobby", "Adresse de l'hôte, la grande dans son salon"],
  ["Inizia la partita", "Start the match", "Spiel starten", "Lancer le match"],
  ["Inventario", "Inventory", "Inventar", "Inventaire"],
  ["Invita amici", "Invite friends", "Freunde einladen", "Inviter des amis"],
  ["L'invito arriva nel loro pannello Amici: entrano con un clic, senza scrivere il codice.", "The invite arrives in their Friends panel: they join with one click, without typing the code.", "Die Einladung erscheint in ihrem Freunde-Bereich: Sie treten mit einem Klick bei, ohne den Code einzugeben.", "L'invitation arrive dans leur panneau Amis : ils rejoignent en un clic, sans taper le code."],
  ["La mia schedina", "My bet slip", "Mein Wettschein", "Mon bulletin"],
  ["La partita non viene trovata?", "Match not found?", "Spiel wird nicht gefunden?", "Le match est introuvable ?"],
  ["La tua squadra", "Your team", "Dein Team", "Ton équipe"],
  ["Limite fps", "FPS limit", "FPS-Limit", "Limite de FPS"],
  ["Lobby", "Lobby", "Lobby", "Salon"],
  ["Maglie, scarpe, capelli", "Shirts, boots, hair", "Trikots, Schuhe, Haare", "Maillots, chaussures, cheveux"],
  ["Mentalità", "Mentality", "Mentalität", "Mentalité"],
  ["Menu", "Menu", "Menü", "Menu"],
  ["Menu principale", "Main menu", "Hauptmenü", "Menu principal"],
  ["Modello", "Preset", "Vorlage", "Modèle"],
  ["Mostra altre", "Show more", "Mehr anzeigen", "Afficher plus"],
  ["Mostra altri", "Show more", "Mehr anzeigen", "Afficher plus"],
  ["Mostra fps", "Show FPS", "FPS anzeigen", "Afficher les FPS"],
  ["Mostra pubblicamente le mie scommesse", "Show my bets publicly", "Meine Wetten öffentlich zeigen", "Afficher mes paris publiquement"],
  ["Mouse in partita: clic sinistro passaggio, clic destro tiro", "Mouse in matches: left click pass, right click shoot", "Maus im Spiel: Linksklick Pass, Rechtsklick Schuss", "Souris en match : clic gauche passe, clic droit tir"],
  ["Movimenti", "Movements", "Bewegungen", "Mouvements"],
  ["Multiplayer", "Multiplayer", "Mehrspieler", "Multijoueur"],
  ["Negozio", "Shop", "Shop", "Boutique"],
  ["Nella versione browser pubblicata il gioco online non è disponibile, perché la pagina non può collegarsi a server esterni. Usa l'app desktop.", "Online play isn't available in the published browser version, because the page can't connect to external servers. Use the desktop app.", "In der veröffentlichten Browserversion ist das Online-Spiel nicht verfügbar, weil die Seite keine Verbindung zu externen Servern herstellen kann. Verwende die Desktop-App.", "Le jeu en ligne n'est pas disponible dans la version navigateur publiée, car la page ne peut pas se connecter à des serveurs externes. Utilise l'application de bureau."],
  ["Nome", "Name", "Name", "Nom"],
  ["Nome della squadra di casa (scrivi per cambiarlo)", "Home team name (type to change it)", "Name des Heimteams (tippen zum Ändern)", "Nom de l'équipe à domicile (écris pour le changer)"],
  ["Nome della squadra ospite (scrivi per cambiarlo)", "Away team name (type to change it)", "Name des Gastteams (tippen zum Ändern)", "Nom de l'équipe à l'extérieur (écris pour le changer)"],
  ["Nome utente", "Username", "Benutzername", "Nom d'utilisateur"],
  ["Nome utente (pubblico)", "Username (public)", "Benutzername (öffentlich)", "Nom d'utilisateur (public)"],
  ["Nomi dei pulsanti", "Button names", "Tastenbezeichnungen", "Noms des boutons"],
  ["Numero", "Number", "Nummer", "Numéro"],
  ["Nuova competizione", "New competition", "Neuer Wettbewerb", "Nouvelle compétition"],
  ["Nuova coppa", "New cup", "Neuer Pokal", "Nouvelle coupe"],
  ["Nuova partita", "New match", "Neues Spiel", "Nouveau match"],
  ["Nuova sfida tra amici", "New challenge between friends", "Neue Herausforderung unter Freunden", "Nouveau défi entre amis"],
  ["Nuovo campionato", "New league", "Neue Meisterschaft", "Nouveau championnat"],
  ["Nuovo torneo", "New tournament", "Neues Turnier", "Nouveau tournoi"],
  ["Obiettivi", "Goals", "Ziele", "Objectifs"],
  ["Oggi", "Today", "Heute", "Aujourd'hui"],
  ["Online", "Online", "Online", "En ligne"],
  ["Online o in rete locale", "Online or on a local network", "Online oder im lokalen Netzwerk", "En ligne ou en réseau local"],
  ["Ospite", "Away", "Gast", "Extérieur"],
  ["Ospiti", "Away", "Gäste", "Visiteurs"],
  ["Pannello con ruolo, IP, porta, stato, ping ed eventi (anche Ctrl+Maiusc+D)", "Panel with role, IP, port, status, ping and events (also Ctrl+Shift+D)", "Anzeige mit Rolle, IP, Port, Status, Ping und Ereignissen (auch Strg+Umschalt+D)", "Panneau avec rôle, IP, port, état, ping et événements (aussi Ctrl+Maj+D)"],
  ["Partita", "Match", "Spiel", "Match"],
  ["Partita 11 contro 11 contro l'IA", "11-a-side match against the AI", "Spiel 11 gegen 11 gegen die KI", "Match à 11 contre 11 contre l'IA"],
  ["Partita del server", "Server match", "Server-Spiel", "Match du serveur"],
  ["Partita libera tra IA (senza scommesse)", "Free AI vs AI match (no bets)", "Freies Spiel KI gegen KI (ohne Wetten)", "Match libre entre IA (sans paris)"],
  ["Partita online: il gioco continua mentre sei in questo menu.", "Online match: the game keeps running while you're in this menu.", "Online-Spiel: Das Spiel läuft weiter, während du in diesem Menü bist.", "Match en ligne : le jeu continue pendant que tu es dans ce menu."],
  ["Partite", "Matches", "Spiele", "Matchs"],
  ["Partite del server, calcolate con lo stesso motore del gioco. Le scommesse chiudono 10 secondi prima del calcio d'inizio; il risultato si scopre solo guardando.", "Server matches, calculated with the same engine as the game. Betting closes 10 seconds before kick-off; you only find out the result by watching.", "Server-Spiele, berechnet mit derselben Engine wie das Spiel. Die Wetten schliessen 10 Sekunden vor dem Anstoss; das Ergebnis erfährst du nur beim Zuschauen.", "Matchs du serveur, calculés avec le même moteur que le jeu. Les paris ferment 10 secondes avant le coup d'envoi ; le résultat ne se découvre qu'en regardant."],
  ["Partite del server, cronaca e scommesse dei giocatori", "Server matches, commentary and players' bets", "Server-Spiele, Liveticker und Wetten der Spieler", "Matchs du serveur, direct et paris des joueurs"],
  ["Password", "Password", "Passwort", "Mot de passe"],
  ["Pausa", "Pause", "Pause", "Pause"],
  ["Personaggio", "Character", "Figur", "Personnage"],
  ["Personaggio e inventario", "Character and inventory", "Figur und Inventar", "Personnage et inventaire"],
  ["Personalizzazione", "Customisation", "Anpassung", "Personnalisation"],
  ["Più scommesse", "Most bet", "Meiste Wetten", "Les plus pariés"],
  ["Premio spettatore", "Spectator reward", "Zuschauerprämie", "Prime du spectateur"],
  ["Pressing", "Pressing", "Pressing", "Pressing"],
  ["Prezzi decisi dal server. Gli oggetti comprati restano nel tuo inventario per sempre e si vedono sul tuo calciatore, anche dagli altri giocatori online.", "Prices are set by the server. Items you buy stay in your inventory forever and show on your footballer, also to other players online.", "Die Preise bestimmt der Server. Gekaufte Gegenstände bleiben für immer in deinem Inventar und sind an deinem Fussballer zu sehen, auch für andere Spieler online.", "Prix fixés par le serveur. Les objets achetés restent dans ton inventaire pour toujours et se voient sur ton joueur, aussi par les autres joueurs en ligne."],
  ["Privacy", "Privacy", "Privatsphäre", "Confidentialité"],
  ["Profilo", "Profile", "Profil", "Profil"],
  ["Prova collegamento", "Test connection", "Verbindung testen", "Tester la connexion"],
  ["Pubblica (visibile agli altri giocatori)", "Public (visible to other players)", "Öffentlich (für andere Spieler sichtbar)", "Publique (visible par les autres joueurs)"],
  ["Pubblico", "Crowd", "Publikum", "Public"],
  ["Puntata (monete)", "Stake (coins)", "Einsatz (Münzen)", "Mise (pièces)"],
  ["Qualità", "Quality", "Qualität", "Qualité"],
  ["Quota base", "Base odds", "Basisquote", "Cote de base"],
  ["Quota totale", "Total odds", "Gesamtquote", "Cote totale"],
  ["Regole attive: fuorigioco, falli, punizioni, rigori, rimesse laterali, calci d'angolo, rinvii dal fondo, intervallo con cambio di campo. I colpi di testa sono automatici quando la palla arriva alta. In difesa il passaggio diventa contrasto e il tiro diventa scivolata.", "Active rules: offside, fouls, free kicks, penalties, throw-ins, corners, goal kicks, half-time with change of ends. Headers are automatic when the ball arrives high. In defence, pass becomes tackle and shoot becomes slide tackle.", "Aktive Regeln: Abseits, Fouls, Freistösse, Elfmeter, Einwürfe, Eckstösse, Abstösse, Halbzeit mit Seitenwechsel. Kopfbälle erfolgen automatisch, wenn der Ball hoch kommt. In der Abwehr wird Pass zu Tackling und Schuss zu Grätsche.", "Règles actives : hors-jeu, fautes, coups francs, penalties, touches, corners, six mètres, mi-temps avec changement de côté. Les têtes sont automatiques quand le ballon arrive haut. En défense, la passe devient un tacle et le tir un tacle glissé."],
  ["Regole attive: fuorigioco, falli, punizioni, rigori, rimesse laterali, calci d'angolo, rinvii dal fondo, intervallo con cambio di campo. I colpi di testa sono automatici quando la palla arriva alta: la direzione indica dove mandarla. Con la telecamera \"Dietro al giocatore\" su vuol dire sempre verso la porta avversaria.", "Active rules: offside, fouls, free kicks, penalties, throw-ins, corners, goal kicks, half-time with change of ends. Headers are automatic when the ball arrives high: the direction sets where to send it. With the \"Behind the player\" camera, up always means towards the opponents' goal.", "Aktive Regeln: Abseits, Fouls, Freistösse, Elfmeter, Einwürfe, Eckstösse, Abstösse, Halbzeit mit Seitenwechsel. Kopfbälle erfolgen automatisch, wenn der Ball hoch kommt: Die Richtung bestimmt, wohin er geht. Mit der Kamera \"Hinter dem Spieler\" bedeutet oben immer Richtung gegnerisches Tor.", "Règles actives : hors-jeu, fautes, coups francs, penalties, touches, corners, six mètres, mi-temps avec changement de côté. Les têtes sont automatiques quand le ballon arrive haut : la direction indique où l'envoyer. Avec la caméra \"Derrière le joueur\", haut veut toujours dire vers le but adverse."],
  ["Replay", "Replay", "Wiederholung", "Ralenti"],
  ["Ricevi un codice di 6 caratteri da dare agli amici. Scegli tu squadre e durata, e avvii quando siete pronti.", "You get a 6-character code to give your friends. You choose teams and length, and start when you're all ready.", "Du erhältst einen 6-stelligen Code für deine Freunde. Du wählst Teams und Dauer und startest, wenn alle bereit sind.", "Tu reçois un code de 6 caractères à donner à tes amis. Tu choisis les équipes et la durée, et tu lances quand vous êtes prêts."],
  ["Ricomincia", "Restart", "Neu starten", "Recommencer"],
  ["Riduci", "Minimise", "Verkleinern", "Réduire"],
  ["Rigori", "Penalties", "Elfmeterschiessen", "Tirs au but"],
  ["Ripeti la password", "Repeat password", "Passwort wiederholen", "Répète le mot de passe"],
  ["Riprendi", "Resume", "Fortsetzen", "Reprendre"],
  ["Risoluzione", "Resolution", "Auflösung", "Résolution"],
  ["Risoluzione dinamica", "Dynamic resolution", "Dynamische Auflösung", "Résolution dynamique"],
  ["Rivincita", "Rematch", "Revanche", "Revanche"],
  ["Saldo (dal server)", "Balance (from the server)", "Guthaben (vom Server)", "Solde (du serveur)"],
  ["Saldo, scommesse e oggetti sono salvati sul server: con lo stesso account li ritrovi su ogni computer e browser. La password non viene mai salvata in chiaro.", "Balance, bets and items are saved on the server: with the same account you'll find them on any computer and browser. The password is never stored in plain text.", "Guthaben, Wetten und Gegenstände werden auf dem Server gespeichert: Mit demselben Konto findest du sie auf jedem Computer und Browser. Das Passwort wird nie im Klartext gespeichert.", "Solde, paris et objets sont enregistrés sur le serveur : avec le même compte, tu les retrouves sur chaque ordinateur et navigateur. Le mot de passe n'est jamais enregistré en clair."],
  ["Salva numero e nome", "Save number and name", "Nummer und Name speichern", "Enregistrer numéro et nom"],
  ["Scala di risoluzione", "Resolution scale", "Auflösungsskalierung", "Échelle de résolution"],
  ["Scendi in campo", "Take the field", "Aufs Feld", "Entrer sur le terrain"],
  ["Schedine, feed, classifiche", "Bet slips, feed, leaderboards", "Wettscheine, Feed, Ranglisten", "Bulletins, fil, classements"],
  ["Schermo intero", "Full screen", "Vollbild", "Plein écran"],
  ["Scommesse", "Bets", "Wetten", "Paris"],
  ["Scommesse dei giocatori", "Players' bets", "Wetten der Spieler", "Paris des joueurs"],
  ["Scommesse pubbliche di persone vere, dal server. Copiarne una la mette in schedina: la giocata parte solo quando confermi.", "Public bets by real people, from the server. Copying one puts it in your bet slip: the bet is only placed when you confirm.", "Öffentliche Wetten echter Personen, vom Server. Eine zu kopieren legt sie in den Wettschein: Gesetzt wird erst, wenn du bestätigst.", "Paris publics de vraies personnes, depuis le serveur. En copier un le met dans ton bulletin : le pari n'est placé que quand tu confirmes."],
  ["Scrivi il codice che ti ha dato chi ha creato la partita.", "Type the code you got from whoever created the match.", "Gib den Code ein, den du vom Ersteller des Spiels bekommen hast.", "Écris le code que t'a donné celui qui a créé le match."],
  ["Scrivi per cambiare il nome; vuoto = nome originale", "Type to change the name; empty = original name", "Tippen zum Ändern des Namens; leer = ursprünglicher Name", "Écris pour changer le nom ; vide = nom d'origine"],
  ["Se lo togli, le tue scommesse spariscono dal feed, dalle statistiche con nome e dalle classifiche. Si vedono solo quelle che condividi con il codice.", "If you turn it off, your bets disappear from the feed, from named statistics and from the leaderboards. Only the ones you share with the code are visible.", "Wenn du es ausschaltest, verschwinden deine Wetten aus dem Feed, aus den Statistiken mit Namen und aus den Ranglisten. Sichtbar sind nur die, die du mit dem Code teilst.", "Si tu le désactives, tes paris disparaissent du fil, des statistiques nominatives et des classements. Seuls ceux que tu partages avec le code sont visibles."],
  ["Selezione incompatibile", "Incompatible selection", "Nicht kombinierbare Auswahl", "Sélection incompatible"],
  ["Selezioni", "Selections", "Tipps", "Sélections"],
  ["Senza direzione, chi riceve il passaggio va incontro alla palla", "With no direction pressed, the receiver moves towards the ball", "Ohne Richtung läuft der Passempfänger dem Ball entgegen", "Sans direction, le receveur va au-devant du ballon"],
  ["Serie del server", "Server league", "Server-Liga", "Ligue du serveur"],
  ["Server dell'economia", "Economy server", "Wirtschaftsserver", "Serveur de l'économie"],
  ["Server dell'economia:", "Economy server:", "Wirtschaftsserver:", "Serveur de l'économie :"],
  ["Server online (facoltativo)", "Online server (optional)", "Online-Server (optional)", "Serveur en ligne (facultatif)"],
  ["Server online:", "Online server:", "Online-Server:", "Serveur en ligne :"],
  ["Shop", "Shop", "Shop", "Boutique"],
  ["Silenzioso", "Mute", "Stumm", "Muet"],
  ["Sostituisci", "Replace", "Ersetzen", "Remplacer"],
  ["Spettatori", "Spectators", "Zuschauer", "Spectateurs"],
  ["Squadra di casa", "Home team", "Heimteam", "Équipe à domicile"],
  ["Squadra di casa precedente", "Previous home team", "Vorheriges Heimteam", "Équipe à domicile précédente"],
  ["Squadra di casa successiva", "Next home team", "Nächstes Heimteam", "Équipe à domicile suivante"],
  ["Squadra ospite", "Away team", "Gastteam", "Équipe à l'extérieur"],
  ["Squadra ospite precedente", "Previous away team", "Vorheriges Gastteam", "Équipe à l'extérieur précédente"],
  ["Squadra ospite successiva", "Next away team", "Nächstes Gastteam", "Équipe à l'extérieur suivante"],
  ["Squadre", "Teams", "Teams", "Équipes"],
  ["Statistiche", "Statistics", "Statistiken", "Statistiques"],
  ["Statistiche scommesse", "Betting statistics", "Wettstatistiken", "Statistiques de paris"],
  ["Stato", "Status", "Status", "État"],
  ["Storico", "History", "Verlauf", "Historique"],
  ["Supplementari", "Extra time", "Verlängerung", "Prolongations"],
  ["Svuota", "Clear", "Leeren", "Vider"],
  ["Tastiera predefinita", "Default keyboard", "Standard-Tastatur", "Clavier par défaut"],
  ["Telecamera: Televisiva", "Camera: Broadcast", "Kamera: TV", "Caméra : Télévision"],
  ["Tipo", "Type", "Typ", "Type"],
  ["Top scommettitori", "Top bettors", "Top-Wetter", "Meilleurs parieurs"],
  ["Torna alla competizione", "Back to the competition", "Zurück zum Wettbewerb", "Retour à la compétition"],
  ["Torneo", "Tournament", "Turnier", "Tournoi"],
  ["Tu controlli", "You control", "Du steuerst", "Tu contrôles"],
  ["Tutti i tasti e i pulsanti si possono cambiare.", "All keys and buttons can be changed.", "Alle Tasten und Knöpfe lassen sich ändern.", "Toutes les touches et tous les boutons peuvent être changés."],
  ["Unisciti", "Join", "Beitreten", "Rejoindre"],
  ["Usa il controller (gamepad)", "Use the controller (gamepad)", "Controller verwenden (Gamepad)", "Utiliser la manette (gamepad)"],
  ["Vantaggio", "Advantage", "Vorteil", "Avantage"],
  ["Vibra per tiri, contrasti, pali e gol", "Vibrates for shots, tackles, posts and goals", "Vibriert bei Schüssen, Zweikämpfen, Pfosten und Toren", "Vibre pour les tirs, tacles, poteaux et buts"],
  ["Vibrazione", "Vibration", "Vibration", "Vibration"],
  ["Vincita possibile", "Potential winnings", "Möglicher Gewinn", "Gain possible"],
  ["Volume generale", "Master volume", "Gesamtlautstärke", "Volume général"],
  ["Vuoto = server predefinito del gioco (quello dell'economia): tutti allo stesso indirizzo, il codice sceglie la partita. Scrivi un indirizzo solo se usi un tuo server relay.", "Empty = the game's default server (the economy one): everyone at the same address, the code picks the match. Only enter an address if you use your own relay server.", "Leer = Standardserver des Spiels (der Wirtschaftsserver): alle an derselben Adresse, der Code wählt das Spiel. Gib nur eine Adresse ein, wenn du einen eigenen Relay-Server verwendest.", "Vide = serveur par défaut du jeu (celui de l'économie) : tout le monde à la même adresse, le code choisit le match. N'écris une adresse que si tu utilises ton propre serveur relais."],
  ["Zona morta levette", "Stick dead zone", "Stick-Totzone", "Zone morte des sticks"],
  ["nessuno", "none", "keiner", "aucun"],
  ["scommesse", "bets", "Wetten", "paris"],
]);
