// Partita: scritte della simulazione e dell'arbitro, comandi, caratteristiche dei giocatori, qualità grafica
// Ogni riga: [italiano, inglese, tedesco, francese]
addTranslations([
  ["Calcio d'inizio", "Kick-off", "Anstoss", "Coup d'envoi"],
  ["Rimessa laterale", "Throw-in", "Einwurf", "Touche"],
  ["Calcio d'angolo", "Corner kick", "Eckstoss", "Corner"],
  ["Rinvio dal fondo", "Goal kick", "Abstoss", "Six mètres"],
  ["Punizione", "Free kick", "Freistoss", "Coup franc"],
  ["Calcio di rigore", "Penalty kick", "Elfmeter", "Penalty"],
  ["Calci di rigore", "Penalty shoot-out", "Elfmeterschiessen", "Tirs au but"],
  ["Fuorigioco", "Offside", "Abseits", "Hors-jeu"],
  ["Autogol", "Own goal", "Eigentor", "But contre son camp"],
  ["Autogol!", "Own goal!", "Eigentor!", "But contre son camp !"],
  ["Autogol?", "Own goal?", "Eigentor?", "But contre son camp ?"],
  ["Parata", "Save", "Parade", "Arrêt"],
  ["Parata!", "Save!", "Parade!", "Arrêt !"],
  ["Parato!", "Saved!", "Gehalten!", "Arrêté !"],
  ["Fuori!", "Wide!", "Daneben!", "À côté !"],
  ["Niente gol!", "No goal!", "Kein Tor!", "Pas de but !"],
  ["Palo!", "Post!", "Pfosten!", "Poteau !"],
  ["Gol!", "Goal!", "Tor!", "But !"],
  ["Fine primo tempo", "Half time", "Halbzeit", "Mi-temps"],
  ["Fine primo tempo supplementare", "End of first half of extra time", "Ende der ersten Verlängerungshälfte", "Fin de la première mi-temps des prolongations"],
  ["Fine partita: parità, si ripeterà", "Full time: a draw, it will be replayed", "Spielende: unentschieden, es wird wiederholt", "Fin du match : égalité, il sera rejoué"],
  ["Parità: si va ai supplementari", "Level: we go to extra time", "Unentschieden: Es geht in die Verlängerung", "Égalité : on va aux prolongations"],
  ["Ripresa del gioco", "Restart of play", "Spielfortsetzung", "Reprise du jeu"],
  ["Vantaggio non concretizzato", "Advantage not realised", "Vorteil nicht genutzt", "Avantage non concrétisé"],
  ["Doppia ammonizione", "Second booking", "Gelb-Rot", "Deuxième avertissement"],
  ["Cartellino giallo — {0}", "Yellow card — {0}", "Gelbe Karte — {0}", "Carton jaune — {0}"],
  ["Cartellino rosso — {0}", "Red card — {0}", "Rote Karte — {0}", "Carton rouge — {0}"],
  ["Secondo giallo — {0} espulso", "Second yellow — {0} sent off", "Zweite Gelbe — {0} vom Platz gestellt", "Deuxième jaune — {0} expulsé"],
  ["Fallo — {t0}", "Foul — {t0}", "Foul — {t0}", "Faute — {t0}"],
  ["Rigori {0}-{1}", "Penalties {0}-{1}", "Elfmeter {0}-{1}", "Tirs au but {0}-{1}"],
  ["{0} vince ai rigori {1}-{2}", "{0} win on penalties {1}-{2}", "{0} gewinnt im Elfmeterschiessen {1}-{2}", "{0} gagne aux tirs au but {1}-{2}"],
  ["Contrasto irregolare", "Illegal tackle", "Regelwidriges Tackling", "Tacle irrégulier"],
  ["Contrasto pulito", "Clean tackle", "Sauberes Tackling", "Tacle propre"],
  ["Intervento a vuoto, nessun contatto", "Missed challenge, no contact", "Ins Leere, kein Kontakt", "Intervention dans le vide, aucun contact"],
  ["Contatto di gioco regolare", "Fair contact", "Regulärer Körperkontakt", "Contact de jeu régulier"],
  ["Carica da dietro", "Charge from behind", "Rempler von hinten", "Charge par derrière"],
  ["Prende il pallone, contatto regolare", "Wins the ball, fair contact", "Spielt den Ball, regulärer Kontakt", "Prend le ballon, contact régulier"],
  ["Intervento con forza eccessiva", "Challenge with excessive force", "Einsteigen mit übermässiger Härte", "Intervention avec force excessive"],
  ["Prende il pallone ma travolge l'avversario", "Wins the ball but runs through the opponent", "Spielt den Ball, rennt aber den Gegner um", "Prend le ballon mais renverse l'adversaire"],
  ["Intervento da dietro", "Challenge from behind", "Einsteigen von hinten", "Intervention par derrière"],
  ["Colpisce le gambe senza prendere il pallone", "Hits the legs without touching the ball", "Trifft die Beine, ohne den Ball zu spielen", "Touche les jambes sans prendre le ballon"],
  ["Grave fallo di gioco", "Serious foul play", "Grobes Foulspiel", "Faute grave"],
  ["Intervento imprudente", "Reckless challenge", "Rücksichtsloses Einsteigen", "Intervention imprudente"],
  ["Chiara occasione da rete negata", "Clear goalscoring opportunity denied", "Klare Torchance verhindert", "Occasion de but manifeste annulée"],
  ["Fallo tattico: interrompe un'azione promettente", "Tactical foul: stops a promising attack", "Taktisches Foul: unterbindet einen vielversprechenden Angriff", "Faute tactique : interrompt une action prometteuse"],
  ["Su", "Up", "Hoch", "Haut"],
  ["Giù", "Down", "Runter", "Bas"],
  ["Sinistra", "Left", "Links", "Gauche"],
  ["Destra", "Right", "Rechts", "Droite"],
  ["Scatto", "Sprint", "Sprint", "Sprint"],
  ["Passaggio / contrasto", "Pass / tackle", "Pass / Tackling", "Passe / tacle"],
  ["Lancio / cross", "Long ball / cross", "Langer Ball / Flanke", "Passe longue / centre"],
  ["Filtrante", "Through ball", "Steilpass", "Passe en profondeur"],
  ["Tiro (tieni premuto) / scivolata", "Shoot (hold) / slide tackle", "Schuss (halten) / Grätsche", "Tir (maintenir) / tacle glissé"],
  ["Cambio giocatore", "Switch player", "Spieler wechseln", "Changer de joueur"],
  ["Pressing (tieni premuto)", "Press (hold)", "Pressing (halten)", "Pressing (maintenir)"],
  ["Telecamera", "Camera", "Kamera", "Caméra"],
  ["Audio sì/no", "Sound on/off", "Ton an/aus", "Son oui/non"],
  ["Schermata comandi", "Controls screen", "Steuerungsübersicht", "Écran des commandes"],
  ["Croce ↑", "D-pad ↑", "Steuerkreuz ↑", "Croix ↑"],
  ["Croce ↓", "D-pad ↓", "Steuerkreuz ↓", "Croix ↓"],
  ["Croce ←", "D-pad ←", "Steuerkreuz ←", "Croix ←"],
  ["Croce →", "D-pad →", "Steuerkreuz →", "Croix →"],
  ["Shift dx", "Right Shift", "Umschalt rechts", "Maj droite"],
  ["Shift", "Shift", "Umschalt", "Maj"],
  ["Ctrl dx", "Right Ctrl", "Strg rechts", "Ctrl droite"],
  ["Ctrl", "Ctrl", "Strg", "Ctrl"],
  ["Cmd dx", "Right Cmd", "Cmd rechts", "Cmd droite"],
  ["Spazio", "Space", "Leertaste", "Espace"],
  ["Invio", "Enter", "Eingabe", "Entrée"],
  ["Esc", "Esc", "Esc", "Échap"],
  ["Clic sx", "Left click", "Linksklick", "Clic gauche"],
  ["Clic dx", "Right click", "Rechtsklick", "Clic droit"],
  ["Clic centrale", "Middle click", "Mittelklick", "Clic du milieu"],
  ["Num {0}", "Num {0}", "Num {0}", "Pavé {0}"],
  ["Pulsante {0}", "Button {0}", "Taste {0}", "Bouton {0}"],
  ["Bassa", "Low", "Niedrig", "Basse"],
  ["Media", "Medium", "Mittel", "Moyenne"],
  ["Alta", "High", "Hoch", "Haute"],
  ["Ultra", "Ultra", "Ultra", "Ultra"],
  ["Bomber", "Poacher", "Torjäger", "Buteur"],
  ["Muro", "Wall", "Mauer", "Mur"],
  ["Colpo di testa", "Header", "Kopfball", "Jeu de tête"],
  ["Instancabile", "Tireless", "Unermüdlich", "Infatigable"],
  ["Regista", "Playmaker", "Spielmacher", "Meneur de jeu"],
  ["Dribblatore", "Dribbler", "Dribbler", "Dribbleur"],
  ["Velocista", "Speedster", "Sprinter", "Sprinteur"],
  ["Para-rigori", "Penalty saver", "Elfmetertöter", "Arrêteur de penaltys"],
  ["colpi di testa più forti e precisi", "stronger and more accurate headers", "stärkere und präzisere Kopfbälle", "têtes plus puissantes et précises"],
  ["consuma meno energia", "uses less energy", "verbraucht weniger Energie", "consomme moins d'énergie"],
  ["contrasti più efficaci", "more effective tackles", "wirksamere Zweikämpfe", "tacles plus efficaces"],
  ["controllo palla migliore sotto pressione", "better ball control under pressure", "bessere Ballkontrolle unter Druck", "meilleur contrôle du ballon sous pression"],
  ["passaggi più precisi", "more accurate passes", "präzisere Pässe", "passes plus précises"],
  ["più riflessi sui tiri ravvicinati", "quicker reflexes on close-range shots", "bessere Reflexe bei Schüssen aus kurzer Distanz", "plus de réflexes sur les tirs de près"],
  ["sprint più rapido", "faster sprint", "schnellerer Sprint", "sprint plus rapide"],
  ["tiri più precisi in area", "more accurate shots in the box", "präzisere Schüsse im Strafraum", "tirs plus précis dans la surface"],
  ["Destro", "Right-footed", "Rechtsfuss", "Droitier"],
  ["Sinistro", "Left-footed", "Linksfuss", "Gaucher"],
  ["Difensiva", "Defensive", "Defensiv", "Défensive"],
  ["Equilibrata", "Balanced", "Ausgeglichen", "Équilibrée"],
  ["Offensiva", "Attacking", "Offensiv", "Offensive"],
  ["Codice partita non valido: sono 6 caratteri, lettere e numeri", "Invalid match code: it's 6 characters, letters and numbers", "Ungültiger Spielcode: 6 Zeichen, Buchstaben und Zahlen", "Code de match non valide : 6 caractères, lettres et chiffres"],
  ["Connessione scaduta: il server non risponde", "Connection timed out: the server isn't responding", "Zeitüberschreitung: Der Server antwortet nicht", "Délai de connexion dépassé : le serveur ne répond pas"],
  ["Il server non ha risposto", "The server didn't respond", "Der Server hat nicht geantwortet", "Le serveur n'a pas répondu"],
  ["Impossibile collegarsi al server", "Can't connect to the server", "Verbindung zum Server nicht möglich", "Impossible de se connecter au serveur"],
  ["Indirizzo del server non valido", "Invalid server address", "Ungültige Serveradresse", "Adresse du serveur non valide"],
  ["Risposta del server non valida", "Invalid server response", "Ungültige Serverantwort", "Réponse du serveur non valide"],
  ["Versione del gioco diversa (host {0}, tu {1})", "Different game version (host {0}, you {1})", "Andere Spielversion (Host {0}, du {1})", "Version du jeu différente (hôte {0}, toi {1})"],
  ["La partita sul tuo computer non coincide con quella del server: vale il risultato del server. Motore del server {0}, del gioco {1}.", "The match on your computer doesn't match the server's: the server's result counts. Server engine {0}, game engine {1}.", "Das Spiel auf deinem Computer stimmt nicht mit dem des Servers überein: Es zählt das Ergebnis des Servers. Engine des Servers {0}, des Spiels {1}.", "Le match sur ton ordinateur ne correspond pas à celui du serveur : c'est le résultat du serveur qui compte. Moteur du serveur {0}, du jeu {1}."],
  ["Sincronizzazione con il server… {0} s", "Syncing with the server… {0} s", "Synchronisierung mit dem Server… {0} s", "Synchronisation avec le serveur… {0} s"],
  ["Sincronizzazione con il server…", "Syncing with the server…", "Synchronisierung mit dem Server…", "Synchronisation avec le serveur…"],
  ["Premio spettatore +20 🪙", "Spectator reward +20 🪙", "Zuschauerprämie +20 🪙", "Prime du spectateur +20 🪙"],
]);
