// Gioco (src/14_game.js): schermate, comandi, partita, multiplayer e rete locale
// Ogni riga: [italiano, inglese, tedesco, francese]
addTranslations([
  ["(disattivato nelle impostazioni)", "(turned off in settings)", "(in den Einstellungen deaktiviert)", "(désactivé dans les paramètres)"],
  ["Alternativo", "Alternative", "Alternativ", "Alternative"],
  ["Alto", "High", "Hoch", "Haut"],
  ["Ammonizioni", "Bookings", "Verwarnungen", "Avertissements"],
  ["Annullato", "Cancelled", "Abgebrochen", "Annulé"],
  ["Attesa", "Waiting", "Warten", "Attente"],
  ["Audio attivo", "Sound on", "Ton an", "Son activé"],
  ["Audio disattivato", "Sound off", "Ton aus", "Son désactivé"],
  ["Avvio la partita su questo computer…", "Starting the match on this computer…", "Starte das Spiel auf diesem Computer…", "Lancement du match sur cet ordinateur…"],
  ["Azione", "Action", "Aktion", "Action"],
  ["Calci d'angolo", "Corners", "Eckstösse", "Corners"],
  ["Calci piazzati", "Set pieces", "Standardsituationen", "Coups de pied arrêtés"],
  ["Cambio", "Switch", "Wechsel", "Changer"],
  ["Cambio giocatore: il più vicino alla palla, o chi deve ricevere il tuo passaggio", "Switch player: the one closest to the ball, or whoever is receiving your pass", "Spielerwechsel: der Spieler am nächsten zum Ball oder der Empfänger deines Passes", "Changer de joueur : le plus proche du ballon, ou celui qui doit recevoir ta passe"],
  ["Cambio verso una direzione", "Switch towards a direction", "Wechsel in eine Richtung", "Changer vers une direction"],
  ["Camminata lenta", "Slow walk", "Langsam gehen", "Marche lente"],
  ["Caricamento…", "Loading…", "Wird geladen…", "Chargement…"],
  ["Chiudi la partita", "Close the match", "Spiel schliessen", "Fermer le match"],
  ["Chiudi la partita per tutti", "Close the match for everyone", "Spiel für alle schliessen", "Fermer le match pour tous"],
  ["Clic", "Click", "Klick", "Clic"],
  ["Codice", "Code", "Code", "Code"],
  ["Codice non valido per la rete locale: i codici delle partite in rete locale iniziano con L. Se la partita è su un server online, impostalo in Impostazioni → Online", "Invalid code for the local network: local network match codes start with L. If the match is on an online server, set it in Settings → Online", "Ungültiger Code für das lokale Netzwerk: Codes für Spiele im lokalen Netzwerk beginnen mit L. Ist das Spiel auf einem Online-Server, stelle ihn unter Einstellungen → Online ein", "Code non valide pour le réseau local : les codes des matchs en réseau local commencent par L. Si le match est sur un serveur en ligne, configure-le dans Paramètres → En ligne"],
  ["Codice partita non valido: sono 6 caratteri, lettere e numeri (senza 0, 1, I e O)", "Invalid match code: it's 6 characters, letters and numbers (no 0, 1, I or O)", "Ungültiger Spielcode: 6 Zeichen, Buchstaben und Zahlen (ohne 0, 1, I und O)", "Code de match non valide : 6 caractères, lettres et chiffres (sans 0, 1, I ni O)"],
  ["Collega un controller e premi un suo pulsante per assegnarlo", "Connect a controller and press one of its buttons to assign it", "Schliesse einen Controller an und drücke eine Taste, um sie zuzuweisen", "Branche une manette et appuie sur un de ses boutons pour l'attribuer"],
  ["Collegato", "Connected", "Verbunden", "Connecté"],
  ["Con l'account il nome è quello dell'account", "With an account, the name is the account name", "Mit Konto ist der Name der Kontoname", "Avec un compte, le nom est celui du compte"],
  ["Con la palla", "With the ball", "Mit Ball", "Avec le ballon"],
  ["Senza palla", "Without the ball", "Ohne Ball", "Sans le ballon"],
  ["Conferma", "Confirm", "Bestätigen", "Confirmer"],
  ["Connessione al server persa e non ripristinata", "Connection to the server lost and not restored", "Verbindung zum Server verloren und nicht wiederhergestellt", "Connexion au serveur perdue et non rétablie"],
  ["Connessione al server persa: la partita continua offline", "Connection to the server lost: the match continues offline", "Verbindung zum Server verloren: Das Spiel läuft offline weiter", "Connexion au serveur perdue : le match continue hors ligne"],
  ["Connessione persa: provo a rientrare…", "Connection lost: trying to rejoin…", "Verbindung verloren: versuche wieder beizutreten…", "Connexion perdue : tentative de reconnexion…"],
  ["Connessione ripristinata", "Connection restored", "Verbindung wiederhergestellt", "Connexion rétablie"],
  ["Contrasto", "Tackle", "Tackling", "Tacle"],
  ["Contrasto: regolare se prendi il pallone (di fronte o di lato); da dietro, attraverso le gambe, è fallo", "Tackle: fair if you win the ball (from the front or side); from behind, through the legs, it's a foul", "Tackling: regulär, wenn du den Ball spielst (von vorne oder der Seite); von hinten, durch die Beine, ist es ein Foul", "Tacle : régulier si tu prends le ballon (de face ou de côté) ; par derrière, à travers les jambes, c'est une faute"],
  ["Controller collegato", "Controller connected", "Controller verbunden", "Manette connectée"],
  ["Controller collegato: {0}", "Controller connected: {0}", "Controller verbunden: {0}", "Manette connectée : {0}"],
  ["Controller collegato{t0}.", "Controller connected{t0}.", "Controller verbunden{t0}.", "Manette connectée{t0}."],
  ["Controller disattivato.", "Controller turned off.", "Controller deaktiviert.", "Manette désactivée."],
  ["Controller scollegato", "Controller disconnected", "Controller getrennt", "Manette déconnectée"],
  [", ma disattivato nelle impostazioni", ", but turned off in settings", ", aber in den Einstellungen deaktiviert", ", mais désactivée dans les paramètres"],
  ["Crea in rete locale", "Create on local network", "Im lokalen Netzwerk erstellen", "Créer en réseau local"],
  ["Crea partita online", "Create online match", "Online-Spiel erstellen", "Créer un match en ligne"],
  ["Creo la partita online…", "Creating the online match…", "Online-Spiel wird erstellt…", "Création du match en ligne…"],
  ["Croce o levetta sinistra", "D-pad or left stick", "Steuerkreuz oder linker Stick", "Croix ou stick gauche"],
  ["Dietro al giocatore", "Behind the player", "Hinter dem Spieler", "Derrière le joueur"],
  ["Televisiva", "Broadcast", "TV", "Télévision"],
  ["Larga", "Wide", "Weit", "Large"],
  ["Difficile", "Hard", "Schwer", "Difficile"],
  ["Normale", "Normal", "Normal", "Normale"],
  ["Facile", "Easy", "Leicht", "Facile"],
  ["Disattiva", "Turn off", "Deaktivieren", "Désactiver"],
  ["Disconnesso", "Disconnected", "Getrennt", "Déconnecté"],
  ["Eliminati", "Knocked out", "Ausgeschieden", "Éliminés"],
  ["Qualificati", "Through", "Weiter", "Qualifiés"],
  ["Vittoria", "Win", "Sieg", "Victoire"],
  ["Sconfitta", "Defeat", "Niederlage", "Défaite"],
  ["Pareggio", "Draw", "Unentschieden", "Match nul"],
  ["Vittoria ai rigori", "Won on penalties", "Sieg im Elfmeterschiessen", "Victoire aux tirs au but"],
  ["Sconfitta ai rigori", "Lost on penalties", "Niederlage im Elfmeterschiessen", "Défaite aux tirs au but"],
  ["Errore", "Error", "Fehler", "Erreur"],
  ["Esci dalla partita", "Leave the match", "Spiel verlassen", "Quitter le match"],
  ["Espulsioni", "Sendings-off", "Platzverweise", "Expulsions"],
  ["Falli", "Fouls", "Fouls", "Fautes"],
  ["Fine", "End", "Ende", "Fin"],
  ["Forza", "Strength", "Stärke", "Force"],
  ["Frecce o Tab", "Arrows or Tab", "Pfeiltasten oder Tab", "Flèches ou Tab"],
  ["Giocatore", "Player", "Spieler", "Joueur"],
  ["Host disconnesso: ha chiuso il gioco", "Host disconnected: they closed the game", "Host getrennt: hat das Spiel geschlossen", "Hôte déconnecté : il a fermé le jeu"],
  ["Host disconnesso: lo aspetto qualche secondo", "Host disconnected: waiting a few seconds for them", "Host getrennt: ich warte ein paar Sekunden", "Hôte déconnecté : je l'attends quelques secondes"],
  ["Host disconnesso: lo aspetto qualche secondo…", "Host disconnected: waiting a few seconds for them…", "Host getrennt: ich warte ein paar Sekunden…", "Hôte déconnecté : je l'attends quelques secondes…"],
  ["Host disconnesso: non è più raggiungibile in rete e la connessione non si è ripristinata", "Host disconnected: no longer reachable on the network and the connection wasn't restored", "Host getrennt: im Netzwerk nicht mehr erreichbar, die Verbindung wurde nicht wiederhergestellt", "Hôte déconnecté : il n'est plus joignable sur le réseau et la connexion n'a pas été rétablie"],
  ["IP locali", "Local IPs", "Lokale IPs", "IP locales"],
  ["Il browser non ha permesso lo schermo intero", "The browser didn't allow full screen", "Der Browser hat den Vollbildmodus nicht erlaubt", "Le navigateur n'a pas autorisé le plein écran"],
  ["Il server è stato spento", "The server was shut down", "Der Server wurde heruntergefahren", "Le serveur a été arrêté"],
  ["Indirizzo dell'host non valido: scrivi quattro numeri da 0 a 255, per esempio 192.168.1.23 oppure 192.168.1.23:8787", "Invalid host address: type four numbers from 0 to 255, for example 192.168.1.23 or 192.168.1.23:8787", "Ungültige Host-Adresse: Gib vier Zahlen von 0 bis 255 ein, zum Beispiel 192.168.1.23 oder 192.168.1.23:8787", "Adresse de l'hôte non valide : écris quatre nombres de 0 à 255, par exemple 192.168.1.23 ou 192.168.1.23:8787"],
  ["Invita", "Invite", "Einladen", "Inviter"],
  ["Invita {0}", "Invite {0}", "{0} einladen", "Inviter {0}"],
  ["Invitato: {0}", "Invited: {0}", "Eingeladen: {0}", "Invité : {0}"],
  ["L'host ha chiuso la partita", "The host closed the match", "Der Host hat das Spiel geschlossen", "L'hôte a fermé le match"],
  ["L'host è tornato", "The host is back", "Der Host ist zurück", "L'hôte est revenu"],
  ["L'indirizzo deve iniziare con ws:// oppure wss://", "The address must start with ws:// or wss://", "Die Adresse muss mit ws:// oder wss:// beginnen", "L'adresse doit commencer par ws:// ou wss://"],
  ["La partita gira su questo computer, che fa anche da server: gli amici sulla stessa rete (Wi-Fi o cavo) entrano con il codice, senza indirizzi IP. Se Windows chiede il permesso del firewall, consentilo.", "The match runs on this computer, which is also the server: friends on the same network (Wi-Fi or cable) join with the code, no IP addresses needed. If Windows asks for firewall permission, allow it.", "Das Spiel läuft auf diesem Computer, der auch Server ist: Freunde im selben Netzwerk (WLAN oder Kabel) treten mit dem Code bei, ohne IP-Adressen. Wenn Windows nach der Firewall-Erlaubnis fragt, erlaube sie.", "Le match tourne sur cet ordinateur, qui sert aussi de serveur : les amis sur le même réseau (Wi-Fi ou câble) rejoignent avec le code, sans adresse IP. Si Windows demande l'autorisation du pare-feu, autorise-la."],
  ["La partita è al completo", "The match is full", "Das Spiel ist voll", "Le match est complet"],
  ["La partita è stata chiusa", "The match was closed", "Das Spiel wurde geschlossen", "Le match a été fermé"],
  ["Lancio", "Long ball", "Langer Ball", "Passe longue"],
  ["Lancio lungo o cross", "Long ball or cross", "Langer Ball oder Flanke", "Passe longue ou centre"],
  ["Levetta destra (colpetto)", "Right stick (flick)", "Rechter Stick (antippen)", "Stick droit (petite pression)"],
  ["Levetta poco inclinata", "Stick slightly tilted", "Stick leicht geneigt", "Stick légèrement incliné"],
  ["Levetta sinistra", "Left stick", "Linker Stick", "Stick gauche"],
  ["Levetta sinistra o croce", "Left stick or D-pad", "Linker Stick oder Steuerkreuz", "Stick gauche ou croix"],
  ["Mando il risultato al server…", "Sending the result to the server…", "Ergebnis wird an den Server gesendet…", "Envoi du résultat au serveur…"],
  ["Modalità", "Mode", "Modus", "Mode"],
  ["Movimento", "Movement", "Bewegung", "Déplacement"],
  ["Muovi il calciatore", "Move the player", "Spieler bewegen", "Déplacer le joueur"],
  ["NON attiva (porta occupata)", "NOT active (port in use)", "NICHT aktiv (Port belegt)", "NON active (port occupé)"],
  ["Nativa", "Native", "Nativ", "Native"],
  ["Nessun controller collegato. Collegalo (USB o Bluetooth) e premi un pulsante.", "No controller connected. Connect it (USB or Bluetooth) and press a button.", "Kein Controller verbunden. Schliesse ihn an (USB oder Bluetooth) und drücke eine Taste.", "Aucune manette connectée. Branche-la (USB ou Bluetooth) et appuie sur un bouton."],
  ["Nessun controller collegato: collegalo e premi un pulsante.", "No controller connected: connect it and press a button.", "Kein Controller verbunden: Schliesse ihn an und drücke eine Taste.", "Aucune manette connectée : branche-la et appuie sur un bouton."],
  ["Nessun gol", "No goals", "Keine Tore", "Aucun but"],
  ["Nessun server online impostato: aggiungilo in Impostazioni → Online", "No online server set: add it in Settings → Online", "Kein Online-Server eingestellt: Füge ihn unter Einstellungen → Online hinzu", "Aucun serveur en ligne configuré : ajoute-le dans Paramètres → En ligne"],
  ["Nessun server: si gioca in rete locale", "No server: playing on the local network", "Kein Server: Es wird im lokalen Netzwerk gespielt", "Aucun serveur : on joue en réseau local"],
  ["Nessuna (guardo)", "None (watching)", "Keins (ich schaue zu)", "Aucune (je regarde)"],
  ["Nessuna partita con questo codice sul server", "No match with this code on the server", "Kein Spiel mit diesem Code auf dem Server", "Aucun match avec ce code sur le serveur"],
  ["Nessuno", "None", "Keiner", "Aucun"],
  ["Non riesco ad avviare il server della partita su questo computer", "Can't start the match server on this computer", "Der Spielserver kann auf diesem Computer nicht gestartet werden", "Impossible de lancer le serveur du match sur cet ordinateur"],
  ["Partita creata, ma questo computer non è collegato a nessuna rete", "Match created, but this computer isn't connected to any network", "Spiel erstellt, aber dieser Computer ist mit keinem Netzwerk verbunden", "Match créé, mais cet ordinateur n'est connecté à aucun réseau"],
  ["Partita del server: il tempo continua mentre sei in questo menu.", "Server match: time keeps running while you're in this menu.", "Server-Spiel: Die Zeit läuft weiter, während du in diesem Menü bist.", "Match du serveur : le temps continue pendant que tu es dans ce menu."],
  ["Partita già iniziata: la guardi come spettatore", "Match already started: you're watching as a spectator", "Spiel hat schon begonnen: Du schaust als Zuschauer zu", "Match déjà commencé : tu le regardes en spectateur"],
  ["Partita terminata", "Match over", "Spiel beendet", "Match terminé"],
  ["Passaggi riusciti", "Completed passes", "Angekommene Pässe", "Passes réussies"],
  ["Passaggio", "Pass", "Pass", "Passe"],
  ["Passaggio filtrante (nello spazio davanti al compagno)", "Through ball (into the space ahead of a teammate)", "Steilpass (in den Raum vor den Mitspieler)", "Passe en profondeur (dans l'espace devant le coéquipier)"],
  ["Passaggio rasoterra: verso la direzione; senza direzione al compagno più libero", "Ground pass: in the chosen direction; with no direction, to the most open teammate", "Flachpass: in die gewählte Richtung; ohne Richtung zum freiesten Mitspieler", "Passe à ras de terre : vers la direction ; sans direction, au coéquipier le plus libre"],
  ["Passaggio teso (più veloce) e filtrante alto", "Driven pass (faster) and lofted through ball", "Scharfer Pass (schneller) und hoher Steilpass", "Passe tendue (plus rapide) et passe en profondeur lobée"],
  ["Pausa (tattica, impostazioni, ricomincia)", "Pause (tactics, settings, restart)", "Pause (Taktik, Einstellungen, Neustart)", "Pause (tactique, paramètres, recommencer)"],
  ["Ping", "Ping", "Ping", "Ping"],
  ["Ping dell'host al server e fotogrammi al secondo del suo computer", "Host's ping to the server and frames per second on their computer", "Ping des Hosts zum Server und Bilder pro Sekunde seines Computers", "Ping de l'hôte vers le serveur et images par seconde de son ordinateur"],
  ["PlayStation", "PlayStation", "PlayStation", "PlayStation"],
  ["Porta", "Port", "Port", "Port"],
  ["Possesso", "Possession", "Ballbesitz", "Possession"],
  ["Premi un pulsante…", "Press a button…", "Drücke eine Taste…", "Appuie sur un bouton…"],
  ["Premi…", "Press…", "Drücke…", "Appuie…"],
  ["Premi… (⌫ toglie)", "Press… (⌫ removes)", "Drücke… (⌫ entfernt)", "Appuie… (⌫ retire)"],
  ["Pressing: tieni premuto e il calciatore va da solo sul portatore o sulla palla", "Pressing: hold it and the player goes for the ball carrier or the ball by himself", "Pressing: Halte gedrückt und der Spieler geht von selbst auf den Ballführenden oder den Ball", "Pressing : maintiens et le joueur va tout seul sur le porteur ou le ballon"],
  ["Provo…", "Trying…", "Versuche…", "Essai…"],
  ["Pulsanti del controller predefiniti", "Default controller buttons", "Standard-Controllertasten", "Boutons de manette par défaut"],
  ["Punizione: passaggio, lancio, filtrante oppure tiro caricato", "Free kick: pass, long ball, through ball or charged shot", "Freistoss: Pass, langer Ball, Steilpass oder aufgeladener Schuss", "Coup franc : passe, passe longue, passe en profondeur ou tir chargé"],
  ["Questa schermata", "This screen", "Diese Übersicht", "Cet écran"],
  ["Questo computer non riesce a inviare messaggi nella rete locale: firewall o antivirus devono consentire Campo Aperto{0}", "This computer can't send messages on the local network: the firewall or antivirus must allow Campo Aperto{0}", "Dieser Computer kann keine Nachrichten im lokalen Netzwerk senden: Firewall oder Virenschutz müssen Campo Aperto erlauben{0}", "Cet ordinateur n'arrive pas à envoyer de messages sur le réseau local : le pare-feu ou l'antivirus doivent autoriser Campo Aperto{0}"],
  ["Questo è il codice di una partita in rete locale: per entrare serve l'app desktop di Campo Aperto", "This is a local network match code: you need the Campo Aperto desktop app to join", "Das ist der Code eines Spiels im lokalen Netzwerk: Zum Beitreten brauchst du die Desktop-App von Campo Aperto", "C'est le code d'un match en réseau local : pour rejoindre, il faut l'application de bureau de Campo Aperto"],
  ["Ricerca in rete locale: UDP broadcast e scansione della sottorete{0}", "Local network search: UDP broadcast and subnet scan{0}", "Suche im lokalen Netzwerk: UDP-Broadcast und Scan des Subnetzes{0}", "Recherche en réseau local : broadcast UDP et scan du sous-réseau{0}"],
  ["Ricerche", "Searches", "Suchen", "Recherches"],
  ["Ricevi un codice di 6 caratteri da dare agli amici: entrano da casa loro, ovunque siano, senza indirizzi IP né porte da aprire. La partita la simula il tuo computer: scegli tu squadre e durata e avvii quando siete pronti.", "You get a 6-character code to give your friends: they join from home, wherever they are, without IP addresses or ports to open. Your computer simulates the match: you choose teams and length and start when you're all ready.", "Du erhältst einen 6-stelligen Code für deine Freunde: Sie treten von zu Hause bei, wo immer sie sind, ohne IP-Adressen oder Ports zu öffnen. Dein Computer simuliert das Spiel: Du wählst Teams und Dauer und startest, wenn alle bereit sind.", "Tu reçois un code de 6 caractères à donner à tes amis : ils rejoignent de chez eux, où qu'ils soient, sans adresse IP ni port à ouvrir. Ton ordinateur simule le match : tu choisis les équipes et la durée et tu lances quand vous êtes prêts."],
  ["Riconnessione…", "Reconnecting…", "Verbinde neu…", "Reconnexion…"],
  ["Rigore contro: tieni su o giù per scegliere dove si tuffa il tuo portiere", "Penalty against: hold up or down to choose where your keeper dives", "Elfmeter gegen dich: Halte hoch oder runter, um zu wählen, wohin dein Torhüter springt", "Penalty contre : maintiens haut ou bas pour choisir où plonge ton gardien"],
  ["Rigore: carica il tiro, su o giù per il lato", "Penalty: charge the shot, up or down for the side", "Elfmeter: Schuss aufladen, hoch oder runter für die Seite", "Penalty : charge le tir, haut ou bas pour le côté"],
  ["Rimessa, corner, rinvio, calcio d'inizio: passaggio corto o lancio, con o senza direzione", "Throw-in, corner, goal kick, kick-off: short pass or long ball, with or without a direction", "Einwurf, Ecke, Abstoss, Anstoss: kurzer Pass oder langer Ball, mit oder ohne Richtung", "Touche, corner, six mètres, coup d'envoi : passe courte ou longue, avec ou sans direction"],
  ["Risposta non valida: all'indirizzo indicato non c'è un server di Campo Aperto", "Invalid response: there's no Campo Aperto server at that address", "Ungültige Antwort: An dieser Adresse gibt es keinen Campo-Aperto-Server", "Réponse non valide : il n'y a pas de serveur Campo Aperto à cette adresse"],
  ["Ritardo alto verso l'host pur con il server vicino: probabilmente la connessione dell'host in uscita. Provate a far ospitare un altro.", "High delay to the host even though the server is close: probably the host's upload connection. Try letting someone else host.", "Hohe Verzögerung zum Host, obwohl der Server nah ist: wahrscheinlich die Upload-Verbindung des Hosts. Lasst jemand anderen hosten.", "Délai élevé vers l'hôte malgré un serveur proche : probablement la connexion sortante de l'hôte. Essayez de faire héberger quelqu'un d'autre."],
  ["Ritardo verso l'host (andata e ritorno, passando dal server); tra parentesi il ritardo verso il server", "Delay to the host (round trip, via the server); in brackets the delay to the server", "Verzögerung zum Host (Hin- und Rückweg über den Server); in Klammern die Verzögerung zum Server", "Délai vers l'hôte (aller-retour, via le serveur) ; entre parenthèses le délai vers le serveur"],
  ["Ruolo", "Role", "Rolle", "Rôle"],
  ["Salta il replay", "Skip replay", "Wiederholung überspringen", "Passer le ralenti"],
  ["Scatto (tieni premuto, consuma energia)", "Sprint (hold, uses energy)", "Sprint (halten, verbraucht Energie)", "Sprint (maintenir, consomme de l'énergie)"],
  ["Schede delle impostazioni", "Settings tabs", "Einstellungsreiter", "Onglets des paramètres"],
  ["Schermo", "Screen", "Bildschirm", "Écran"],
  ["Schermo intero non disponibile qui. Nell'app usa F11.", "Full screen isn't available here. In the app, use F11.", "Vollbild ist hier nicht verfügbar. In der App F11 verwenden.", "Plein écran non disponible ici. Dans l'application, utilise F11."],
  ["Scivolata", "Slide tackle", "Grätsche", "Tacle glissé"],
  ["Scivolata: se manchi il pallone travolgi l'avversario (fallo, spesso cartellino)", "Slide tackle: if you miss the ball you take out the opponent (foul, often a card)", "Grätsche: Verfehlst du den Ball, triffst du den Gegner (Foul, oft eine Karte)", "Tacle glissé : si tu rates le ballon, tu fauches l'adversaire (faute, souvent un carton)"],
  ["Scrivi un indirizzo che inizia con https://", "Enter an address starting with https://", "Gib eine Adresse ein, die mit https:// beginnt", "Écris une adresse qui commence par https://"],
  ["Sei collegato alla partita. Scegli una squadra e aspetta l'avvio.{t0}", "You're connected to the match. Choose a team and wait for the start.{t0}", "Du bist mit dem Spiel verbunden. Wähle ein Team und warte auf den Start.{t0}", "Tu es connecté au match. Choisis une équipe et attends le début.{t0}"],
  ["Sei l'host: la partita gira sul tuo computer. Tieni aperto il gioco finché giocate.{t0}", "You're the host: the match runs on your computer. Keep the game open while you play.{t0}", "Du bist der Host: Das Spiel läuft auf deinem Computer. Lass das Spiel offen, solange ihr spielt.{t0}", "Tu es l'hôte : le match tourne sur ton ordinateur. Garde le jeu ouvert pendant que vous jouez.{t0}"],
  ["Sei stato tolto dalla partita", "You were removed from the match", "Du wurdest aus dem Spiel entfernt", "Tu as été retiré du match"],
  ["Server", "Server", "Server", "Serveur"],
  ["Server perso: la partita continua offline", "Server lost: the match continues offline", "Server verloren: Das Spiel läuft offline weiter", "Serveur perdu : le match continue hors ligne"],
  ["Server raggiungibile", "Server reachable", "Server erreichbar", "Serveur joignable"],
  ["Server raggiungibile, ma è su questo computer: gli altri giocatori non lo vedono", "Server reachable, but it's on this computer: other players can't see it", "Server erreichbar, aber er ist auf diesem Computer: Andere Spieler sehen ihn nicht", "Serveur joignable, mais il est sur cet ordinateur : les autres joueurs ne le voient pas"],
  ["Server raggiungibile, stesso motore del gioco: le partite si guardano in 3D", "Server reachable, same engine as the game: matches can be watched in 3D", "Server erreichbar, gleiche Engine wie das Spiel: Die Spiele lassen sich in 3D ansehen", "Serveur joignable, même moteur que le jeu : les matchs se regardent en 3D"],
  ["Server raggiungibile, ma con un altro motore ({0}): aggiorna il gioco o il server per guardare le partite in 3D", "Server reachable, but with a different engine ({0}): update the game or the server to watch matches in 3D", "Server erreichbar, aber mit einer anderen Engine ({0}): Aktualisiere das Spiel oder den Server, um die Spiele in 3D zu sehen", "Serveur joignable, mais avec un autre moteur ({0}) : mets à jour le jeu ou le serveur pour regarder les matchs en 3D"],
  ["Sicuro? Esci", "Sure? Quit", "Sicher? Beenden", "Sûr ? Quitter"],
  ["Sicuro? Ricomincia", "Sure? Restart", "Sicher? Neu starten", "Sûr ? Recommencer"],
  ["Spostati tra i pulsanti", "Move between buttons", "Zwischen den Knöpfen wechseln", "Se déplacer entre les boutons"],
  ["Squadra al completo", "Team full", "Team voll", "Équipe complète"],
  ["Tasti della tastiera predefiniti", "Default keyboard keys", "Standard-Tastaturbelegung", "Touches du clavier par défaut"],
  ["Tasto", "Key", "Taste", "Touche"],
  ["Tieni premuto", "Hold", "Gedrückt halten", "Maintenir"],
  ["Tieni su o giù quando parte il tiro: il portiere si tuffa da quella parte", "Hold up or down when the shot is taken: the keeper dives that way", "Halte hoch oder runter, wenn geschossen wird: Der Torhüter springt in diese Ecke", "Maintiens haut ou bas au moment du tir : le gardien plonge de ce côté"],
  ["Tiri", "Shots", "Schüsse", "Tirs"],
  ["Tiri in porta", "Shots on target", "Schüsse aufs Tor", "Tirs cadrés"],
  ["Tiro", "Shot", "Schuss", "Tir"],
  ["Tiro a giro: tieni premuto anche questo tasto mentre tiri", "Curled shot: hold this key too while shooting", "Angeschnittener Schuss: Halte beim Schiessen auch diese Taste gedrückt", "Tir enroulé : maintiens aussi cette touche en tirant"],
  ["Tiro: tieni premuto per caricare, rilascia per calciare. Carica corta = piatto rasoterra, piena = tiro potente (rischia di andare alto). Su o giù scelgono il palo", "Shoot: hold to charge, release to kick. Short charge = low side-foot, full = powerful shot (may go high). Up or down pick the post", "Schuss: Halten zum Aufladen, loslassen zum Schiessen. Kurz aufgeladen = flacher Innenrist, voll = harter Schuss (kann zu hoch gehen). Hoch oder runter wählen den Pfosten", "Tir : maintiens pour charger, relâche pour frapper. Charge courte = plat du pied à ras de terre, pleine = tir puissant (risque de partir haut). Haut ou bas choisissent le poteau"],
  ["Torna al centro partita", "Back to the match centre", "Zurück zum Spielzentrum", "Retour au centre du match"],
  ["Torna alla lobby", "Back to the lobby", "Zurück zur Lobby", "Retour au salon"],
  ["Trasporto", "Transport", "Transport", "Transport"],
  ["Troppi tentativi con codici sbagliati: aspetta un minuto e riprova", "Too many attempts with wrong codes: wait a minute and try again", "Zu viele Versuche mit falschen Codes: Warte eine Minute und versuche es erneut", "Trop de tentatives avec de mauvais codes : attends une minute et réessaie"],
  ["Tutti i tuoi amici sono già qui (o non hai ancora amici: aggiungili dal pannello Amici).", "All your friends are already here (or you don't have friends yet: add them from the Friends panel).", "Alle deine Freunde sind schon hier (oder du hast noch keine Freunde: Füge sie im Freunde-Bereich hinzu).", "Tous tes amis sont déjà là (ou tu n'as pas encore d'amis : ajoute-les depuis le panneau Amis)."],
  ["Versione", "Version", "Version", "Version"],
  ["Versione {0}, app desktop", "Version {0}, desktop app", "Version {0}, Desktop-App", "Version {0}, application de bureau"],
  ["Versione {0}, browser", "Version {0}, browser", "Version {0}, Browser", "Version {0}, navigateur"],
  ["Xbox", "Xbox", "Xbox", "Xbox"],
  ["in attesa", "waiting", "wartet", "en attente"],
  ["non attiva", "not active", "nicht aktiv", "non active"],
  ["non collegato", "not connected", "nicht verbunden", "non connecté"],
  ["non disponibili nel browser", "not available in the browser", "im Browser nicht verfügbar", "non disponibles dans le navigateur"],
  ["nessuna rete", "no network", "kein Netzwerk", "aucun réseau"],
  ["nessuna rete trovata", "no network found", "kein Netzwerk gefunden", "aucun réseau trouvé"],
  ["nessuno, si gioca in rete locale", "none, playing on the local network", "keiner, es wird im lokalen Netzwerk gespielt", "aucun, on joue en réseau local"],
  ["rete locale", "local network", "lokales Netzwerk", "réseau local"],
  ["rete locale disponibile", "local network available", "lokales Netzwerk verfügbar", "réseau local disponible"],
  ["server online", "online server", "Online-Server", "serveur en ligne"],
  ["solo server online", "online server only", "nur Online-Server", "serveur en ligne uniquement"],
  ["connessione persa", "connection lost", "Verbindung verloren", "connexion perdue"],
  ["macOS sta bloccando l'accesso alla rete locale. Apri Impostazioni di Sistema → Privacy e sicurezza → Rete locale e attiva Campo Aperto (o il Terminale, se avvii il gioco da lì), poi riavvia il gioco.", "macOS is blocking access to the local network. Open System Settings → Privacy & Security → Local Network and turn on Campo Aperto (or Terminal, if you start the game from there), then restart the game.", "macOS blockiert den Zugriff auf das lokale Netzwerk. Öffne Systemeinstellungen → Datenschutz & Sicherheit → Lokales Netzwerk und aktiviere Campo Aperto (oder das Terminal, wenn du das Spiel von dort startest), dann starte das Spiel neu.", "macOS bloque l'accès au réseau local. Ouvre Réglages Système → Confidentialité et sécurité → Réseau local et active Campo Aperto (ou le Terminal, si tu lances le jeu depuis là), puis redémarre le jeu."],
  ["macOS sta bloccando l'accesso alla rete locale. Apri Impostazioni di Sistema → Privacy e sicurezza → Rete locale e attiva Campo Aperto (o il Terminale, se avvii il gioco da lì), poi riavvia il gioco.{0}", "macOS is blocking access to the local network. Open System Settings → Privacy & Security → Local Network and turn on Campo Aperto (or Terminal, if you start the game from there), then restart the game.{0}", "macOS blockiert den Zugriff auf das lokale Netzwerk. Öffne Systemeinstellungen → Datenschutz & Sicherheit → Lokales Netzwerk und aktiviere Campo Aperto (oder das Terminal, wenn du das Spiel von dort startest), dann starte das Spiel neu.{0}", "macOS bloque l'accès au réseau local. Ouvre Réglages Système → Confidentialité et sécurité → Réseau local et active Campo Aperto (ou le Terminal, si tu lances le jeu depuis là), puis redémarre le jeu.{0}"],
  ["{0} s fa", "{0} s ago", "vor {0} s", "il y a {0} s"],
  ["Altri indirizzi: {0}", "Other addresses: {0}", "Weitere Adressen: {0}", "Autres adresses : {0}"],
  ["Cerco la partita {0}…", "Looking for match {0}…", "Suche Spiel {0}…", "Recherche du match {0}…"],
  ["Codice copiato: {0}", "Code copied: {0}", "Code kopiert: {0}", "Code copié : {0}"],
  ["Collegamento WebSocket a {0}", "WebSocket connection to {0}", "WebSocket-Verbindung zu {0}", "Connexion WebSocket à {0}"],
  ["Connessione scaduta: il server multiplayer {0} non risponde. Controlla la connessione e l'indirizzo in Impostazioni → Online", "Connection timed out: the multiplayer server {0} isn't responding. Check your connection and the address in Settings → Online", "Zeitüberschreitung: Der Mehrspieler-Server {0} antwortet nicht. Prüfe die Verbindung und die Adresse unter Einstellungen → Online", "Délai dépassé : le serveur multijoueur {0} ne répond pas. Vérifie la connexion et l'adresse dans Paramètres → En ligne"],
  ["Connessione scaduta: il server {0} accetta il collegamento ma non risponde", "Connection timed out: the server {0} accepts the connection but doesn't respond", "Zeitüberschreitung: Der Server {0} nimmt die Verbindung an, antwortet aber nicht", "Délai dépassé : le serveur {0} accepte la connexion mais ne répond pas"],
  ["Connessione scaduta: l'host {0}:{1} accetta il collegamento ma non risponde", "Connection timed out: the host {0}:{1} accepts the connection but doesn't respond", "Zeitüberschreitung: Der Host {0}:{1} nimmt die Verbindung an, antwortet aber nicht", "Délai dépassé : l'hôte {0}:{1} accepte la connexion mais ne répond pas"],
  ["Copia non riuscita: il codice è {0}", "Copy failed: the code is {0}", "Kopieren fehlgeschlagen: Der Code ist {0}", "Échec de la copie : le code est {0}"],
  ["Copia non riuscita: l'indirizzo è {0}", "Copy failed: the address is {0}", "Kopieren fehlgeschlagen: Die Adresse ist {0}", "Échec de la copie : l'adresse est {0}"],
  ["Da tenere d'occhio: {0}", "Players to watch: {0}", "Im Auge behalten: {0}", "À surveiller : {0}"],
  ["Durata di un tempo {0} minuti, IA {t1}.", "Half length {0} minutes, AI {t1}.", "Halbzeitdauer {0} Minuten, KI {t1}.", "Durée d'une mi-temps {0} minutes, IA {t1}."],
  ["Entrato nella partita {0}", "Joined match {0}", "Spiel {0} beigetreten", "Match {0} rejoint"],
  ["Entro nella partita {0} su {1}…", "Joining match {0} on {1}…", "Trete Spiel {0} auf {1} bei…", "Connexion au match {0} sur {1}…"],
  ["Entro nella partita {0}…", "Joining match {0}…", "Trete Spiel {0} bei…", "Connexion au match {0}…"],
  ["Forza {0}, allenatore {1}", "Rating {0}, coach {1}", "Stärke {0}, Trainer {1}", "Force {0}, entraîneur {1}"],
  ["Giocatore {0}: {1}", "Player {0}: {1}", "Spieler {0}: {1}", "Joueur {0} : {1}"],
  ["Host non raggiungibile a {0}:{1}:", "Host not reachable at {0}:{1}:", "Host nicht erreichbar unter {0}:{1}:", "Hôte injoignable à {0}:{1} :"],
  ["Partita trovata a {0}:{1}, ma impossibile raggiungere l'host:", "Match found at {0}:{1}, but the host can't be reached:", "Spiel gefunden unter {0}:{1}, aber der Host ist nicht erreichbar:", "Match trouvé à {0}:{1}, mais impossible de joindre l'hôte :"],
  ["{t0}è l'ultimo indirizzo usato e potrebbe essere cambiato. Controlla quello mostrato ora nella lobby dell'host{1}", "{t0} it's the last address used and it may have changed. Check the one shown now in the host's lobby{1}", "{t0} Das ist die zuletzt verwendete Adresse, sie könnte sich geändert haben. Prüfe die Adresse, die jetzt in der Lobby des Hosts angezeigt wird{1}", "{t0} c'est la dernière adresse utilisée et elle a peut-être changé. Vérifie celle affichée maintenant dans le salon de l'hôte{1}"],
  ["{t0}il computer c'è ma rifiuta la connessione, quindi non sta più ospitando oppure la porta è diversa{1}", "{t0} the computer is there but refuses the connection, so it's no longer hosting or the port is different{1}", "{t0} Der Computer ist da, lehnt die Verbindung aber ab: Er hostet nicht mehr oder der Port ist ein anderer{1}", "{t0} l'ordinateur est là mais refuse la connexion : il n'héberge plus ou le port est différent{1}"],
  ["{t0}non risponde. Di solito è il firewall del computer dell'host: deve consentire Campo Aperto (su Windows anche per le reti pubbliche){1}", "{t0} not responding. It's usually the firewall on the host's computer: it must allow Campo Aperto (on Windows, for public networks too){1}", "{t0} antwortet nicht. Meistens ist es die Firewall auf dem Computer des Hosts: Sie muss Campo Aperto erlauben (unter Windows auch für öffentliche Netzwerke){1}", "{t0} ne répond pas. C'est souvent le pare-feu de l'ordinateur de l'hôte : il doit autoriser Campo Aperto (sous Windows, aussi pour les réseaux publics){1}"],
  ["{t0}la rete non lo raggiunge. Siete sulla stessa rete? Alcuni Wi-Fi (ospiti, pubblici) isolano i dispositivi tra loro{1}", "{t0} the network can't reach it. Are you on the same network? Some Wi-Fi networks (guest, public) isolate devices from each other{1}", "{t0} Das Netzwerk erreicht ihn nicht. Seid ihr im selben Netzwerk? Manche WLANs (Gäste, öffentlich) trennen die Geräte voneinander{1}", "{t0} le réseau ne l'atteint pas. Êtes-vous sur le même réseau ? Certains Wi-Fi (invités, publics) isolent les appareils entre eux{1}"],
  ["{t0}la porta risponde ma il gioco no. Controlla che l'host usi la stessa versione del gioco ({1})", "{t0} the port responds but the game doesn't. Check the host is using the same game version ({1})", "{t0} Der Port antwortet, das Spiel aber nicht. Prüfe, ob der Host dieselbe Spielversion verwendet ({1})", "{t0} le port répond mais pas le jeu. Vérifie que l'hôte utilise la même version du jeu ({1})"],
  ["{t0}la connessione non riesce{1}", "{t0} the connection fails{1}", "{t0} Die Verbindung schlägt fehl{1}", "{t0} la connexion échoue{1}"],
  ["{t0}il collegamento non riesce. Riprova tra poco", "{t0} the connection fails. Try again shortly", "{t0} Die Verbindung schlägt fehl. Versuche es gleich noch einmal", "{t0} la connexion échoue. Réessaie dans un instant"],
  ["Host trovato: {0} in {1} ms", "Host found: {0} in {1} ms", "Host gefunden: {0} in {1} ms", "Hôte trouvé : {0} en {1} ms"],
  ["Host, {0} giocatore{1}, server {2} ms", "Host, {0} player{1}, server {2} ms", "Host, {0} Spieler{1}, Server {2} ms", "Hôte, {0} joueur{1}, serveur {2} ms"],
  ["Host, {0} giocatori{1}, server {2} ms", "Host, {0} players{1}, server {2} ms", "Host, {0} Spieler{1}, Server {2} ms", "Hôte, {0} joueurs{1}, serveur {2} ms"],
  ["Il codice è {0}", "The code is {0}", "Der Code ist {0}", "Le code est {0}"],
  ["Il computer dell'host va a {0} fotogrammi al secondo: rallenta la partita per tutti. Sull'host abbassa la grafica (Impostazioni → Grafica: qualità bassa, risoluzione dinamica) oppure fate ospitare a chi ha il computer più veloce.", "The host's computer runs at {0} frames per second: it slows down the match for everyone. On the host, lower the graphics (Settings → Graphics: low quality, dynamic resolution) or let whoever has the fastest computer host.", "Der Computer des Hosts läuft mit {0} Bildern pro Sekunde: Das verlangsamt das Spiel für alle. Senke beim Host die Grafik (Einstellungen → Grafik: niedrige Qualität, dynamische Auflösung) oder lasst den mit dem schnellsten Computer hosten.", "L'ordinateur de l'hôte tourne à {0} images par seconde : cela ralentit le match pour tous. Sur l'hôte, baisse les graphismes (Paramètres → Graphismes : qualité basse, résolution dynamique) ou faites héberger celui qui a l'ordinateur le plus rapide."],
  ["Il gioco non è partito: {0}. Serve un browser con WebGL attivo.", "The game didn't start: {0}. A browser with WebGL enabled is needed.", "Das Spiel ist nicht gestartet: {0}. Es braucht einen Browser mit aktiviertem WebGL.", "Le jeu n'a pas démarré : {0}. Il faut un navigateur avec WebGL activé."],
  ["Il server della partita su questo computer non risponde ({0}): riprova", "The match server on this computer isn't responding ({0}): try again", "Der Spielserver auf diesem Computer antwortet nicht ({0}): Versuche es erneut", "Le serveur du match sur cet ordinateur ne répond pas ({0}) : réessaie"],
  ["Indirizzo copiato: {0}", "Address copied: {0}", "Adresse kopiert: {0}", "Adresse copiée : {0}"],
  ["L'host {0}:{1} è raggiungibile, ma non ha nessuna partita con questo codice: controlla il codice e che l'host sia ancora nella lobby", "The host {0}:{1} is reachable but has no match with this code: check the code and that the host is still in the lobby", "Der Host {0}:{1} ist erreichbar, hat aber kein Spiel mit diesem Code: Prüfe den Code und ob der Host noch in der Lobby ist", "L'hôte {0}:{1} est joignable, mais n'a aucun match avec ce code : vérifie le code et que l'hôte est toujours dans le salon"],
  ["L'indirizzo è {0}", "The address is {0}", "Die Adresse ist {0}", "L'adresse est {0}"],
  ["La ricerca automatica non è attiva (porta UDP 8788 occupata): gli amici devono scrivere l'indirizzo {0}:{1}", "Automatic search isn't active (UDP port 8788 in use): friends must type the address {0}:{1}", "Die automatische Suche ist nicht aktiv (UDP-Port 8788 belegt): Die Freunde müssen die Adresse {0}:{1} eingeben", "La recherche automatique n'est pas active (port UDP 8788 occupé) : les amis doivent écrire l'adresse {0}:{1}"],
  ["Lo schermo è più piccolo: finestra {0}×{1}", "The screen is smaller: window {0}×{1}", "Der Bildschirm ist kleiner: Fenster {0}×{1}", "L'écran est plus petit : fenêtre {0}×{1}"],
  ["Nessuna partita con questo codice sul server {0}: controlla il codice, o la partita è già stata chiusa", "No match with this code on the server {0}: check the code, or the match has already been closed", "Kein Spiel mit diesem Code auf dem Server {0}: Prüfe den Code, oder das Spiel wurde schon geschlossen", "Aucun match avec ce code sur le serveur {0} : vérifie le code, ou le match a déjà été fermé"],
  ["Nessuna risposta alla ricerca ({0}): provo l'indirizzo {1}", "No reply to the search ({0}): trying address {1}", "Keine Antwort auf die Suche ({0}): versuche die Adresse {1}", "Aucune réponse à la recherche ({0}) : j'essaie l'adresse {1}"],
  ["Non sei collegato a nessuna rete: collegati al Wi-Fi o al cavo della stessa rete dell'host{0}", "You aren't connected to any network: connect to the Wi-Fi or cable of the host's network{0}", "Du bist mit keinem Netzwerk verbunden: Verbinde dich per WLAN oder Kabel mit dem Netzwerk des Hosts{0}", "Tu n'es connecté à aucun réseau : connecte-toi au Wi-Fi ou au câble du même réseau que l'hôte{0}"],
  ["Ognuno sceglie la squadra con «Gioca qui»: vanno bene anche squadre diverse, come 2 contro 1 (fino a {0} per squadra, gli altri calciatori li muove l'IA).", "Everyone picks a team with “Play here”: uneven teams are fine too, like 2 against 1 (up to {0} per team, the AI controls the other players).", "Jeder wählt sein Team mit «Hier spielen»: Auch ungleiche Teams sind möglich, wie 2 gegen 1 (bis zu {0} pro Team, die übrigen Spieler steuert die KI).", "Chacun choisit son équipe avec « Jouer ici » : des équipes inégales vont aussi, comme 2 contre 1 (jusqu'à {0} par équipe, l'IA contrôle les autres joueurs)."],
  ["Online, {0} ms (server {1} ms{2})", "Online, {0} ms (server {1} ms{2})", "Online, {0} ms (Server {1} ms{2})", "En ligne, {0} ms (serveur {1} ms{2})"],
  ["Partita creata, codice {0}", "Match created, code {0}", "Spiel erstellt, Code {0}", "Match créé, code {0}"],
  ["Partita lasciata a metà: il resto è stato simulato ({0} {1}-{2} {3})", "Match left unfinished: the rest was simulated ({0} {1}-{2} {3})", "Spiel abgebrochen: Der Rest wurde simuliert ({0} {1}-{2} {3})", "Match abandonné en cours : la suite a été simulée ({0} {1}-{2} {3})"],
  ["Partita non trovata nella rete locale: nessun host ha risposto alla ricerca. Controlla che siate sulla stessa rete (non la rete ospiti, nessuna VPN attiva), che l'host sia ancora nella lobby e che sul suo computer il firewall consenta Campo Aperto (su Windows anche per le reti pubbliche). Se ancora non va, scrivi l'indirizzo mostrato nella lobby dell'host in «La partita non viene trovata?»{0}", "Match not found on the local network: no host replied to the search. Check that you're on the same network (not the guest network, no VPN active), that the host is still in the lobby and that the firewall on their computer allows Campo Aperto (on Windows, for public networks too). If it still doesn't work, type the address shown in the host's lobby under “Match not found?”{0}", "Spiel im lokalen Netzwerk nicht gefunden: Kein Host hat auf die Suche geantwortet. Prüfe, ob ihr im selben Netzwerk seid (nicht im Gästenetz, kein VPN aktiv), ob der Host noch in der Lobby ist und ob die Firewall auf seinem Computer Campo Aperto erlaubt (unter Windows auch für öffentliche Netzwerke). Wenn es immer noch nicht geht, gib die in der Lobby des Hosts angezeigte Adresse bei «Spiel wird nicht gefunden?» ein{0}", "Match introuvable sur le réseau local : aucun hôte n'a répondu à la recherche. Vérifie que vous êtes sur le même réseau (pas le réseau invités, aucun VPN actif), que l'hôte est toujours dans le salon et que le pare-feu de son ordinateur autorise Campo Aperto (sous Windows, aussi pour les réseaux publics). Si ça ne marche toujours pas, écris l'adresse affichée dans le salon de l'hôte sous « Le match est introuvable ? »{0}"],
  ["Partita pronta su {0}:{1}", "Match ready on {0}:{1}", "Spiel bereit auf {0}:{1}", "Match prêt sur {0}:{1}"],
  ["Rinvio: {t0} corto, {t1} lungo", "Goal kick: {t0} short, {t1} long", "Abstoss: {t0} kurz, {t1} lang", "Six mètres : {t0} court, {t1} long"],
  ["Ritardo di rete verso il server ({0}): di solito sono reti con filtri o proxy (scuola, ufficio) o il Wi-Fi. Se siete nella stessa rete, con l'app desktop usate «Crea in rete locale»: niente internet, ritardo di pochi millisecondi.", "Network delay to the server ({0}): usually it's networks with filters or proxies (school, office) or the Wi-Fi. If you're on the same network, use “Create on local network” in the desktop app: no internet, only a few milliseconds of delay.", "Netzwerkverzögerung zum Server ({0}): Meistens sind es Netzwerke mit Filtern oder Proxys (Schule, Büro) oder das WLAN. Wenn ihr im selben Netzwerk seid, nutzt in der Desktop-App «Im lokalen Netzwerk erstellen»: kein Internet, nur wenige Millisekunden Verzögerung.", "Délai réseau vers le serveur ({0}) : ce sont souvent des réseaux avec filtres ou proxy (école, bureau) ou le Wi-Fi. Si vous êtes sur le même réseau, utilisez « Créer en réseau local » dans l'application de bureau : pas d'internet, quelques millisecondes de délai."],
  ["Server avviato: TCP {0} su tutte le schede di rete, ricerca UDP NON attiva (porta occupata), indirizzi {1}", "Server started: TCP {0} on all network adapters, UDP search NOT active (port in use), addresses {1}", "Server gestartet: TCP {0} auf allen Netzwerkkarten, UDP-Suche NICHT aktiv (Port belegt), Adressen {1}", "Serveur lancé : TCP {0} sur toutes les cartes réseau, recherche UDP NON active (port occupé), adresses {1}"],
  ["Server avviato: TCP {0} su tutte le schede di rete, ricerca UDP attiva, indirizzi {1}", "Server started: TCP {0} on all network adapters, UDP search active, addresses {1}", "Server gestartet: TCP {0} auf allen Netzwerkkarten, UDP-Suche aktiv, Adressen {1}", "Serveur lancé : TCP {0} sur toutes les cartes réseau, recherche UDP active, adresses {1}"],
  ["Server multiplayer non disponibile ({0}): è spento, l'indirizzo è sbagliato oppure la rete lo blocca. Controlla l'indirizzo in Impostazioni → Online", "Multiplayer server not available ({0}): it's off, the address is wrong or the network is blocking it. Check the address in Settings → Online", "Mehrspieler-Server nicht verfügbar ({0}): Er ist aus, die Adresse ist falsch oder das Netzwerk blockiert ihn. Prüfe die Adresse unter Einstellungen → Online", "Serveur multijoueur indisponible ({0}) : il est éteint, l'adresse est fausse ou le réseau le bloque. Vérifie l'adresse dans Paramètres → En ligne"],
  ["Spazio / Invio / {t0}", "Space / Enter / {t0}", "Leertaste / Eingabe / {t0}", "Espace / Entrée / {t0}"],
  ["Squadre, durata ({0} minuti a tempo) e IA {t1} fissate dalla competizione. A fine partita il risultato va al server da solo.", "Teams, length ({0} minutes per half) and AI {t1} are set by the competition. At full time the result goes to the server by itself.", "Teams, Dauer ({0} Minuten pro Halbzeit) und KI {t1} legt der Wettbewerb fest. Nach dem Spiel geht das Ergebnis automatisch an den Server.", "Équipes, durée ({0} minutes par mi-temps) et IA {t1} fixées par la compétition. À la fin du match, le résultat part tout seul au serveur."],
  ["Stanza aperta, ma il server non l'ha registrata ({0}): dai al tuo amico il codice {1}", "Room open, but the server didn't register it ({0}): give your friend the code {1}", "Raum offen, aber der Server hat ihn nicht registriert ({0}): Gib deinem Freund den Code {1}", "Salon ouvert, mais le serveur ne l'a pas enregistré ({0}) : donne le code {1} à ton ami"],
  ["TCP {0}, UDP {1}, {2} collegamenti", "TCP {0}, UDP {1}, {2} connections", "TCP {0}, UDP {1}, {2} Verbindungen", "TCP {0}, UDP {1}, {2} connexions"],
  ["Telecamera {t0}", "Camera {t0}", "Kamera {t0}", "Caméra {t0}"],
  ["Telecamera: {t0}", "Camera: {t0}", "Kamera: {t0}", "Caméra : {t0}"],
  ["Tieni premuto {t0} per caricare, rilascia per tirare. Su o giù scelgono il lato", "Hold {t0} to charge, release to shoot. Up or down pick the side", "Halte {t0} zum Aufladen, loslassen zum Schiessen. Hoch oder runter wählen die Seite", "Maintiens {t0} pour charger, relâche pour tirer. Haut ou bas choisissent le côté"],
  ["Versione del gioco diversa da quella dell'host: aggiornate tutti alla stessa versione (la tua è {0})", "Game version different from the host's: everyone update to the same version (yours is {0})", "Spielversion unterscheidet sich von der des Hosts: Aktualisiert alle auf dieselbe Version (deine ist {0})", "Version du jeu différente de celle de l'hôte : mettez-vous tous à la même version (la tienne est {0})"],
  ["Vuoto: si usa il server predefinito {0}", "Empty: the default server {0} is used", "Leer: Es wird der Standardserver {0} verwendet", "Vide : le serveur par défaut {0} est utilisé"],
  ["WebSocket su TCP{t0}", "WebSocket over TCP{t0}", "WebSocket über TCP{t0}", "WebSocket sur TCP{t0}"],
  [", ricerca UDP {0}", ", UDP search {0}", ", UDP-Suche {0}", ", recherche UDP {0}"],
  ["(per gli altri {0})", "(for the others {0})", "(für die anderen {0})", "(pour les autres {0})"],
  ["{0} (per gli altri {1})", "{0} (for the others {1})", "{0} (für die anderen {1})", "{0} (pour les autres {1})"],
  ["host {0} ms, server {1} ms", "host {0} ms, server {1} ms", "Host {0} ms, Server {1} ms", "hôte {0} ms, serveur {1} ms"],
  ["server {0} ms", "server {0} ms", "Server {0} ms", "serveur {0} ms"],
  ["server {0} ms · {1} fps", "server {0} ms · {1} fps", "Server {0} ms · {1} fps", "serveur {0} ms · {1} fps"],
  ["{0} (predefinito)", "{0} (default)", "{0} (Standard)", "{0} (par défaut)"],
  ["{t0} / Clic dx", "{t0} / Right click", "{t0} / Rechtsklick", "{t0} / Clic droit"],
  ["{t0} / Clic sx", "{t0} / Left click", "{t0} / Linksklick", "{t0} / Clic gauche"],
  ["{t0} cross in area, {t1} corto. Con una direzione scegli il compagno", "{t0} cross into the box, {t1} short. With a direction you pick the teammate", "{t0} Flanke in den Strafraum, {t1} kurz. Mit einer Richtung wählst du den Mitspieler", "{t0} centre dans la surface, {t1} court. Avec une direction, tu choisis le coéquipier"],
  ["{0} fps, {1}x", "{0} fps, {1}x", "{0} fps, {1}x", "{0} fps, {1}x"],
  ["{0} ms (server {1})", "{0} ms (server {1})", "{0} ms (Server {1})", "{0} ms (serveur {1})"],
  ["{t0} passaggio corto, {t1} lancio lungo", "{t0} short pass, {t1} long ball", "{t0} kurzer Pass, {t1} langer Ball", "{t0} passe courte, {t1} passe longue"],
  ["{t0} passaggio, {t1} lancio, {t2} tiro (tieni premuto)", "{t0} pass, {t1} long ball, {t2} shoot (hold)", "{t0} Pass, {t1} langer Ball, {t2} Schuss (halten)", "{t0} passe, {t1} passe longue, {t2} tir (maintenir)"],
  ["{t0} per saltare", "{t0} to skip", "{t0} zum Überspringen", "{t0} pour passer"],
  ["{0} ricevute, {1} con questo codice{2}", "{0} received, {1} with this code{2}", "{0} empfangen, {1} mit diesem Code{2}", "{0} reçues, {1} avec ce code{2}"],
  ["{t0} riprende, {t1} mostra i comandi{2}", "{t0} resumes, {t1} shows the controls{2}", "{t0} setzt fort, {t1} zeigt die Steuerung{2}", "{t0} reprend, {t1} affiche les commandes{2}"],
  ["{t0} tolto da “{t1}”", "{t0} removed from “{t1}”", "{t0} entfernt von «{t1}»", "{t0} retiré de « {t1} »"],
  ["{0} × {1} pixel (rapporto {2}, schermo {3}x{4})", "{0} × {1} pixels (ratio {2}, screen {3}x{4})", "{0} × {1} Pixel (Verhältnis {2}, Bildschirm {3}x{4})", "{0} × {1} pixels (rapport {2}, écran {3}x{4})"],
  ["{0}' {1} (autogol)", "{0}' {1} (own goal)", "{0}' {1} (Eigentor)", "{0}' {1} (c.s.c.)"],
  ["{0}' {1} (giallo)", "{0}' {1} (yellow)", "{0}' {1} (Gelb)", "{0}' {1} (jaune)"],
  ["{0}' {1} (rosso)", "{0}' {1} (red)", "{0}' {1} (Rot)", "{0}' {1} (rouge)"],
  ["{0}' {1} ({2}, autogol)", "{0}' {1} ({2}, own goal)", "{0}' {1} ({2}, Eigentor)", "{0}' {1} ({2}, c.s.c.)"],
  ["{t0}, pulsante del controller", "{t0}, controller button", "{t0}, Controllertaste", "{t0}, bouton de la manette"],
  ["{t0}, tasto alternativo", "{t0}, alternative key", "{t0}, alternative Taste", "{t0}, touche alternative"],
  ["{t0}, tasto principale", "{t0}, main key", "{t0}, Haupttaste", "{t0}, touche principale"],
  ["{0}: {1} gioca con {2}, {3} con {4}. Avvia quando ci siete tutti e due.", "{0}: {1} plays as {2}, {3} as {4}. Start when you're both here.", "{0}: {1} spielt mit {2}, {3} mit {4}. Starte, wenn ihr beide da seid.", "{0} : {1} joue avec {2}, {3} avec {4}. Lance quand vous êtes là tous les deux."],
  ["{0}: {1} gioca con {2}, {3} con {4}. La partita la avvia chi ha aperto la stanza.", "{0}: {1} plays as {2}, {3} as {4}. Whoever opened the room starts the match.", "{0}: {1} spielt mit {2}, {3} mit {4}. Das Spiel startet, wer den Raum eröffnet hat.", "{0} : {1} joue avec {2}, {3} avec {4}. Celui qui a ouvert le salon lance le match."],
  ["🏆 {0}: vince {1}!", "🏆 {0}: {1} win!", "🏆 {0}: {1} gewinnt!", "🏆 {0} : {1} gagne !"],
  ["risultato registrato", "result recorded", "Ergebnis gespeichert", "résultat enregistré"],
  ["la tua squadra è eliminata", "your team is knocked out", "dein Team ist ausgeschieden", "ton équipe est éliminée"],
  ["prossimo turno: {0}", "next round: {0}", "nächste Runde: {0}", "tour suivant : {0}"],
  ["{0}º posto", "Place {0}", "{0}. Platz", "Place {0}"],
  ["d.t.s.", "a.e.t.", "n.V.", "a.p."],
  ["rigori {0}-{1}", "penalties {0}-{1}", "Elfmeter {0}-{1}", "tirs au but {0}-{1}"],
  ["La partita la avvia chi ha aperto la stanza.", "Whoever opened the room starts the match.", "Das Spiel startet, wer den Raum eröffnet hat.", "Celui qui a ouvert le salon lance le match."],
  ["Avvia quando ci siete tutti e due.", "Start when you're both here.", "Starte, wenn ihr beide da seid.", "Lance quand vous êtes là tous les deux."],
  ["Tastiera", "Keyboard", "Tastatur", "Clavier"],
  ["{t0} / {t1}", "{t0} / {t1}", "{t0} / {t1}", "{t0} / {t1}"],
]);
