// Economia (src/15_account.js, src/16_economy_ui.js, src/17_fixture_watch.js): account, partite del server, scommesse, negozio, profilo
// Ogni riga: [italiano, inglese, tedesco, francese]
addTranslations([
  ["% vinte", "% won", "% gewonnen", "% gagnés"],
  ["Accessori", "Accessories", "Accessoires", "Accessoires"],
  ["Accesso…", "Logging in…", "Anmeldung…", "Connexion…"],
  ["Acquisto nel negozio", "Shop purchase", "Kauf im Shop", "Achat en boutique"],
  ["Altro", "Other", "Weitere", "Autres"],
  ["Ancora nessuna giocata.", "No bets yet.", "Noch keine Wetten.", "Aucun pari pour l'instant."],
  ["Ancora nessuna scommessa conclusa.", "No settled bets yet.", "Noch keine abgeschlossenen Wetten.", "Aucun pari terminé pour l'instant."],
  ["Ancora nessuno in classifica per questo periodo.", "Nobody on the leaderboard for this period yet.", "Für diesen Zeitraum ist noch niemand in der Rangliste.", "Personne au classement pour cette période."],
  ["Calzettoni", "Socks", "Stutzen", "Chaussettes"],
  ["Capelli", "Hair", "Haare", "Cheveux"],
  ["Carico le scommesse…", "Loading bets…", "Wetten werden geladen…", "Chargement des paris…"],
  ["Carico…", "Loading…", "Lade…", "Chargement…"],
  ["Cartellini", "Cards", "Karten", "Cartons"],
  ["Chiuse", "Settled", "Abgeschlossen", "Terminés"],
  ["Classifica per bravura, non per saldo. Solo profili pubblici; ROI e % vinte con almeno 5 scommesse decise. La serie conta le scommesse vinte di fila.", "Ranked by skill, not by balance. Public profiles only; ROI and % won with at least 5 settled bets. The streak counts bets won in a row.", "Rangliste nach Können, nicht nach Guthaben. Nur öffentliche Profile; ROI und % gewonnen ab 5 entschiedenen Wetten. Die Serie zählt die nacheinander gewonnenen Wetten.", "Classement selon le talent, pas le solde. Profils publics uniquement ; ROI et % gagnés avec au moins 5 paris décidés. La série compte les paris gagnés d'affilée."],
  ["Competizioni riprese dall'account", "Competitions restored from the account", "Wettbewerbe aus dem Konto übernommen", "Compétitions récupérées depuis le compte"],
  ["Comune", "Common", "Gewöhnlich", "Commun"],
  ["Raro", "Rare", "Selten", "Rare"],
  ["Epico", "Epic", "Episch", "Épique"],
  ["Leggendario", "Legendary", "Legendär", "Légendaire"],
  ["Condividi", "Share", "Teilen", "Partager"],
  ["Copia scommessa", "Copy bet", "Wette kopieren", "Copier le pari"],
  ["Corner", "Corners", "Ecken", "Corners"],
  ["Creo l'account…", "Creating the account…", "Konto wird erstellt…", "Création du compte…"],
  ["Finita", "Finished", "Beendet", "Terminé"],
  ["Finita, liquidazione in corso", "Finished, settling bets", "Beendet, Wetten werden abgerechnet", "Terminé, règlement en cours"],
  ["Finita, scommesse liquidate", "Finished, bets settled", "Beendet, Wetten abgerechnet", "Terminé, paris réglés"],
  ["Finite", "Finished", "Beendet", "Terminés"],
  ["Forma", "Form", "Form", "Forme"],
  ["Giocatori", "Players", "Spieler", "Joueurs"],
  ["Giornata", "Matchday", "Spieltag", "Journée"],
  ["Giornata {#0}", "Matchday {#0}", "Spieltag {#0}", "Journée {#0}"],
  ["Già compresa nelle altre selezioni: non cambia la quota e non conta per il bonus", "Already covered by the other selections: it doesn't change the odds and doesn't count for the bonus", "Bereits in den anderen Tipps enthalten: ändert die Quote nicht und zählt nicht für den Bonus", "Déjà comprise dans les autres sélections : elle ne change pas la cote et ne compte pas pour le bonus"],
  ["Guanti", "Gloves", "Handschuhe", "Gants"],
  ["Guarda dall'inizio", "Watch from the start", "Von Anfang an ansehen", "Regarder depuis le début"],
  ["Il campionato del server comincia con le prossime partite.", "The server league starts with the next matches.", "Die Server-Liga beginnt mit den nächsten Spielen.", "La ligue du serveur commence avec les prochains matchs."],
  ["Il codice ha la forma BET-XXXXX", "The code looks like BET-XXXXX", "Der Code hat die Form BET-XXXXX", "Le code a la forme BET-XXXXX"],
  ["Il server dell'economia non è impostato. Scrivi il suo indirizzo (https://…) in Impostazioni, Online.", "The economy server isn't set. Enter its address (https://…) in Settings, Online.", "Der Wirtschaftsserver ist nicht eingestellt. Gib seine Adresse (https://…) unter Einstellungen, Online ein.", "Le serveur de l'économie n'est pas configuré. Écris son adresse (https://…) dans Paramètres, En ligne."],
  ["Il server dell'economia non è impostato: chiedi l'indirizzo a chi gestisce il gioco e scrivilo in Impostazioni, Online.", "The economy server isn't set: ask whoever runs the game for the address and enter it in Settings, Online.", "Der Wirtschaftsserver ist nicht eingestellt: Frage den Betreiber des Spiels nach der Adresse und gib sie unter Einstellungen, Online ein.", "Le serveur de l'économie n'est pas configuré : demande l'adresse à celui qui gère le jeu et écris-la dans Paramètres, En ligne."],
  ["Il server non risponde", "The server isn't responding", "Der Server antwortet nicht", "Le serveur ne répond pas"],
  ["Indossa", "Wear", "Anziehen", "Porter"],
  ["Indossato", "Worn", "Angezogen", "Porté"],
  ["Inventario vuoto: gli oggetti si comprano nel negozio.", "Inventory empty: items are bought in the shop.", "Inventar leer: Gegenstände kauft man im Shop.", "Inventaire vide : les objets s'achètent dans la boutique."],
  ["Invio…", "Sending…", "Senden…", "Envoi…"],
  ["La password deve avere almeno 8 caratteri", "The password must be at least 8 characters", "Das Passwort muss mindestens 8 Zeichen haben", "Le mot de passe doit contenir au moins 8 caractères"],
  ["Le due password non coincidono", "The two passwords don't match", "Die beiden Passwörter stimmen nicht überein", "Les deux mots de passe ne correspondent pas"],
  ["Le tue scommesse non sono più visibili agli altri", "Your bets are no longer visible to others", "Deine Wetten sind für andere nicht mehr sichtbar", "Tes paris ne sont plus visibles par les autres"],
  ["Le tue scommesse sono pubbliche", "Your bets are public", "Deine Wetten sind öffentlich", "Tes paris sont publics"],
  ["Maglia", "Shirt", "Trikot", "Maillot"],
  ["Pantaloncini", "Shorts", "Hose", "Short"],
  ["Scarpe", "Boots", "Schuhe", "Chaussures"],
  ["Mercato chiuso: non si può più giocare", "Market closed: no more bets", "Markt geschlossen: keine Wetten mehr möglich", "Marché fermé : on ne peut plus parier"],
  ["Mese", "Month", "Monat", "Mois"],
  ["Settimana", "Week", "Woche", "Semaine"],
  ["Tutti", "All", "Alle", "Tous"],
  ["Monete di benvenuto", "Welcome coins", "Willkommensmünzen", "Pièces de bienvenue"],
  ["monete di benvenuto", "welcome coins", "Willkommensmünzen", "pièces de bienvenue"],
  ["Monete puntate", "Coins staked", "Eingesetzte Münzen", "Pièces misées"],
  ["Monete vinte", "Coins won", "Gewonnene Münzen", "Pièces gagnées"],
  ["Multipla", "Accumulator", "Kombiwette", "Combiné"],
  ["Singola", "Single", "Einzelwette", "Simple"],
  ["Nel tuo inventario", "In your inventory", "In deinem Inventar", "Dans ton inventaire"],
  ["Nessun evento per ora.", "No events yet.", "Noch keine Ereignisse.", "Aucun événement pour l'instant."],
  ["Nessun mercato in questa scheda.", "No markets in this tab.", "Keine Märkte in diesem Reiter.", "Aucun marché dans cet onglet."],
  ["Nessun movimento.", "No transactions.", "Keine Bewegungen.", "Aucun mouvement."],
  ["Nessuna partita in programma: il server ne crea di nuove ogni pochi minuti.", "No matches scheduled: the server creates new ones every few minutes.", "Keine Spiele geplant: Der Server erstellt alle paar Minuten neue.", "Aucun match au programme : le serveur en crée de nouveaux toutes les quelques minutes."],
  ["Nessuna scommessa in corso. Apri Partite per giocare.", "No bets in progress. Open Matches to bet.", "Keine laufenden Wetten. Öffne Spiele, um zu wetten.", "Aucun pari en cours. Ouvre Matchs pour parier."],
  ["Nessuna scommessa pubblica su questa partita. Sii il primo!", "No public bets on this match. Be the first!", "Keine öffentlichen Wetten auf dieses Spiel. Sei der Erste!", "Aucun pari public sur ce match. Sois le premier !"],
  ["Nessuna scommessa pubblica.", "No public bets.", "Keine öffentlichen Wetten.", "Aucun pari public."],
  ["Nome utente: da 3 a 16 caratteri tra lettere, numeri e _", "Username: 3 to 16 characters, letters, numbers and _", "Benutzername: 3 bis 16 Zeichen aus Buchstaben, Zahlen und _", "Nom d'utilisateur : de 3 à 16 caractères parmi lettres, chiffres et _"],
  ["Obiettivo", "Goal", "Ziel", "Objectif"],
  ["Partita calcolata con un altro motore: aggiorna il gioco per guardarla in 3D", "Match calculated with a different engine: update the game to watch it in 3D", "Spiel mit einer anderen Engine berechnet: Aktualisiere das Spiel, um es in 3D zu sehen", "Match calculé avec un autre moteur : mets à jour le jeu pour le regarder en 3D"],
  ["Partite e scommesse", "Matches and bets", "Spiele und Wetten", "Matchs et paris"],
  ["Perse", "Lost", "Verloren", "Perdus"],
  ["Vinte", "Won", "Gewonnen", "Gagnés"],
  ["Pos", "Pos", "Pos.", "Pos"],
  ["Premio di stagione", "Season reward", "Saisonprämie", "Prime de saison"],
  ["Privata", "Private", "Privat", "Privé"],
  ["Profitto", "Profit", "Gewinn", "Profit"],
  ["Prossime", "Upcoming", "Nächste", "À venir"],
  ["Quota cambiata: controlla le nuove quote e conferma di nuovo", "Odds changed: check the new odds and confirm again", "Quote geändert: Prüfe die neuen Quoten und bestätige erneut", "Cote modifiée : vérifie les nouvelles cotes et confirme à nouveau"],
  ["Record", "Record", "Rekord", "Record"],
  ["Rendi privata", "Make private", "Privat machen", "Rendre privé"],
  ["Rendi pubblica", "Make public", "Öffentlich machen", "Rendre public"],
  ["Rigore", "Penalty", "Elfmeter", "Penalty"],
  ["Saldo", "Balance", "Guthaben", "Solde"],
  ["Scommessa", "Bet", "Wette", "Pari"],
  ["Scommessa annullata (rimborso)", "Bet cancelled (refund)", "Wette storniert (Rückerstattung)", "Pari annulé (remboursement)"],
  ["Scommessa copiata: niente è stato giocato. Controlla e conferma.", "Bet copied: nothing has been placed. Check and confirm.", "Wette kopiert: Es wurde noch nichts gesetzt. Prüfen und bestätigen.", "Pari copié : rien n'a été joué. Vérifie et confirme."],
  ["Scommessa giocata", "Bet placed", "Wette platziert", "Pari placé"],
  ["Scommessa non trovata (o non condivisa)", "Bet not found (or not shared)", "Wette nicht gefunden (oder nicht geteilt)", "Pari introuvable (ou non partagé)"],
  ["Scommessa privata", "Private bet", "Private Wette", "Pari privé"],
  ["Scommessa pubblica", "Public bet", "Öffentliche Wette", "Pari public"],
  ["Scommessa vinta", "Bet won", "Wette gewonnen", "Pari gagné"],
  ["Scommesse aperte", "Open bets", "Offene Wetten", "Paris ouverts"],
  ["Scommesse chiuse.", "Betting closed.", "Wetten geschlossen.", "Paris fermés."],
  ["Scommesse chiuse: la partita sta per iniziare.", "Betting closed: the match is about to start.", "Wetten geschlossen: Das Spiel beginnt gleich.", "Paris fermés : le match va commencer."],
  ["Scommesse giocate", "Bets placed", "Platzierte Wetten", "Paris joués"],
  ["Scommesse vinte", "Bets won", "Gewonnene Wetten", "Paris gagnés"],
  ["Scrivi nome utente e password", "Enter username and password", "Benutzername und Passwort eingeben", "Écris le nom d'utilisateur et le mot de passe"],
  ["Scrivi una puntata di almeno 1 moneta", "Enter a stake of at least 1 coin", "Gib einen Einsatz von mindestens 1 Münze ein", "Écris une mise d'au moins 1 pièce"],
  ["Sei uscito dall'account", "You've logged out", "Du hast dich abgemeldet", "Tu t'es déconnecté"],
  ["Selezione non disponibile", "Selection not available", "Tipp nicht verfügbar", "Sélection non disponible"],
  ["Serie", "Streak", "Serie", "Série"],
  ["Serie attuale", "Current streak", "Aktuelle Serie", "Série actuelle"],
  ["Serie record", "Best streak", "Rekordserie", "Série record"],
  ["Server dell'economia non impostato (Impostazioni, Online)", "Economy server not set (Settings, Online)", "Wirtschaftsserver nicht eingestellt (Einstellungen, Online)", "Serveur de l'économie non configuré (Paramètres, En ligne)"],
  ["Server non raggiungibile: controlla la connessione", "Server not reachable: check your connection", "Server nicht erreichbar: Prüfe die Verbindung", "Serveur injoignable : vérifie la connexion"],
  ["Si può guardare dal calcio d'inizio", "Can be watched from kick-off", "Ab dem Anstoss zu sehen", "Visible dès le coup d'envoi"],
  ["Sicuro?", "Sure?", "Sicher?", "Sûr ?"],
  ["Squadra", "Team", "Team", "Équipe"],
  ["Stagione", "Season", "Saison", "Saison"],
  ["Tiro in porta", "Shot on target", "Schuss aufs Tor", "Tir cadré"],
  ["Togli", "Remove", "Entfernen", "Retirer"],
  ["Tua", "Yours", "Deine", "À toi"],
  ["in corso", "live", "läuft", "en cours"],
  ["↩ Annullata", "↩ Cancelled", "↩ Storniert", "↩ Annulé"],
  ["❌ Persa", "❌ Lost", "❌ Verloren", "❌ Perdu"],
  ["🟥 Espulsione", "🟥 Sending-off", "🟥 Platzverweis", "🟥 Expulsion"],
  ["🟨 Ammonizione", "🟨 Booking", "🟨 Verwarnung", "🟨 Avertissement"],
  ["🟨🟨 Seconda ammonizione", "🟨🟨 Second booking", "🟨🟨 Zweite Verwarnung", "🟨🟨 Deuxième avertissement"],
  ["Account creato il {0}. Nome pubblico: {1}. Gli altri vedono solo il nome, mai saldo o dati dell'account.", "Account created on {0}. Public name: {1}. Others only see the name, never your balance or account data.", "Konto erstellt am {0}. Öffentlicher Name: {1}. Andere sehen nur den Namen, nie Guthaben oder Kontodaten.", "Compte créé le {0}. Nom public : {1}. Les autres ne voient que le nom, jamais le solde ni les données du compte."],
  ["Account creato: {0} monete di benvenuto", "Account created: {0} welcome coins", "Konto erstellt: {0} Willkommensmünzen", "Compte créé : {0} pièces de bienvenue"],
  ["Al massimo {0} selezioni in una schedina", "At most {0} selections in one bet slip", "Höchstens {0} Tipps auf einem Wettschein", "Au maximum {0} sélections dans un bulletin"],
  ["Bentornato, {0}", "Welcome back, {0}", "Willkommen zurück, {0}", "Bon retour, {0}"],
  ["Bonus giornaliero: +{0} 🪙", "Daily bonus: +{0} 🪙", "Tagesbonus: +{0} 🪙", "Bonus quotidien : +{0} 🪙"],
  ["Codice {0} copiato: chi lo apre in Scommesse vede la giocata", "Code {0} copied: anyone who opens it in Bets sees the bet", "Code {0} kopiert: Wer ihn unter Wetten öffnet, sieht die Wette", "Code {0} copié : celui qui l'ouvre dans Paris voit le pari"],
  ["Condivisa: il codice è {0}", "Shared: the code is {0}", "Geteilt: Der Code ist {0}", "Partagé : le code est {0}"],
  ["Copiata da {0}: controlla quote e puntata, poi conferma.", "Copied from {0}: check odds and stake, then confirm.", "Kopiert von {0}: Prüfe Quoten und Einsatz, dann bestätige.", "Copié de {0} : vérifie cotes et mise, puis confirme."],
  ["copiata da {0}", "copied from {0}", "kopiert von {0}", "copié de {0}"],
  ["Errore del server ({0})", "Server error ({0})", "Serverfehler ({0})", "Erreur du serveur ({0})"],
  ["Esito finale, quota delle giocate ({0})", "Final result, share of bets ({0})", "Endergebnis, Anteil der Wetten ({0})", "Résultat final, part des paris ({0})"],
  ["Finale: tiri {0}–{1}, in porta {2}–{3}, corner {4}–{5}, cartellini {6}–{7}", "Full time: shots {0}–{1}, on target {2}–{3}, corners {4}–{5}, cards {6}–{7}", "Endstand: Schüsse {0}–{1}, aufs Tor {2}–{3}, Ecken {4}–{5}, Karten {6}–{7}", "Final : tirs {0}–{1}, cadrés {2}–{3}, corners {4}–{5}, cartons {6}–{7}"],
  ["Già riscosso oggi (serie di {0} giorni). Torna domani.", "Already collected today ({0}-day streak). Come back tomorrow.", "Heute schon abgeholt (Serie von {0} Tagen). Komm morgen wieder.", "Déjà récupéré aujourd'hui (série de {0} jours). Reviens demain."],
  ["Marcatori: {0}", "Scorers: {0}", "Torschützen: {0}", "Buteurs : {0}"],
  ["Mercato più giocato: {t0} ({1})", "Most bet market: {t0} ({1})", "Meistgespielter Markt: {t0} ({1})", "Marché le plus joué : {t0} ({1})"],
  ["Oggi ({0})", "Today ({0})", "Heute ({0})", "Aujourd'hui ({0})"],
  ["Premio spettatore: +{0} 🪙", "Spectator reward: +{0} 🪙", "Zuschauerprämie: +{0} 🪙", "Prime du spectateur : +{0} 🪙"],
  ["Questa partita è stata calcolata con un altro motore ({0}, il tuo gioco ha {1}): aggiorna il gioco per guardarla in 3D. Cronaca e risultato restano qui.", "This match was calculated with a different engine ({0}, your game has {1}): update the game to watch it in 3D. Commentary and result stay here.", "Dieses Spiel wurde mit einer anderen Engine berechnet ({0}, dein Spiel hat {1}): Aktualisiere das Spiel, um es in 3D zu sehen. Liveticker und Ergebnis bleiben hier.", "Ce match a été calculé avec un autre moteur ({0}, ton jeu a {1}) : mets à jour le jeu pour le regarder en 3D. Le direct et le résultat restent ici."],
  ["Quota cambiata: originale {0}, ora {1}", "Odds changed: originally {0}, now {1}", "Quote geändert: ursprünglich {0}, jetzt {1}", "Cote modifiée : d'origine {0}, maintenant {1}"],
  ["Riscuoti +{0} 🪙", "Collect +{0} 🪙", "Abholen +{0} 🪙", "Récupérer +{0} 🪙"],
  ["Saldo insufficiente ({0} 🪙)", "Not enough balance ({0} 🪙)", "Guthaben reicht nicht ({0} 🪙)", "Solde insuffisant ({0} 🪙)"],
  ["Salvato: numero {0}", "Saved: number {0}", "Gespeichert: Nummer {0}", "Enregistré : numéro {0}"],
  ["Salvato: numero {0}, {1}", "Saved: number {0}, {1}", "Gespeichert: Nummer {0}, {1}", "Enregistré : numéro {0}, {1}"],
  ["Scommessa {0} giocata: {1} 🪙 @{2}", "Bet {0} placed: {1} 🪙 @{2}", "Wette {0} platziert: {1} 🪙 @{2}", "Pari {0} placé : {1} 🪙 @{2}"],
  ["Scommesse aperte: chiudono tra {0}:{1}", "Betting open: closes in {0}:{1}", "Wetten offen: schliessen in {0}:{1}", "Paris ouverts : fermeture dans {0}:{1}"],
  ["Scommesse chiuse. Calcio d'inizio tra {0} s", "Betting closed. Kick-off in {0} s", "Wetten geschlossen. Anstoss in {0} s", "Paris fermés. Coup d'envoi dans {0} s"],
  ["Serie: giorno {0}", "Streak: day {0}", "Serie: Tag {0}", "Série : jour {0}"],
  ["Serie: giorno {0}. Evento del fine settimana: bonus doppio!", "Streak: day {0}. Weekend event: double bonus!", "Serie: Tag {0}. Wochenend-Event: doppelter Bonus!", "Série : jour {0}. Événement du week-end : bonus doublé !"],
  ["Sicuro? {0} 🪙", "Sure? {0} 🪙", "Sicher? {0} 🪙", "Sûr ? {0} 🪙"],
  ["Stagione {0} · giornata {1} di {2} · {3} partite finite", "Season {0} · matchday {1} of {2} · {3} matches played", "Saison {0} · Spieltag {1} von {2} · {3} Spiele beendet", "Saison {0} · journée {1} sur {2} · {3} matchs terminés"],
  ["Stagione {0} · giornata {1} di {2} · {3} partite finite · campione della stagione {4}: {5}", "Season {0} · matchday {1} of {2} · {3} matches played · season {4} champion: {5}", "Saison {0} · Spieltag {1} von {2} · {3} Spiele beendet · Meister der Saison {4}: {5}", "Saison {0} · journée {1} sur {2} · {3} matchs terminés · champion de la saison {4} : {5}"],
  ["Stagione {#0}", "Season {#0}", "Saison {#0}", "Saison {#0}"],
  ["saldo {0}", "balance {0}", "Guthaben {0}", "solde {0}"],
  ["tra {0}:{1}", "in {0}:{1}", "in {0}:{1}", "dans {0}:{1}"],
  ["{0} comprato: è nel tuo inventario", "{0} bought: it's in your inventory", "{0} gekauft: Es ist in deinem Inventar", "{0} acheté : il est dans ton inventaire"],
  ["{0} giocata · {1} 🪙", "{0} bet · {1} 🪙", "{0} Wette · {1} 🪙", "{0} pari · {1} 🪙"],
  ["{0} giocate · {1} 🪙", "{0} bets · {1} 🪙", "{0} Wetten · {1} 🪙", "{0} paris · {1} 🪙"],
  ["{t0} non può vincere insieme a {t1}.", "{t0} can't win together with {t1}.", "{t0} kann nicht zusammen mit {t1} gewinnen.", "{t0} ne peut pas gagner en même temps que {t1}."],
  ["{t0} non si può combinare con {t1}.", "{t0} can't be combined with {t1}.", "{t0} lässt sich nicht mit {t1} kombinieren.", "{t0} ne peut pas être combiné avec {t1}."],
  ["{#0} scommessa", "{#0} bet", "{#0} Wette", "{#0} pari"],
  ["{#0} scommesse", "{#0} bets", "{#0} Wetten", "{#0} paris"],
  ["{#0} selezione", "{#0} selection", "{#0} Tipp", "{#0} sélection"],
  ["{#0} selezioni", "{#0} selections", "{#0} Tipps", "{#0} sélections"],
  ["{#0} copia", "{#0} copy", "{#0} Kopie", "{#0} copie"],
  ["{#0} copie", "{#0} copies", "{#0} Kopien", "{#0} copies"],
  ["{0} selezione valida per il bonus", "{0} selection counts for the bonus", "{0} Tipp zählt für den Bonus", "{0} sélection valable pour le bonus"],
  ["{0} selezioni valide per il bonus", "{0} selections count for the bonus", "{0} Tipps zählen für den Bonus", "{0} sélections valables pour le bonus"],
  ["{0} selezione valida per il bonus · con {1} il bonus diventa +{2}%", "{0} selection counts for the bonus · with {1} the bonus becomes +{2}%", "{0} Tipp zählt für den Bonus · mit {1} wird der Bonus +{2}%", "{0} sélection valable pour le bonus · avec {1} le bonus passe à +{2} %"],
  ["{0} selezioni valide per il bonus · con {1} il bonus diventa +{2}%", "{0} selections count for the bonus · with {1} the bonus becomes +{2}%", "{0} Tipps zählen für den Bonus · mit {1} wird der Bonus +{2}%", "{0} sélections valables pour le bonus · avec {1} le bonus passe à +{2} %"],
  ["{t0}. Puoi riprovare: la scommessa non verrà registrata due volte.", "{t0}. You can try again: the bet won't be recorded twice.", "{t0}. Du kannst es erneut versuchen: Die Wette wird nicht doppelt gespeichert.", "{t0}. Tu peux réessayer : le pari ne sera pas enregistré deux fois."],
  ["→ {0} 🪙 possibili", "→ {0} 🪙 possible", "→ {0} 🪙 möglich", "→ {0} 🪙 possibles"],
  ["✅ Vinta +{0}", "✅ Won +{0}", "✅ Gewonnen +{0}", "✅ Gagné +{0}"],
  ["Selezioni collegate della stessa partita: quota della partita", "Linked selections from the same match: match odds", "Verbundene Tipps aus demselben Spiel: Spielquote", "Sélections liées du même match : cote du match"],
  ["invece di {0}", "instead of {0}", "statt {0}", "au lieu de {0}"],
  ["Vincita più alta: {0} 🪙 di {1} @{2} ({3})", "Biggest win: {0} 🪙 by {1} @{2} ({3})", "Höchster Gewinn: {0} 🪙 von {1} @{2} ({3})", "Plus gros gain : {0} 🪙 de {1} @{2} ({3})"],
  ["Vincita possibile più alta: {0} 🪙 di {1}", "Biggest potential win: {0} 🪙 by {1}", "Höchster möglicher Gewinn: {0} 🪙 von {1}", "Plus gros gain possible : {0} 🪙 de {1}"],
  ["Colletto a contrasto", "Contrast collar", "Kontrastkragen", "Col contrasté"],
  ["Maniche bicolore", "Two-tone sleeves", "Zweifarbige Ärmel", "Manches bicolores"],
  ["Righe verticali", "Vertical stripes", "Vertikale Streifen", "Rayures verticales"],
  ["Fascia diagonale", "Diagonal sash", "Diagonaler Streifen", "Bande diagonale"],
  ["Bordi dorati", "Gold trim", "Goldene Ränder", "Bordures dorées"],
  ["Notte stellata", "Starry night", "Sternennacht", "Nuit étoilée"],
  ["Pantaloncini bianchi", "White shorts", "Weisse Hose", "Short blanc"],
  ["Pantaloncini neri", "Black shorts", "Schwarze Hose", "Short noir"],
  ["Pantaloncini rossi", "Red shorts", "Rote Hose", "Short rouge"],
  ["Pantaloncini oro", "Gold shorts", "Goldene Hose", "Short doré"],
  ["Calzettoni bianchi", "White socks", "Weisse Stutzen", "Chaussettes blanches"],
  ["Calzettoni a righe", "Striped socks", "Gestreifte Stutzen", "Chaussettes rayées"],
  ["Calzettoni fluo", "Neon socks", "Neon-Stutzen", "Chaussettes fluo"],
  ["Scarpe classiche nere", "Classic black boots", "Klassische schwarze Schuhe", "Chaussures noires classiques"],
  ["Scarpe bianche", "White boots", "Weisse Schuhe", "Chaussures blanches"],
  ["Scarpe fuoco", "Fire boots", "Feuerschuhe", "Chaussures de feu"],
  ["Scarpe lime", "Lime boots", "Limettengrüne Schuhe", "Chaussures citron vert"],
  ["Scarpe d'oro", "Golden boots", "Goldene Schuhe", "Chaussures en or"],
  ["Guanti neri", "Black gloves", "Schwarze Handschuhe", "Gants noirs"],
  ["Guanti blu", "Blue gloves", "Blaue Handschuhe", "Gants bleus"],
  ["Guanti arancioni", "Orange gloves", "Orange Handschuhe", "Gants orange"],
  ["Cresta", "Mohawk", "Irokese", "Crête"],
  ["Ricci", "Curls", "Locken", "Boucles"],
  ["Biondo platino", "Platinum blond", "Platinblond", "Blond platine"],
  ["Rasati", "Shaved", "Rasiert", "Rasés"],
  ["Ciuffo blu", "Blue quiff", "Blaue Tolle", "Mèche bleue"],
  ["Fascia per capelli", "Headband", "Haarband", "Bandeau"],
  ["Fascia per capelli rossa", "Red headband", "Rotes Haarband", "Bandeau rouge"],
  ["Polsini", "Wristbands", "Schweissbänder", "Poignets"],
  ["Fascia da capitano", "Captain's armband", "Kapitänsbinde", "Brassard de capitaine"],
  ["Prima giocata", "First bet", "Erste Wette", "Premier pari"],
  ["Piazza la tua prima scommessa", "Place your first bet", "Platziere deine erste Wette", "Place ton premier pari"],
  ["Prima vittoria", "First win", "Erster Sieg", "Première victoire"],
  ["Vinci la tua prima scommessa", "Win your first bet", "Gewinne deine erste Wette", "Gagne ton premier pari"],
  ["Habitué", "Regular", "Stammgast", "Habitué"],
  ["Piazza 10 scommesse", "Place 10 bets", "Platziere 10 Wetten", "Place 10 paris"],
  ["In serie", "On a roll", "Serienweise", "En série"],
  ["Vinci 5 scommesse di fila", "Win 5 bets in a row", "Gewinne 5 Wetten in Folge", "Gagne 5 paris d'affilée"],
  ["Colpo grosso", "Big hit", "Grosser Coup", "Gros coup"],
  ["Vinci una scommessa con quota 5 o più", "Win a bet with odds of 5 or more", "Gewinne eine Wette mit Quote 5 oder mehr", "Gagne un pari avec une cote de 5 ou plus"],
  ["Nuovo look", "New look", "Neuer Look", "Nouveau look"],
  ["Compra il primo articolo del negozio", "Buy your first item from the shop", "Kaufe deinen ersten Artikel im Shop", "Achète ton premier article en boutique"],
  ["Fedelissimo", "Loyal fan", "Treuester Fan", "Fidèle parmi les fidèles"],
  ["Ritira il bonus giornaliero 7 giorni di fila", "Collect the daily bonus 7 days in a row", "Hole den Tagesbonus 7 Tage in Folge ab", "Récupère le bonus quotidien 7 jours d'affilée"],
  ["Compra", "Buy", "Kaufen", "Acheter"],
  ["Saldo insufficiente", "Not enough balance", "Guthaben reicht nicht", "Solde insuffisant"],
]);
