// Competizioni (src/18_competitions.js, src/19_competitions_ui.js, cloud/src/complogic.js): campionato, torneo, coppe, sfide tra amici
// Ogni riga: [italiano, inglese, tedesco, francese]
addTranslations([
  ["Coppa", "Cup", "Pokal", "Coupe"],
  ["Coppa Nazionale", "National Cup", "Nationaler Pokal", "Coupe nationale"],
  ["Coppa dei Campioni", "Champions Cup", "Pokal der Meister", "Coupe des champions"],
  ["Coppa Lampo", "Lightning Cup", "Blitz-Pokal", "Coupe éclair"],
  ["Coppa della Tradizione", "Heritage Cup", "Traditionspokal", "Coupe de la tradition"],
  ["Finale", "Final", "Finale", "Finale"],
  ["Semifinali", "Semi-finals", "Halbfinale", "Demi-finales"],
  ["Quarti di finale", "Quarter-finals", "Viertelfinale", "Quarts de finale"],
  ["Ottavi di finale", "Round of 16", "Achtelfinale", "Huitièmes de finale"],
  ["Sedicesimi di finale", "Round of 32", "Sechzehntelfinale", "Seizièmes de finale"],
  ["Trentaduesimi", "Round of 64", "Runde der letzten 64", "Trente-deuxièmes de finale"],
  ["Turno", "Round", "Runde", "Tour"],
  ["Turno a {0}", "Round of {0}", "Runde der letzten {0}", "Tour à {0}"],
  ["Fase a gironi, giornata {0}", "Group stage, matchday {0}", "Gruppenphase, Spieltag {0}", "Phase de groupes, journée {0}"],
  ["{t0}, andata", "{t0}, first leg", "{t0}, Hinspiel", "{t0}, aller"],
  ["{t0}, ritorno", "{t0}, second leg", "{t0}, Rückspiel", "{t0}, retour"],
  ["{t0}, ripetizioni", "{t0}, replays", "{t0}, Wiederholungsspiele", "{t0}, matchs à rejouer"],
  ["Il tabellone vuole 4, 8, 16 o 32 squadre", "The bracket needs 4, 8, 16 or 32 teams", "Der Turnierbaum braucht 4, 8, 16 oder 32 Teams", "Le tableau demande 4, 8, 16 ou 32 équipes"],
  ["Le qualificate devono essere 4, 8, 16 o 32", "The qualified teams must be 4, 8, 16 or 32", "Es müssen sich 4, 8, 16 oder 32 Teams qualifizieren", "Les qualifiées doivent être 4, 8, 16 ou 32"],
  ["Le squadre devono dividersi in gironi da almeno 3", "Teams must split into groups of at least 3", "Die Teams müssen sich in Gruppen von mindestens 3 aufteilen", "Les équipes doivent se répartir en groupes d'au moins 3"],
  ["Mancano i rigori", "Penalties missing", "Elfmeterschiessen fehlt", "Il manque les tirs au but"],
  ["Mancano i supplementari", "Extra time missing", "Verlängerung fehlt", "Il manque les prolongations"],
  ["Rigori non previsti", "No penalties in this format", "Kein Elfmeterschiessen vorgesehen", "Tirs au but non prévus"],
  ["Risultato non valido", "Invalid result", "Ungültiges Ergebnis", "Résultat non valide"],
  ["Supplementari e rigori non previsti in questa partita", "No extra time or penalties in this match", "In diesem Spiel sind weder Verlängerung noch Elfmeterschiessen vorgesehen", "Ni prolongations ni tirs au but prévus dans ce match"],
  ["Supplementari non previsti", "No extra time in this format", "Keine Verlängerung vorgesehen", "Prolongations non prévues"],
  ["Un campionato vuole da 4 a 32 squadre", "A league needs 4 to 32 teams", "Eine Meisterschaft braucht 4 bis 32 Teams", "Un championnat demande de 4 à 32 équipes"],
  ["il tabellone vuole 2, 4, 8, 16, 32 o 64 squadre", "the bracket needs 2, 4, 8, 16, 32 or 64 teams", "der Turnierbaum braucht 2, 4, 8, 16, 32 oder 64 Teams", "le tableau demande 2, 4, 8, 16, 32 ou 64 équipes"],
  ["le squadre devono dividersi in gironi uguali", "teams must split into equal groups", "die Teams müssen sich in gleich grosse Gruppen aufteilen", "les équipes doivent se répartir en groupes égaux"],
  ["Troppe competizioni salvate: eliminane una", "Too many saved competitions: delete one", "Zu viele gespeicherte Wettbewerbe: Lösche einen", "Trop de compétitions enregistrées : supprimes-en une"],
  ["(ha lasciato, ora IA)", "(left, now AI)", "(hat verlassen, jetzt KI)", "(est parti, maintenant IA)"],
  ["Accetta l'invito", "Accept the invite", "Einladung annehmen", "Accepter l'invitation"],
  ["Amichevole", "Friendly", "Freundschaftsspiel", "Amical"],
  ["Ancora nessuna partita giocata.", "No matches played yet.", "Noch keine Spiele gespielt.", "Aucun match joué pour l'instant."],
  ["Andata e ritorno", "Home and away", "Hin- und Rückspiel", "Aller-retour"],
  ["Andata e ritorno (finale secca)", "Home and away (one-off final)", "Hin- und Rückspiel (Finale in einem Spiel)", "Aller-retour (finale sur un match)"],
  ["Andata e ritorno.", "Home and away.", "Hin- und Rückspiel.", "Aller-retour."],
  ["andata e ritorno", "home and away", "Hin- und Rückspiel", "aller-retour"],
  ["andata e ritorno, totale {0}", "home and away, aggregate {0}", "Hin- und Rückspiel, gesamt {0}", "aller-retour, total {0}"],
  ["Solo andata", "Single leg", "Nur Hinspiel", "Aller simple"],
  ["Solo andata.", "Single leg.", "Nur Hinspiel.", "Aller simple."],
  ["solo andata", "single leg", "nur Hinspiel", "aller simple"],
  ["Cambia squadra", "Change team", "Team wechseln", "Changer d'équipe"],
  ["Campo neutro", "Neutral ground", "Neutraler Platz", "Terrain neutre"],
  ["In casa", "At home", "Zu Hause", "À domicile"],
  ["In trasferta", "Away", "Auswärts", "À l'extérieur"],
  ["Caricamento degli amici…", "Loading friends…", "Freunde werden geladen…", "Chargement des amis…"],
  ["Chiedi la simulazione", "Ask for the simulation", "Simulation anfragen", "Demander la simulation"],
  ["Simula (l'ha chiesto {0})", "Simulate ({0} asked for it)", "Simulieren ({0} hat es angefragt)", "Simuler ({0} l'a demandé)"],
  ["Classifica", "Table", "Tabelle", "Classement"],
  ["Classifica finale", "Final table", "Abschlusstabelle", "Classement final"],
  ["Competizione eliminata", "Competition deleted", "Wettbewerb gelöscht", "Compétition supprimée"],
  ["Continua", "Continue", "Weiter", "Continuer"],
  ["Visualizza", "View", "Ansehen", "Voir"],
  ["Crea e invita", "Create and invite", "Erstellen und einladen", "Créer et inviter"],
  ["Creata: invita gli amici e poi inizia", "Created: invite your friends, then start", "Erstellt: Lade deine Freunde ein und starte dann", "Créée : invite tes amis puis commence"],
  ["Creata: inviti mandati a {0}", "Created: invites sent to {0}", "Erstellt: Einladungen an {0} gesendet", "Créée : invitations envoyées à {0}"],
  ["Eliminazione diretta", "Knockout", "K.-o.-System", "Élimination directe"],
  ["Eliminazione diretta.", "Knockout.", "K.-o.-System.", "Élimination directe."],
  ["Eliminazione diretta con andata e ritorno (finale secca).", "Knockout, home and away (one-off final).", "K.-o.-System mit Hin- und Rückspiel (Finale in einem Spiel).", "Élimination directe en aller-retour (finale sur un match)."],
  ["Entra nella partita", "Join the match", "Dem Spiel beitreten", "Rejoindre le match"],
  ["Gara unica", "Single match", "Ein Spiel", "Match unique"],
  ["Giocata da te", "Played by you", "Von dir gespielt", "Joué par toi"],
  ["Giocata da {0}", "Played by {0}", "Gespielt von {0}", "Joué par {0}"],
  ["giocata", "played", "gespielt", "joué"],
  ["Giocata online tra amici", "Played online between friends", "Online unter Freunden gespielt", "Joué en ligne entre amis"],
  ["online", "online", "online", "en ligne"],
  ["Gironi", "Groups", "Gruppen", "Groupes"],
  ["Gironi + eliminazione", "Groups + knockout", "Gruppen + K.-o.", "Groupes + élimination"],
  ["Girone {0}", "Group {0}", "Gruppe {0}", "Groupe {0}"],
  ["Girone {0}, {1}º", "Group {0}, {1}th", "Gruppe {0}, {1}.", "Groupe {0}, {1}e"],
  ["Girone {0}, {1}º · {2} pt", "Group {0}, {1}th · {2} pts", "Gruppe {0}, {1}. · {2} Pkt.", "Groupe {0}, {1}e · {2} pts"],
  ["{0}º · {1} pt", "{0}th · {1} pts", "{0}. · {1} Pkt.", "{0}e · {1} pts"],
  ["{#0} punti", "{#0} points", "{#0} Punkte", "{#0} points"],
  ["eliminata", "out", "ausgeschieden", "éliminée"],
  ["conclusa", "finished", "beendet", "terminée"],
  ["organizza", "organiser", "Organisator", "organise"],
  ["Gol", "Goals", "Tore", "Buts"],
  ["Hai lasciato la competizione", "You left the competition", "Du hast den Wettbewerb verlassen", "Tu as quitté la compétition"],
  ["I due risultati non coincidono: controllate nella competizione", "The two results don't match: check in the competition", "Die beiden Ergebnisse stimmen nicht überein: Prüft es im Wettbewerb", "Les deux résultats ne correspondent pas : vérifiez dans la compétition"],
  ["I due risultati non coincidono: {0}", "The two results don't match: {0}", "Die beiden Ergebnisse stimmen nicht überein: {0}", "Les deux résultats ne correspondent pas : {0}"],
  ["rigiocate la partita o chiedete entrambi la simulazione.", "replay the match or both ask for the simulation.", "spielt das Spiel nochmals oder fragt beide die Simulation an.", "rejouez le match ou demandez tous les deux la simulation."],
  ["Il risultato della partita va sul server da solo. Se esci a metà, il resto si simula dal punteggio; una partita iniziata e mai finita non si rigioca (decide la simulazione).", "The match result goes to the server by itself. If you leave halfway, the rest is simulated from the score; a match started and never finished isn't replayed (the simulation decides).", "Das Ergebnis geht automatisch an den Server. Verlässt du das Spiel vorzeitig, wird der Rest ab dem Spielstand simuliert; ein begonnenes und nie beendetes Spiel wird nicht wiederholt (die Simulation entscheidet).", "Le résultat du match part tout seul au serveur. Si tu quittes en cours, la suite est simulée à partir du score ; un match commencé et jamais terminé n'est pas rejoué (la simulation décide)."],
  ["Il risultato torna da solo nella competizione; le altre partite della giornata si simulano.", "The result goes back into the competition by itself; the other matches of the round are simulated.", "Das Ergebnis kommt automatisch in den Wettbewerb; die anderen Spiele des Spieltags werden simuliert.", "Le résultat revient tout seul dans la compétition ; les autres matchs de la journée sont simulés."],
  ["In caso di parità, supplementari e rigori li decide la simulazione ufficiale.", "If it's a draw, the official simulation decides extra time and penalties.", "Bei Unentschieden entscheidet die offizielle Simulation über Verlängerung und Elfmeterschiessen.", "En cas d'égalité, la simulation officielle décide des prolongations et des tirs au but."],
  ["Inizia la competizione", "Start the competition", "Wettbewerb starten", "Lancer la compétition"],
  ["Invita altri amici", "Invite more friends", "Weitere Freunde einladen", "Inviter d'autres amis"],
  ["Invito rifiutato", "Invite declined", "Einladung abgelehnt", "Invitation refusée"],
  ["Invito mandato a {0}", "Invite sent to {0}", "Einladung an {0} gesendet", "Invitation envoyée à {0}"],
  ["La competizione non esiste più", "The competition no longer exists", "Der Wettbewerb existiert nicht mehr", "La compétition n'existe plus"],
  ["La tua richiesta e quella del tuo amico non coincidono", "Your request and your friend's don't match", "Deine Anfrage und die deines Freundes stimmen nicht überein", "Ta demande et celle de ton ami ne correspondent pas"],
  ["La tua squadra riposa in questa giornata.", "Your team has a bye this matchday.", "Dein Team hat an diesem Spieltag spielfrei.", "Ton équipe est au repos lors de cette journée."],
  ["La tua squadra riposa in questo turno.", "Your team has a bye this round.", "Dein Team hat in dieser Runde spielfrei.", "Ton équipe est au repos lors de ce tour."],
  ["La tua squadra è stata eliminata. Puoi simulare il resto della competizione.", "Your team has been knocked out. You can simulate the rest of the competition.", "Dein Team ist ausgeschieden. Du kannst den Rest des Wettbewerbs simulieren.", "Ton équipe a été éliminée. Tu peux simuler le reste de la compétition."],
  ["La tua squadra è stata eliminata: guardi come va a finire.", "Your team has been knocked out: you watch how it ends.", "Dein Team ist ausgeschieden: Du schaust, wie es ausgeht.", "Ton équipe a été éliminée : tu regardes comment ça se termine."],
  ["Lascia", "Leave", "Verlassen", "Quitter"],
  ["Lasciata a metà: il resto è stato simulato", "Left unfinished: the rest was simulated", "Abgebrochen: Der Rest wurde simuliert", "Abandonné en cours : la suite a été simulée"],
  ["Miglior attacco", "Best attack", "Bester Angriff", "Meilleure attaque"],
  ["Miglior difesa", "Best defence", "Beste Abwehr", "Meilleure défense"],
  ["Miglior attacco: {0} ({1})", "Best attack: {0} ({1})", "Bester Angriff: {0} ({1})", "Meilleure attaque : {0} ({1})"],
  ["Capocannoniere", "Top scorer", "Torschützenkönig", "Meilleur buteur"],
  ["Capocannoniere: {0} ({1})", "Top scorer: {0} ({1})", "Torschützenkönig: {0} ({1})", "Meilleur buteur : {0} ({1})"],
  ["Nessun altro amico da invitare (aggiungili dal pannello Amici nella Home).", "No other friends to invite (add them from the Friends panel on the Home screen).", "Keine weiteren Freunde zum Einladen (füge sie im Freunde-Bereich auf der Startseite hinzu).", "Aucun autre ami à inviter (ajoute-les depuis le panneau Amis de l'accueil)."],
  ["Nessun amico ancora: aggiungili dal pannello Amici nella Home (puoi anche creare la sfida e invitarli dopo).", "No friends yet: add them from the Friends panel on the Home screen (you can also create the challenge and invite them later).", "Noch keine Freunde: Füge sie im Freunde-Bereich auf der Startseite hinzu (du kannst die Herausforderung auch erstellen und sie später einladen).", "Pas encore d'amis : ajoute-les depuis le panneau Amis de l'accueil (tu peux aussi créer le défi et les inviter après)."],
  ["Nessun campionato: creane uno con il calendario all'italiana, classifica e stagioni.", "No leagues: create one with a round-robin schedule, table and seasons.", "Keine Meisterschaft: Erstelle eine mit Spielplan Jeder gegen Jeden, Tabelle und Saisons.", "Aucun championnat : crées-en un avec calendrier aller-retour, classement et saisons."],
  ["Nessun gol.", "No goals.", "Keine Tore.", "Aucun but."],
  ["Nessun torneo: 8, 16 o 32 squadre, eliminazione diretta fino alla finale.", "No tournaments: 8, 16 or 32 teams, knockout all the way to the final.", "Kein Turnier: 8, 16 oder 32 Teams, K.-o.-System bis zum Finale.", "Aucun tournoi : 8, 16 ou 32 équipes, élimination directe jusqu'à la finale."],
  ["Nessuna (solo simulazione)", "None (simulation only)", "Keins (nur Simulation)", "Aucune (simulation seulement)"],
  ["Nessuna coppa: scegli un modello o crea il tuo formato (gironi, andata e ritorno, supplementari, rigori).", "No cups: choose a preset or create your own format (groups, home and away, extra time, penalties).", "Kein Pokal: Wähle eine Vorlage oder erstelle dein eigenes Format (Gruppen, Hin- und Rückspiel, Verlängerung, Elfmeterschiessen).", "Aucune coupe : choisis un modèle ou crée ton format (groupes, aller-retour, prolongations, tirs au but)."],
  ["Nessuna partita.", "No matches.", "Keine Spiele.", "Aucun match."],
  ["Nessuna squadra scelta: le partite si simulano.", "No team chosen: the matches are simulated.", "Kein Team gewählt: Die Spiele werden simuliert.", "Aucune équipe choisie : les matchs sont simulés."],
  ["Niente supplementari", "No extra time", "Keine Verlängerung", "Pas de prolongations"],
  ["No (ripetizione)", "No (replay)", "Nein (Wiederholung)", "Non (match à rejouer)"],
  ["Non hai una squadra in questa competizione.", "You don't have a team in this competition.", "Du hast kein Team in diesem Wettbewerb.", "Tu n'as pas d'équipe dans cette compétition."],
  ["Nuova edizione", "New edition", "Neue Ausgabe", "Nouvelle édition"],
  ["Nuova edizione: sorteggio fatto", "New edition: draw made", "Neue Ausgabe: Auslosung erfolgt", "Nouvelle édition : tirage effectué"],
  ["Nuova stagione", "New season", "Neue Saison", "Nouvelle saison"],
  ["Nuova stagione: calendario pronto", "New season: fixtures ready", "Neue Saison: Spielplan bereit", "Nouvelle saison : calendrier prêt"],
  ["Ogni amico sceglie una squadra libera quando accetta; le altre le guida l'IA. Si gioca online tra amici, contro l'IA da soli.", "Each friend picks a free team when accepting; the AI controls the others. Matches between friends are online, against the AI you play alone.", "Jeder Freund wählt beim Annehmen ein freies Team; die anderen steuert die KI. Unter Freunden wird online gespielt, gegen die KI allein.", "Chaque ami choisit une équipe libre en acceptant ; l'IA dirige les autres. On joue en ligne entre amis, seul contre l'IA."],
  ["Ognuno sceglie una squadra; le altre le guida l'IA.", "Everyone picks a team; the AI controls the others.", "Jeder wählt ein Team; die anderen steuert die KI.", "Chacun choisit une équipe ; l'IA dirige les autres."],
  ["Panoramica", "Overview", "Übersicht", "Aperçu"],
  ["Partecipanti", "Participants", "Teilnehmer", "Participants"],
  ["Partita bloccata: decide la simulazione ufficiale", "Match stuck: the official simulation decides", "Spiel blockiert: Die offizielle Simulation entscheidet", "Match bloqué : la simulation officielle décide"],
  ["Partita online 1 contro 1, fuori dalla competizione", "Online 1-v-1 match, outside the competition", "Online-Spiel 1 gegen 1, ausserhalb des Wettbewerbs", "Match en ligne 1 contre 1, hors compétition"],
  ["Partite in attesa", "Pending matches", "Ausstehende Spiele", "Matchs en attente"],
  ["Partite senza subire gol", "Clean sheets", "Spiele ohne Gegentor", "Matchs sans encaisser de but"],
  ["Personalizzata", "Custom", "Benutzerdefiniert", "Personnalisée"],
  ["Prossima", "Next", "Nächstes", "Prochain"],
  ["Ultima", "Last", "Letztes", "Dernier"],
  ["Quando inizi si fa il calendario (o il sorteggio) e non si entra più.", "When you start, the fixtures (or the draw) are made and nobody else can join.", "Beim Start wird der Spielplan (oder die Auslosung) erstellt und niemand kann mehr beitreten.", "Quand tu commences, le calendrier (ou le tirage) est fait et on ne peut plus entrer."],
  ["Riapri la stanza", "Reopen the room", "Raum wieder öffnen", "Rouvrir le salon"],
  ["Richiesta mandata: aspetta la risposta del tuo amico", "Request sent: wait for your friend's reply", "Anfrage gesendet: Warte auf die Antwort deines Freundes", "Demande envoyée : attends la réponse de ton ami"],
  ["Rifiuta", "Decline", "Ablehnen", "Refuser"],
  ["Ripetizione dopo il pareggio.", "Replay after the draw.", "Wiederholung nach dem Unentschieden.", "Match rejoué après le nul."],
  ["Risultato mandato: si registra quando lo manda anche il tuo amico", "Result sent: it's recorded when your friend sends it too", "Ergebnis gesendet: Es wird gespeichert, wenn dein Freund es auch sendet", "Résultat envoyé : il est enregistré quand ton ami l'envoie aussi"],
  ["Risultato registrato · la competizione è finita!", "Result recorded · the competition is over!", "Ergebnis gespeichert · der Wettbewerb ist beendet!", "Résultat enregistré · la compétition est terminée !"],
  ["Scegli la tua squadra", "Choose your team", "Wähle dein Team", "Choisis ton équipe"],
  ["Serve un vincitore.", "A winner is needed.", "Es braucht einen Sieger.", "Il faut un vainqueur."],
  ["Serve un vincitore: {0}.", "A winner is needed: {0}.", "Es braucht einen Sieger: {0}.", "Il faut un vainqueur : {0}."],
  ["@{0} e {1}", "{0} and {1}", "{0} und {1}", "{0} et {1}"],
  ["supplementari", "extra time", "Verlängerung", "prolongations"],
  ["rigori", "penalties", "Elfmeterschiessen", "tirs au but"],
  ["ripetizione in caso di parità", "replay if level", "Wiederholung bei Unentschieden", "match rejoué en cas d'égalité"],
  ["rigori.", "penalties.", "Elfmeterschiessen.", "tirs au but."],
  ["ripetizione in caso di parità.", "replay if level.", "Wiederholung bei Unentschieden.", "match rejoué en cas d'égalité."],
  ["Sfida tra amici", "Challenge between friends", "Herausforderung unter Freunden", "Défi entre amis"],
  ["Si parte!", "Here we go!", "Los geht's!", "C'est parti !"],
  ["Calendario pronto", "Fixtures ready", "Spielplan bereit", "Calendrier prêt"],
  ["Sorteggio fatto", "Draw made", "Auslosung erfolgt", "Tirage effectué"],
  ["Calendario pronto: {t0}", "Fixtures ready: {t0}", "Spielplan bereit: {t0}", "Calendrier prêt : {t0}"],
  ["Sorteggio fatto: {t0}", "Draw made: {t0}", "Auslosung erfolgt: {t0}", "Tirage effectué : {t0}"],
  ["Sicuro? Elimina", "Sure? Delete", "Sicher? Löschen", "Sûr ? Supprimer"],
  ["Sicuro? Elimina per tutti", "Sure? Delete for everyone", "Sicher? Für alle löschen", "Sûr ? Supprimer pour tous"],
  ["Sicuro? Lascia", "Sure? Leave", "Sicher? Verlassen", "Sûr ? Quitter"],
  ["Sicuro? Simula tutto", "Sure? Simulate everything", "Sicher? Alles simulieren", "Sûr ? Tout simuler"],
  ["Simula", "Simulate", "Simulieren", "Simuler"],
  ["Simula fino alla fine", "Simulate to the end", "Bis zum Ende simulieren", "Simuler jusqu'à la fin"],
  ["Simula giornata", "Simulate matchday", "Spieltag simulieren", "Simuler la journée"],
  ["Simula partita", "Simulate match", "Spiel simulieren", "Simuler le match"],
  ["Simulazione ufficiale", "Official simulation", "Offizielle Simulation", "Simulation officielle"],
  ["Solo simulazione", "Simulation only", "Nur Simulation", "Simulation seulement"],
  ["Tabellone", "Bracket", "Turnierbaum", "Tableau"],
  ["Calendario", "Fixtures", "Spielplan", "Calendrier"],
  ["Marcatori", "Scorers", "Torschützen", "Buteurs"],
  ["Turno precedente", "Previous round", "Vorherige Runde", "Tour précédent"],
  ["Turno successivo", "Next round", "Nächste Runde", "Tour suivant"],
  ["Una partita di competizione lasciata a metà è stata completata con la simulazione", "A competition match left unfinished was completed by simulation", "Ein abgebrochenes Wettbewerbsspiel wurde per Simulation beendet", "Un match de compétition abandonné en cours a été terminé par la simulation"],
  ["{0} partite lasciate a metà sono state completate con la simulazione", "{0} matches left unfinished were completed by simulation", "{0} abgebrochene Spiele wurden per Simulation beendet", "{0} matchs abandonnés en cours ont été terminés par la simulation"],
  ["Uno dei due apre la stanza, l'altro entra da qui. A fine partita il gioco manda il risultato per entrambi: vale quando coincide.", "One of you opens the room, the other joins from here. At full time the game sends the result for both: it counts when they match.", "Einer von euch öffnet den Raum, der andere tritt hier bei. Nach dem Spiel sendet das Spiel das Ergebnis für beide: Es zählt, wenn es übereinstimmt.", "L'un de vous ouvre le salon, l'autre entre d'ici. À la fin du match, le jeu envoie le résultat pour les deux : il compte quand il correspond."],
  ["Vittoria 3 punti, pareggio 1, sconfitta 0. A pari punti contano gli scontri diretti, poi la differenza reti e i gol fatti. Forma: ultime 5 partite.", "Win 3 points, draw 1, defeat 0. On equal points, head-to-head counts, then goal difference and goals scored. Form: last 5 matches.", "Sieg 3 Punkte, Unentschieden 1, Niederlage 0. Bei Punktgleichheit zählen die direkten Duelle, dann die Tordifferenz und die erzielten Tore. Form: letzte 5 Spiele.", "Victoire 3 points, nul 1, défaite 0. À égalité de points comptent les confrontations directes, puis la différence de buts et les buts marqués. Forme : 5 derniers matchs."],
  ["Vittoria più larga", "Biggest win", "Höchster Sieg", "Plus large victoire"],
  ["da decidere", "to be decided", "offen", "à déterminer"],
  ["forma", "form", "Form", "forme"],
  ["facile", "easy", "leicht", "facile"],
  ["normale", "normal", "normal", "normale"],
  ["difficile", "hard", "schwer", "difficile"],
  ["IA {0}", "AI {0}", "KI {0}", "IA {0}"],
  ["tempi da {0} minuti", "{0}-minute halves", "Halbzeiten zu {0} Minuten", "mi-temps de {0} minutes"],
  ["contro l'IA", "against the AI", "gegen die KI", "contre l'IA"],
  ["contro {0}", "against {0}", "gegen {0}", "contre {0}"],
  ["contro", "vs", "gegen", "contre"],
  ["si gioca online", "played online", "es wird online gespielt", "on joue en ligne"],
  ["nessuna partita in questa giornata", "no match this matchday", "kein Spiel an diesem Spieltag", "aucun match lors de cette journée"],
  ["eliminata: si può simulare il resto", "knocked out: the rest can be simulated", "ausgeschieden: Der Rest kann simuliert werden", "éliminée : on peut simuler la suite"],
  ["risultati diversi", "different results", "unterschiedliche Ergebnisse", "résultats différents"],
  ["tocca a {0}", "{0} to play", "{0} ist dran", "à {0} de jouer"],
  ["(rig. {0}-{1})", "(pens {0}-{1})", "(i.E. {0}-{1})", "(t.a.b. {0}-{1})"],
  ["rig. {0}-{1}", "pens {0}-{1}", "i.E. {0}-{1}", "t.a.b. {0}-{1}"],
  ["{0} (rig. {1}-{2})", "{0} (pens {1}-{2})", "{0} (i.E. {1}-{2})", "{0} (t.a.b. {1}-{2})"],
  ["{0} (d.t.s.)", "{0} (a.e.t.)", "{0} (n.V.)", "{0} (a.p.)"],
  ["(d.t.s.)", "(a.e.t.)", "(n.V.)", "(a.p.)"],
  ["Aspetta che {0} avvii la competizione: la vedrai partire qui e nel pannello Amici.", "Wait for {0} to start the competition: you'll see it begin here and in the Friends panel.", "Warte, bis {0} den Wettbewerb startet: Du siehst den Start hier und im Freunde-Bereich.", "Attends que {0} lance la compétition : tu la verras démarrer ici et dans le panneau Amis."],
  ["Campione · edizione {0}", "Champion · edition {0}", "Sieger · Ausgabe {0}", "Champion · édition {0}"],
  ["Campione · stagione {0}", "Champion · season {0}", "Meister · Saison {0}", "Champion · saison {0}"],
  ["Vincitore · edizione {0}", "Winner · edition {0}", "Sieger · Ausgabe {0}", "Vainqueur · édition {0}"],
  ["Vincitore · stagione {0}", "Winner · season {0}", "Sieger · Saison {0}", "Vainqueur · saison {0}"],
  ["Edizione {0}", "Edition {0}", "Ausgabe {0}", "Édition {0}"],
  ["Finale: {0}", "Final: {0}", "Finale: {0}", "Finale : {0}"],
  ["Giornata simulata ({0} partite)", "Matchday simulated ({0} matches)", "Spieltag simuliert ({0} Spiele)", "Journée simulée ({0} matchs)"],
  ["Hai aperto la stanza {0}: aspetta che {1} entri.", "You opened room {0}: wait for {1} to join.", "Du hast den Raum {0} geöffnet: Warte, bis {1} beitritt.", "Tu as ouvert le salon {0} : attends que {1} entre."],
  ["{0} ti aspetta nella stanza {1}.", "{0} is waiting for you in room {1}.", "{0} wartet im Raum {1} auf dich.", "{0} t'attend dans le salon {1}."],
  ["Hai mandato: {0}.", "You sent: {0}.", "Du hast gesendet: {0}.", "Tu as envoyé : {0}."],
  ["{0} ha mandato: {1}.", "{0} sent: {1}.", "{0} hat gesendet: {1}.", "{0} a envoyé : {1}."],
  ["La nuova stagione la avvia {0}, che ha creato la competizione.", "{0}, who created the competition, starts the new season.", "Die neue Saison startet {0}, der den Wettbewerb erstellt hat.", "La nouvelle saison est lancée par {0}, qui a créé la compétition."],
  ["Ora giochi con {0}", "Now you play as {0}", "Jetzt spielst du mit {0}", "Tu joues maintenant avec {0}"],
  ["Sei dentro con {0}", "You're in with {0}", "Du bist dabei mit {0}", "Tu es inscrit avec {0}"],
  ["Partita simulata: {0}", "Match simulated: {0}", "Spiel simuliert: {0}", "Match simulé : {0}"],
  ["Partita simulata: {0} (rigori {1}-{2})", "Match simulated: {0} (penalties {1}-{2})", "Spiel simuliert: {0} (Elfmeterschiessen {1}-{2})", "Match simulé : {0} (tirs au but {1}-{2})"],
  ["Partita simulata: {0} (d.t.s.)", "Match simulated: {0} (a.e.t.)", "Spiel simuliert: {0} (n.V.)", "Match simulé : {0} (a.p.)"],
  ["Risultato registrato: {0}", "Result recorded: {0}", "Ergebnis gespeichert: {0}", "Résultat enregistré : {0}"],
  ["Risultato registrato: {0} (rigori {1}-{2})", "Result recorded: {0} (penalties {1}-{2})", "Ergebnis gespeichert: {0} (Elfmeterschiessen {1}-{2})", "Résultat enregistré : {0} (tirs au but {1}-{2})"],
  ["Risultato registrato: {0} (d.t.s.)", "Result recorded: {0} (a.e.t.)", "Ergebnis gespeichert: {0} (n.V.)", "Résultat enregistré : {0} (a.p.)"],
  ["Risultato registrato nella sfida tra amici", "Result recorded in the challenge between friends", "Ergebnis in der Herausforderung unter Freunden gespeichert", "Résultat enregistré dans le défi entre amis"],
  ["Risultato registrato nella sfida tra amici (rigori {0}-{1} dalla simulazione)", "Result recorded in the challenge between friends (penalties {0}-{1} from the simulation)", "Ergebnis in der Herausforderung unter Freunden gespeichert (Elfmeterschiessen {0}-{1} aus der Simulation)", "Résultat enregistré dans le défi entre amis (tirs au but {0}-{1} par la simulation)"],
  ["Risultato registrato nella sfida tra amici (supplementari dalla simulazione)", "Result recorded in the challenge between friends (extra time from the simulation)", "Ergebnis in der Herausforderung unter Freunden gespeichert (Verlängerung aus der Simulation)", "Résultat enregistré dans le défi entre amis (prolongations par la simulation)"],
  ["Risultato non mandato: {t0}", "Result not sent: {t0}", "Ergebnis nicht gesendet: {t0}", "Résultat non envoyé : {t0}"],
  ["Risultato non registrato: {t0}", "Result not recorded: {t0}", "Ergebnis nicht gespeichert: {t0}", "Résultat non enregistré : {t0}"],
  ["Uscita non registrata: {t0}. Al prossimo «Gioca» decide la simulazione.", "Exit not recorded: {t0}. On the next “Play” the simulation decides.", "Verlassen nicht gespeichert: {t0}. Beim nächsten «Spielen» entscheidet die Simulation.", "Sortie non enregistrée : {t0}. Au prochain « Jouer », la simulation décide."],
  ["Questa partita era già iniziata e non è stata finita: risultato dalla simulazione ({0} {1}-{2} {3})", "This match had already started and wasn't finished: result from the simulation ({0} {1}-{2} {3})", "Dieses Spiel hatte schon begonnen und wurde nicht beendet: Ergebnis aus der Simulation ({0} {1}-{2} {3})", "Ce match avait déjà commencé et n'a pas été terminé : résultat de la simulation ({0} {1}-{2} {3})"],
  ["Passano il turno le prime {0} di ogni girone (evidenziate).", "The top {0} of each group go through (highlighted).", "Die ersten {0} jeder Gruppe kommen weiter (hervorgehoben).", "Les {0} premières de chaque groupe passent (en surbrillance)."],
  ["{t0} · stagione {1}", "{t0} · season {1}", "{t0} · Saison {1}", "{t0} · saison {1}"],
  ["{t0} · edizione {1}", "{t0} · edition {1}", "{t0} · Ausgabe {1}", "{t0} · édition {1}"],
  ["{t0} · stagione {1} · con gli amici", "{t0} · season {1} · with friends", "{t0} · Saison {1} · mit Freunden", "{t0} · saison {1} · avec des amis"],
  ["{t0} · edizione {1} · con gli amici", "{t0} · edition {1} · with friends", "{t0} · Ausgabe {1} · mit Freunden", "{t0} · édition {1} · avec des amis"],
  ["{t0} · iscrizioni aperte", "{t0} · registration open", "{t0} · Anmeldung offen", "{t0} · inscriptions ouvertes"],
  ["Ultimi risultati · {t0}", "Latest results · {t0}", "Letzte Ergebnisse · {t0}", "Derniers résultats · {t0}"],
  ["Tempi da {0} minuti, IA {1}.", "{0}-minute halves, AI {1}.", "Halbzeiten zu {0} Minuten, KI {1}.", "Mi-temps de {0} minutes, IA {1}."],
  ["{0} (forza {1})", "{0} (rating {1})", "{0} (Stärke {1})", "{0} (force {1})"],
  ["{#0} di {#1}", "{#0} of {#1}", "{#0} von {#1}", "{#0} sur {#1}"],
  ["{#0} di {#1} partite", "{#0} of {#1} matches", "{#0} von {#1} Spielen", "{#0} sur {#1} matchs"],
  ["{0} di {1} partite giocate", "{0} of {1} matches played", "{0} von {1} Spielen gespielt", "{0} sur {1} matchs joués"],
  ["{0} giocate da te", "{0} played by you", "{0} von dir gespielt", "{0} joués par toi"],
  ["{0} giocate dagli amici", "{0} played by friends", "{0} von Freunden gespielt", "{0} joués par des amis"],
  ["{0} giocate da te, {1} simulate", "{0} played by you, {1} simulated", "{0} von dir gespielt, {1} simuliert", "{0} joués par toi, {1} simulés"],
  ["{0} giocate dagli amici, {1} simulate", "{0} played by friends, {1} simulated", "{0} von Freunden gespielt, {1} simuliert", "{0} joués par des amis, {1} simulés"],
  ["{0} giornate, {1} partite.", "{0} matchdays, {1} matches.", "{0} Spieltage, {1} Spiele.", "{0} journées, {1} matchs."],
  ["{0} gironi da 4 (andata e ritorno), passano le prime 2, poi eliminazione diretta fino alla finale.", "{0} groups of 4 (home and away), the top 2 go through, then knockout to the final.", "{0} Gruppen zu 4 (Hin- und Rückspiel), die ersten 2 kommen weiter, dann K.-o.-System bis zum Finale.", "{0} groupes de 4 (aller-retour), les 2 premiers passent, puis élimination directe jusqu'à la finale."],
  ["{0} gironi da 4 (solo andata), passano le prime 2, poi eliminazione diretta fino alla finale.", "{0} groups of 4 (single leg), the top 2 go through, then knockout to the final.", "{0} Gruppen zu 4 (nur Hinspiel), die ersten 2 kommen weiter, dann K.-o.-System bis zum Finale.", "{0} groupes de 4 (aller simple), les 2 premiers passent, puis élimination directe jusqu'à la finale."],
  ["{0} gironi, passano le prime {1}, poi eliminazione diretta.", "{0} groups, the top {1} go through, then knockout.", "{0} Gruppen, die ersten {1} kommen weiter, dann K.-o.-System.", "{0} groupes, les {1} premiers passent, puis élimination directe."],
  ["{#0} gol fatti", "{#0} goals scored", "{#0} Tore erzielt", "{#0} buts marqués"],
  ["{#0} gol subiti", "{#0} goals conceded", "{#0} Gegentore", "{#0} buts encaissés"],
  ["{0} gol in {1} partite", "{0} goals in {1} matches", "{0} Tore in {1} Spielen", "{0} buts en {1} matchs"],
  ["{0} gol subiti in {1}", "{0} goals conceded in {1}", "{0} Gegentore in {1}", "{0} buts encaissés en {1}"],
  ["{0} gol, media {1}", "{0} goals, average {1}", "{0} Tore, Schnitt {1}", "{0} buts, moyenne {1}"],
  ["{0} gol, {1}", "{0} goals, {1}", "{0} Tore, {1}", "{0} buts, {1}"],
  ["media {0} a partita", "average {0} per match", "Schnitt {0} pro Spiel", "moyenne {0} par match"],
  ["{0} ha creato questa competizione ({1}) con {2} squadre.", "{0} created this competition ({1}) with {2} teams.", "{0} hat diesen Wettbewerb ({1}) mit {2} Teams erstellt.", "{0} a créé cette compétition ({1}) avec {2} équipes."],
  ["{0} invito senza risposta: se inizi ora scade e quelle squadre le guida l'IA.", "{0} invite unanswered: if you start now it expires and the AI controls that team.", "{0} Einladung ohne Antwort: Wenn du jetzt startest, verfällt sie und die KI steuert dieses Team.", "{0} invitation sans réponse : si tu commences maintenant, elle expire et l'IA dirige cette équipe."],
  ["{0} inviti senza risposta: se inizi ora scadono e quelle squadre le guida l'IA.", "{0} invites unanswered: if you start now they expire and the AI controls those teams.", "{0} Einladungen ohne Antwort: Wenn du jetzt startest, verfallen sie und die KI steuert diese Teams.", "{0} invitations sans réponse : si tu commences maintenant, elles expirent et l'IA dirige ces équipes."],
  ["{#0} squadre", "{#0} teams", "{#0} Teams", "{#0} équipes"],
  ["{0} squadre: {1}.", "{0} teams: {1}.", "{0} Teams: {1}.", "{0} équipes : {1}."],
  ["ultima: {0}", "last: {0}", "letztes: {0}", "dernier : {0}"],
  ["Ritorno: all'andata {0} {1}, {2} {3}.", "Second leg: first leg {0} {1}, {2} {3}.", "Rückspiel: im Hinspiel {0} {1}, {2} {3}.", "Retour : à l'aller {0} {1}, {2} {3}."],
  ["@PG", "P", "Sp", "J"],
  ["@V", "W", "S", "V"],
  ["@N", "D", "U", "N"],
  ["@P", "L", "N", "D"],
  ["@GF", "GF", "T", "BP"],
  ["@GS", "GA", "GT", "BC"],
  ["@DR", "GD", "TD", "Diff"],
  ["@PT", "Pts", "Pkt", "Pts"],
  ["@CS", "CS", "ZN", "CS"],
  ["@% V", "% W", "% S", "% V"],
  ["Vincitore", "Winner", "Sieger", "Vainqueur"],
  ["Campione", "Champion", "Meister", "Champion"],
  ["invitato, deve rispondere", "invited, hasn't replied yet", "eingeladen, Antwort ausstehend", "invité, doit répondre"],
  ["ha lasciato", "left", "hat verlassen", "est parti"],
]);
