// Amici (src/20_social.js): pannello Amici nella Home, richieste, inviti, sfide
// Ogni riga: [italiano, inglese, tedesco, francese]
addTranslations([
  ["Accedi con l'account per sfidare gli amici in campionati, tornei e coppe.", "Log in with your account to challenge friends in leagues, tournaments and cups.", "Melde dich mit deinem Konto an, um Freunde in Meisterschaften, Turnieren und Pokalen herauszufordern.", "Connecte-toi avec ton compte pour défier tes amis en championnats, tournois et coupes."],
  ["Accedi per vedere chi gioca, aggiungere amici e sfidarli in campionati, tornei e coppe.", "Log in to see who's playing, add friends and challenge them in leagues, tournaments and cups.", "Melde dich an, um zu sehen, wer spielt, Freunde hinzuzufügen und sie in Meisterschaften, Turnieren und Pokalen herauszufordern.", "Connecte-toi pour voir qui joue, ajouter des amis et les défier en championnats, tournois et coupes."],
  ["Ancora nessun amico: aggiungili dall'elenco qui sotto.", "No friends yet: add them from the list below.", "Noch keine Freunde: Füge sie aus der Liste unten hinzu.", "Pas encore d'amis : ajoute-les depuis la liste ci-dessous."],
  ["Scegli la squadra", "Choose the team", "Team wählen", "Choisir l'équipe"],
  ["1 contro 1, ognuno con la sua squadra · partita {0}", "1 v 1, each with their own team · match {0}", "1 gegen 1, jeder mit seinem Team · Spiel {0}", "1 contre 1, chacun avec son équipe · match {0}"],
  ["Amici · {0}", "Friends · {0}", "Freunde · {0}", "Amis · {0}"],
  ["Amico", "Friend", "Freund", "Ami"],
  ["amico", "friend", "Freund", "ami"],
  ["Aggiungi", "Add", "Hinzufügen", "Ajouter"],
  ["Accetta", "Accept", "Annehmen", "Accepter"],
  ["Sfida", "Challenge", "Herausfordern", "Défier"],
  ["Campionato, torneo o coppa insieme", "League, tournament or cup together", "Meisterschaft, Turnier oder Pokal zusammen", "Championnat, tournoi ou coupe ensemble"],
  ["Cerca un nome", "Search for a name", "Namen suchen", "Chercher un nom"],
  ["Ci sono altri giocatori: cerca il nome.", "There are more players: search for the name.", "Es gibt weitere Spieler: Suche nach dem Namen.", "Il y a d'autres joueurs : cherche le nom."],
  ["Il server non ha ancora gli amici: va aggiornato alla 0.9 (nella cartella cloud: npm run deploy).", "The server doesn't have friends yet: it needs updating to 0.9 (in the cloud folder: npm run deploy).", "Der Server hat noch keine Freunde-Funktion: Er muss auf 0.9 aktualisiert werden (im Ordner cloud: npm run deploy).", "Le serveur n'a pas encore les amis : il faut le mettre à jour en 0.9 (dans le dossier cloud : npm run deploy)."],
  ["Le tue sfide", "Your challenges", "Deine Herausforderungen", "Tes défis"],
  ["Nessun giocatore con questo nome.", "No player with this name.", "Kein Spieler mit diesem Namen.", "Aucun joueur avec ce nom."],
  ["Nessuna sfida tra amici: creane una e invita chi vuoi dalla lista degli amici.", "No challenges between friends: create one and invite whoever you like from your friends list.", "Keine Herausforderungen unter Freunden: Erstelle eine und lade aus deiner Freundesliste ein, wen du willst.", "Aucun défi entre amis : crées-en un et invite qui tu veux depuis ta liste d'amis."],
  ["Nessuna sfida: invita un amico con «Sfida».", "No challenges: invite a friend with “Challenge”.", "Keine Herausforderungen: Lade einen Freund mit «Herausfordern» ein.", "Aucun défi : invite un ami avec « Défier »."],
  ["Nuova sfida", "New challenge", "Neue Herausforderung", "Nouveau défi"],
  ["Partita online 1 contro 1: ognuno con la sua squadra da 11", "Online 1-v-1 match: each with their own 11-player team", "Online-Spiel 1 gegen 1: jeder mit seinem eigenen 11er-Team", "Match en ligne 1 contre 1 : chacun avec son équipe de 11"],
  ["Per gli amici serve il server online: impostalo in Impostazioni → Online.", "Friends need the online server: set it in Settings → Online.", "Für Freunde braucht es den Online-Server: Stelle ihn unter Einstellungen → Online ein.", "Les amis nécessitent le serveur en ligne : configure-le dans Paramètres → En ligne."],
  ["Richiesta inviata a {0}", "Request sent to {0}", "Anfrage an {0} gesendet", "Demande envoyée à {0}"],
  ["Richieste e inviti", "Requests and invites", "Anfragen und Einladungen", "Demandes et invitations"],
  ["Togli dagli amici", "Remove from friends", "Aus Freunden entfernen", "Retirer des amis"],
  ["Tutti i giocatori", "All players", "Alle Spieler", "Tous les joueurs"],
  ["Tutti i giocatori · {#0}", "All players · {#0}", "Alle Spieler · {#0}", "Tous les joueurs · {#0}"],
  ["iscrizioni aperte", "registration open", "Anmeldung offen", "inscriptions ouvertes"],
  ["richiesta inviata", "request sent", "Anfrage gesendet", "demande envoyée"],
  ["ti invita a giocare online", "invites you to play online", "lädt dich zu einem Online-Spiel ein", "t'invite à jouer en ligne"],
  ["ti invita a", "invites you to", "lädt dich ein zu", "t'invite à"],
  ["vuole essere tuo amico", "wants to be your friend", "möchte dein Freund sein", "veut être ton ami"],
  ["{0} iscritti su {1} squadre", "{0} joined out of {1} teams", "{0} angemeldet von {1} Teams", "{0} inscrits sur {1} équipes"],
  ["{0} non è più tra gli amici", "{0} is no longer a friend", "{0} ist nicht mehr dein Freund", "{0} ne fait plus partie de tes amis"],
  ["{0} ora è tuo amico", "{0} is now your friend", "{0} ist jetzt dein Freund", "{0} est maintenant ton ami"],
  ["{0} ti invita a giocare online: apri Amici", "{0} invites you to play online: open Friends", "{0} lädt dich zu einem Online-Spiel ein: Öffne Freunde", "{0} t'invite à jouer en ligne : ouvre Amis"],
  ["{t0} · {#1} squadre · {#2} giocatori iscritti", "{t0} · {#1} teams · {#2} players joined", "{t0} · {#1} Teams · {#2} Spieler angemeldet", "{t0} · {#1} équipes · {#2} joueurs inscrits"],
]);
