// Server (cloud/src/*.js): mercati delle scommesse e messaggi di errore. Il server resta in italiano: il gioco traduce quello che mostra
// Ogni riga: [italiano, inglese, tedesco, francese]
addTranslations([
  ["Esito finale", "Match result", "Endergebnis", "Résultat final"],
  ["Doppia chance", "Double chance", "Doppelte Chance", "Double chance"],
  ["Risultato primo tempo", "Half-time result", "Halbzeitergebnis", "Résultat à la mi-temps"],
  ["Handicap", "Handicap", "Handicap", "Handicap"],
  ["Risultato esatto", "Correct score", "Genaues Ergebnis", "Score exact"],
  ["Altro risultato", "Any other score", "Anderes Ergebnis", "Autre score"],
  ["Gol totali", "Total goals", "Tore insgesamt", "Total de buts"],
  ["Entrambe segnano", "Both teams to score", "Beide Teams treffen", "Les deux équipes marquent"],
  ["Gol primo tempo", "First-half goals", "Tore erste Halbzeit", "Buts en première mi-temps"],
  ["Gol secondo tempo", "Second-half goals", "Tore zweite Halbzeit", "Buts en seconde mi-temps"],
  ["Primo gol", "First goal", "Erstes Tor", "Premier but"],
  ["Ultimo gol", "Last goal", "Letztes Tor", "Dernier but"],
  ["Porta inviolata {0}", "{0} clean sheet", "{0} ohne Gegentor", "{0} sans encaisser"],
  ["Corner totali", "Total corners", "Ecken insgesamt", "Total de corners"],
  ["Corner {0}", "{0} corners", "Ecken {0}", "Corners {0}"],
  ["Primo corner", "First corner", "Erste Ecke", "Premier corner"],
  ["Nessun corner", "No corners", "Keine Ecke", "Aucun corner"],
  ["Cartellini totali", "Total cards", "Karten insgesamt", "Total de cartons"],
  ["Primo cartellino", "First card", "Erste Karte", "Premier carton"],
  ["Nessun cartellino", "No cards", "Keine Karte", "Aucun carton"],
  ["Espulsione", "Sending-off", "Platzverweis", "Expulsion"],
  ["Tiri totali", "Total shots", "Schüsse insgesamt", "Total de tirs"],
  ["Più possesso palla", "More possession", "Mehr Ballbesitz", "Plus de possession"],
  ["Più di {0}", "Over {0}", "Über {0}", "Plus de {0}"],
  ["Meno di {0}", "Under {0}", "Unter {0}", "Moins de {0}"],
  ["Sì", "Yes", "Ja", "Oui"],
  ["No", "No", "Nein", "Non"],
  ["{0} vincente", "{0} to win", "{0} gewinnt", "{0} gagne"],
  ["{0} o pareggio", "{0} or draw", "{0} oder Unentschieden", "{0} ou nul"],
  ["Pareggio o {0}", "Draw or {0}", "Unentschieden oder {0}", "Nul ou {0}"],
  ["{0} o {1}", "{0} or {1}", "{0} oder {1}", "{0} ou {1}"],
  ["1X2", "1X2", "1X2", "1X2"],
  ["GOL", "GOALS", "TORE", "BUTS"],
  ["CORNER", "CORNERS", "ECKEN", "CORNERS"],
  ["CARTELLINI", "CARDS", "KARTEN", "CARTONS"],
  ["ALTRO", "OTHER", "WEITERE", "AUTRES"],
  ["{t0} · stagione {1} · giornata {2}", "{t0} · season {1} · matchday {2}", "{t0} · Saison {1} · Spieltag {2}", "{t0} · saison {1} · journée {2}"],
  ["stagione {0} · giornata {1}", "season {0} · matchday {1}", "Saison {0} · Spieltag {1}", "saison {0} · journée {1}"],
  ["Accedi per continuare", "Log in to continue", "Melde dich an, um fortzufahren", "Connecte-toi pour continuer"],
  ["Bonus di oggi già riscosso", "Today's bonus already collected", "Heutiger Bonus schon abgeholt", "Bonus du jour déjà récupéré"],
  ["Carriera troppo grande da salvare", "Career too large to save", "Karriere zu gross zum Speichern", "Carrière trop grande pour être enregistrée"],
  ["Categoria non valida", "Invalid category", "Ungültige Kategorie", "Catégorie non valide"],
  ["Codice della partita non valido", "Invalid match code", "Ungültiger Spielcode", "Code du match non valide"],
  ["Codice della stanza non valido", "Invalid room code", "Ungültiger Raumcode", "Code du salon non valide"],
  ["codice non valido", "invalid code", "ungültiger Code", "code non valide"],
  ["Competizione non trovata", "Competition not found", "Wettbewerb nicht gefunden", "Compétition introuvable"],
  ["Competizione non valida", "Invalid competition", "Ungültiger Wettbewerb", "Compétition non valide"],
  ["Contro un amico si gioca online", "Against a friend you play online", "Gegen einen Freund wird online gespielt", "Contre un ami, on joue en ligne"],
  ["Controller non valido", "Invalid controller", "Ungültiger Controller", "Manette non valide"],
  ["Data del salvataggio non valida", "Invalid save date", "Ungültiges Speicherdatum", "Date de sauvegarde non valide"],
  ["Elenco non valido", "Invalid list", "Ungültige Liste", "Liste non valide"],
  ["Errore del server", "Server error", "Serverfehler", "Erreur du serveur"],
  ["Giocatore non trovato", "Player not found", "Spieler nicht gefunden", "Joueur introuvable"],
  ["Hai creato tu la competizione: puoi eliminarla", "You created the competition: you can delete it", "Du hast den Wettbewerb erstellt: Du kannst ihn löschen", "C'est toi qui as créé la compétition : tu peux la supprimer"],
  ["Hai già questo oggetto", "You already have this item", "Du hast diesen Gegenstand schon", "Tu as déjà cet objet"],
  ["Il premio si riscuote durante il secondo tempo della partita", "The reward is collected during the second half of the match", "Die Prämie gibt es während der zweiten Halbzeit", "La prime se récupère pendant la seconde mi-temps du match"],
  ["Indirizzo sconosciuto", "Unknown address", "Unbekannte Adresse", "Adresse inconnue"],
  ["Invito non più valido", "Invite no longer valid", "Einladung nicht mehr gültig", "Invitation plus valable"],
  ["La competizione non è in corso", "The competition isn't in progress", "Der Wettbewerb läuft nicht", "La compétition n'est pas en cours"],
  ["La competizione è già iniziata", "The competition has already started", "Der Wettbewerb hat schon begonnen", "La compétition a déjà commencé"],
  ["La competizione è già iniziata: gli inviti sono chiusi", "The competition has already started: invites are closed", "Der Wettbewerb hat schon begonnen: Die Einladungen sind geschlossen", "La compétition a déjà commencé : les invitations sont fermées"],
  ["La password deve avere da 8 a 128 caratteri", "The password must be 8 to 128 characters", "Das Passwort muss 8 bis 128 Zeichen haben", "Le mot de passe doit contenir de 8 à 128 caractères"],
  ["La stagione non è ancora finita", "The season isn't over yet", "Die Saison ist noch nicht beendet", "La saison n'est pas encore terminée"],
  ["Manca la quota vista per una selezione", "The odds seen for a selection are missing", "Für einen Tipp fehlt die angezeigte Quote", "Il manque la cote vue pour une sélection"],
  ["Messaggio sconosciuto", "Unknown message", "Unbekannte Nachricht", "Message inconnu"],
  ["Nessun invito", "No invite", "Keine Einladung", "Aucune invitation"],
  ["Nome sulla maglia: massimo 12 caratteri tra lettere, numeri, spazio . ' -", "Name on the shirt: up to 12 characters, letters, numbers, space . ' -", "Name auf dem Trikot: höchstens 12 Zeichen aus Buchstaben, Zahlen, Leerzeichen . ' -", "Nom sur le maillot : 12 caractères maximum parmi lettres, chiffres, espace . ' -"],
  ["Nome utente o password sbagliati", "Wrong username or password", "Benutzername oder Passwort falsch", "Nom d'utilisateur ou mot de passe incorrect"],
  ["Nome utente: da 3 a 16 caratteri, lettere, numeri o _", "Username: 3 to 16 characters, letters, numbers or _", "Benutzername: 3 bis 16 Zeichen, Buchstaben, Zahlen oder _", "Nom d'utilisateur : de 3 à 16 caractères, lettres, chiffres ou _"],
  ["Non partecipi a questa competizione", "You're not in this competition", "Du nimmst an diesem Wettbewerb nicht teil", "Tu ne participes pas à cette compétition"],
  ["Non possiedi questo oggetto", "You don't own this item", "Du besitzt diesen Gegenstand nicht", "Tu ne possèdes pas cet objet"],
  ["Non puoi aggiungere te stesso", "You can't add yourself", "Du kannst dich nicht selbst hinzufügen", "Tu ne peux pas t'ajouter toi-même"],
  ["Non puoi invitare te stesso", "You can't invite yourself", "Du kannst dich nicht selbst einladen", "Tu ne peux pas t'inviter toi-même"],
  ["Non puoi reagire alle tue scommesse", "You can't react to your own bets", "Du kannst nicht auf deine eigenen Wetten reagieren", "Tu ne peux pas réagir à tes propres paris"],
  ["Non è una partita della tua squadra", "It's not your team's match", "Das ist kein Spiel deines Teams", "Ce n'est pas un match de ton équipe"],
  ["Numero di maglia da 1 a 99", "Shirt number from 1 to 99", "Rückennummer von 1 bis 99", "Numéro de maillot de 1 à 99"],
  ["Oggetto non in vendita", "Item not for sale", "Gegenstand nicht verkäuflich", "Objet pas en vente"],
  ["Oggetto non valido", "Invalid item", "Ungültiger Gegenstand", "Objet non valide"],
  ["Partecipi già", "You're already in", "Du nimmst schon teil", "Tu participes déjà"],
  ["Posto non più disponibile", "Spot no longer available", "Platz nicht mehr verfügbar", "Place plus disponible"],
  ["Preferenze non valide", "Invalid preferences", "Ungültige Einstellungen", "Préférences non valides"],
  ["Preferenze troppo grandi", "Preferences too large", "Einstellungen zu gross", "Préférences trop grandes"],
  ["Premio già riscosso per questa partita", "Reward already collected for this match", "Prämie für dieses Spiel schon abgeholt", "Prime déjà récupérée pour ce match"],
  ["Pulsanti non validi", "Invalid buttons", "Ungültige Tasten", "Boutons non valides"],
  ["Questa partita non è in programma adesso: aggiorna", "This match isn't scheduled now: refresh", "Dieses Spiel ist jetzt nicht angesetzt: Aktualisiere", "Ce match n'est pas prévu maintenant : actualise"],
  ["Questa partita è contro l'IA", "This match is against the AI", "Dieses Spiel ist gegen die KI", "Ce match est contre l'IA"],
  ["Questa squadra l'ha già scelta un altro giocatore", "Another player has already chosen this team", "Dieses Team hat schon ein anderer Spieler gewählt", "Un autre joueur a déjà choisi cette équipe"],
  ["Questo account è nascosto: non può avere amici", "This account is hidden: it can't have friends", "Dieses Konto ist verborgen: Es kann keine Freunde haben", "Ce compte est masqué : il ne peut pas avoir d'amis"],
  ["Questo nome utente è già usato", "This username is already taken", "Dieser Benutzername ist schon vergeben", "Ce nom d'utilisateur est déjà pris"],
  ["Quota non valida", "Invalid odds", "Ungültige Quote", "Cote non valide"],
  ["Quota cambiata", "Odds changed", "Quote geändert", "Cote modifiée"],
  ["Reazione non valida", "Invalid reaction", "Ungültige Reaktion", "Réaction non valide"],
  ["Richiesta non valida", "Invalid request", "Ungültige Anfrage", "Requête non valide"],
  ["Richiesta senza chiave valida", "Request without a valid key", "Anfrage ohne gültigen Schlüssel", "Requête sans clé valide"],
  ["Richiesta troppo grande", "Request too large", "Anfrage zu gross", "Requête trop grande"],
  ["Riprova", "Try again", "Erneut versuchen", "Réessaie"],
  ["Riprova: codice già in uso", "Try again: code already in use", "Erneut versuchen: Code schon vergeben", "Réessaie : code déjà utilisé"],
  ["Salvataggio non valido", "Invalid save", "Ungültiger Spielstand", "Sauvegarde non valide"],
  ["Scegli la tua squadra tra quelle della competizione", "Choose your team from the competition's teams", "Wähle dein Team aus den Teams des Wettbewerbs", "Choisis ton équipe parmi celles de la compétition"],
  ["Scegli una squadra della competizione", "Choose a team from the competition", "Wähle ein Team des Wettbewerbs", "Choisis une équipe de la compétition"],
  ["Schedina non valida", "Invalid bet slip", "Ungültiger Wettschein", "Bulletin non valide"],
  ["Scommessa non trovata", "Bet not found", "Wette nicht gefunden", "Pari introuvable"],
  ["Selezione non valida", "Invalid selection", "Ungültiger Tipp", "Sélection non valide"],
  ["Solo chi ha creato la competizione può farlo", "Only the creator of the competition can do this", "Nur der Ersteller des Wettbewerbs kann das tun", "Seul le créateur de la compétition peut le faire"],
  ["Squadre non valide", "Invalid teams", "Ungültige Teams", "Équipes non valides"],
  ["Sul server c'è un salvataggio più recente", "There's a more recent save on the server", "Auf dem Server gibt es einen neueren Spielstand", "Il y a une sauvegarde plus récente sur le serveur"],
  ["Tasti non validi", "Invalid keys", "Ungültige Tasten", "Touches non valides"],
  ["Troppe competizioni", "Too many competitions", "Zu viele Wettbewerbe", "Trop de compétitions"],
  ["Troppe modifiche nello stesso momento: riprova", "Too many changes at the same time: try again", "Zu viele gleichzeitige Änderungen: Versuche es erneut", "Trop de modifications en même temps : réessaie"],
  ["Troppe reazioni in poco tempo", "Too many reactions in a short time", "Zu viele Reaktionen in kurzer Zeit", "Trop de réactions en peu de temps"],
  ["Troppe richieste in attesa", "Too many pending requests", "Zu viele offene Anfragen", "Trop de demandes en attente"],
  ["Troppe scommesse in poco tempo: aspetta un momento", "Too many bets in a short time: wait a moment", "Zu viele Wetten in kurzer Zeit: Warte einen Moment", "Trop de paris en peu de temps : attends un instant"],
  ["Troppi account creati da questa rete oggi", "Too many accounts created from this network today", "Zu viele Konten heute aus diesem Netzwerk erstellt", "Trop de comptes créés depuis ce réseau aujourd'hui"],
  ["Troppi tentativi sbagliati: riprova tra qualche minuto", "Too many wrong attempts: try again in a few minutes", "Zu viele Fehlversuche: Versuche es in ein paar Minuten erneut", "Trop de tentatives incorrectes : réessaie dans quelques minutes"],
  ["Valore non valido", "Invalid value", "Ungültiger Wert", "Valeur non valide"],
  ["Versione del gioco diversa da quella del server", "Game version different from the server's", "Spielversion unterscheidet sich von der des Servers", "Version du jeu différente de celle du serveur"],
  ["Visibilità non valida", "Invalid visibility", "Ungültige Sichtbarkeit", "Visibilité non valide"],
  ["Zona morta non valida", "Invalid dead zone", "Ungültige Totzone", "Zone morte non valide"],
  ["Al massimo {0} partecipanti", "At most {0} participants", "Höchstens {0} Teilnehmer", "Au maximum {0} participants"],
  ["Al massimo {0} selezioni", "At most {0} selections", "Höchstens {0} Tipps", "Au maximum {0} sélections"],
  ["Hai già riscosso {0} premi spettatore oggi", "You've already collected {0} spectator rewards today", "Du hast heute schon {0} Zuschauerprämien abgeholt", "Tu as déjà récupéré {0} primes de spectateur aujourd'hui"],
  ["Hai già {0} competizioni in corso: finiscine o eliminane una", "You already have {0} competitions in progress: finish or delete one", "Du hast schon {0} laufende Wettbewerbe: Beende oder lösche einen", "Tu as déjà {0} compétitions en cours : termines-en une ou supprimes-en une"],
  ["La schedina deve avere da 1 a {0} selezioni", "The bet slip must have 1 to {0} selections", "Der Wettschein muss 1 bis {0} Tipps haben", "Le bulletin doit avoir de 1 à {0} sélections"],
  ["Nessuna richiesta da {0}", "No request from {0}", "Keine Anfrage von {0}", "Aucune demande de {0}"],
  ["Preferenza non valida: {0}", "Invalid preference: {0}", "Ungültige Einstellung: {0}", "Préférence non valide : {0}"],
  ["Puntata: un numero intero di monete da {0} a {1}", "Stake: a whole number of coins from {0} to {1}", "Einsatz: eine ganze Zahl an Münzen von {0} bis {1}", "Mise : un nombre entier de pièces de {0} à {1}"],
  ["Quota totale oltre {0}", "Total odds above {0}", "Gesamtquote über {0}", "Cote totale au-delà de {0}"],
  ["Scommesse chiuse per {0} - {1}", "Betting closed for {0} - {1}", "Wetten geschlossen für {0} - {1}", "Paris fermés pour {0} - {1}"],
  ["Selezione incompatibile: {t0} non si può combinare con {t1}", "Incompatible selection: {t0} can't be combined with {t1}", "Nicht kombinierbarer Tipp: {t0} lässt sich nicht mit {t1} kombinieren", "Sélection incompatible : {t0} ne peut pas être combiné avec {t1}"],
  ["Selezione incompatibile: {t0} non si può combinare con {t1} ({2})", "Incompatible selection: {t0} can't be combined with {t1} ({2})", "Nicht kombinierbarer Tipp: {t0} lässt sich nicht mit {t1} kombinieren ({2})", "Sélection incompatible : {t0} ne peut pas être combiné avec {t1} ({2})"],
  ["Selezione ripetuta: {t0}", "Repeated selection: {t0}", "Doppelter Tipp: {t0}", "Sélection répétée : {t0}"],
  ["Selezioni incompatibili: {0} non possono vincere insieme{1}", "Incompatible selections: {0} can't win together{1}", "Nicht kombinierbare Tipps: {0} können nicht zusammen gewinnen{1}", "Sélections incompatibles : {0} ne peuvent pas gagner ensemble{1}"],
  ["Vincita possibile oltre il massimo di {0} monete: abbassa la puntata", "Potential winnings over the maximum of {0} coins: lower the stake", "Möglicher Gewinn über dem Maximum von {0} Münzen: Senke den Einsatz", "Gain possible au-delà du maximum de {0} pièces : baisse la mise"],
  ["{0} non è tra i tuoi amici", "{0} isn't one of your friends", "{0} ist nicht unter deinen Freunden", "{0} ne fait pas partie de tes amis"],
  ["«{t0}: {t1}»", "«{t0}: {t1}»", "«{t0}: {t1}»", "« {t0} : {t1} »"],
]);
