// Telecronaca a scritte (src/21_commentary.js) e la sua impostazione
// Ogni riga: [italiano, inglese, tedesco, francese]. Le frasi con @ servono solo a trf() nel codice.
addTranslations([
  ["Telecronaca", "Commentary", "Kommentar", "Commentaire"],
  ["Frasi brevi durante la partita (gol, parate, falli, cartellini)", "Short lines during the match (goals, saves, fouls, cards)", "Kurze Sätze während des Spiels (Tore, Paraden, Fouls, Karten)", "Phrases courtes pendant le match (buts, arrêts, fautes, cartons)"],
  ["@GOOOL di {0}!", "GOOOAL by {0}!", "TOOOR durch {0}!", "BUUUT de {0} !"],
  ["@Rete di {0}!", "{0} scores!", "Treffer von {0}!", "But de {0} !"],
  ["@{0} la mette dentro!", "{0} puts it away!", "{0} macht ihn rein!", "{0} la met au fond !"],
  ["@Gol! Firma di {0}", "Goal! {0} with the finish", "Tor! {0} trifft", "But ! Signé {0}"],
  ["@Autogol di {0}!", "Own goal by {0}!", "Eigentor von {0}!", "But contre son camp de {0} !"],
  ["@Sfortunato {0}: autogol", "Unlucky {0}: own goal", "Pech für {0}: Eigentor", "Malchanceux {0} : contre son camp"],
  ["@Gran parata!", "Great save!", "Starke Parade!", "Superbe arrêt !"],
  ["@Il portiere ci arriva!", "The keeper gets there!", "Der Torhüter ist dran!", "Le gardien s'interpose !"],
  ["@Che riflessi del portiere!", "What reflexes from the keeper!", "Was für Reflexe des Torhüters!", "Quels réflexes du gardien !"],
  ["@Palo! Che sfortuna", "Off the post! So unlucky", "Pfosten! So ein Pech", "Poteau ! Pas de chance"],
  ["@Colpisce il legno!", "It hits the woodwork!", "Nur das Aluminium!", "Sur le montant !"],
  ["@Sul palo!", "Off the post!", "An den Pfosten!", "Sur le poteau !"],
  ["@Ci prova {0}…", "{0} has a go…", "{0} versucht es…", "{0} tente sa chance…"],
  ["@Tiro di {0}…", "Shot by {0}…", "Schuss von {0}…", "Tir de {0}…"],
  ["@{0} calcia…", "{0} shoots…", "{0} zieht ab…", "{0} frappe…"],
  ["@Fuori di poco!", "Just wide!", "Knapp vorbei!", "Juste à côté !"],
  ["@Alto sopra la traversa", "Over the bar", "Über die Latte", "Au-dessus de la barre"],
  ["@Niente da fare, fuori", "No luck, it's wide", "Nichts zu machen, vorbei", "Rien à faire, c'est à côté"],
  ["@Fallo di {0}", "Foul by {0}", "Foul von {0}", "Faute de {0}"],
  ["@L'arbitro fischia: fallo di {0}", "The referee blows: foul by {0}", "Der Schiedsrichter pfeift: Foul von {0}", "L'arbitre siffle : faute de {0}"],
  ["@Giallo per {0}", "Yellow for {0}", "Gelb für {0}", "Jaune pour {0}"],
  ["@Ammonito {0}", "{0} is booked", "{0} wird verwarnt", "{0} est averti"],
  ["@Rosso! {0} va negli spogliatoi", "Red! {0} heads for the dressing room", "Rot! {0} muss in die Kabine", "Rouge ! {0} file au vestiaire"],
  ["@Espulso {0}!", "{0} is sent off!", "{0} fliegt vom Platz!", "{0} est expulsé !"],
  ["@È rigore!", "It's a penalty!", "Es gibt Elfmeter!", "C'est penalty !"],
  ["@Fuorigioco di {0}", "{0} is offside", "{0} steht im Abseits", "Hors-jeu de {0}"],
  ["@Bandierina alzata: fuorigioco", "Flag's up: offside", "Fahne oben: Abseits", "Drapeau levé : hors-jeu"],
  ["@Calcio d'angolo per {0}", "Corner kick for {0}", "Eckstoss für {0}", "Corner pour {0}"],
  ["@Corner per {0}", "Corner to {0}", "Ecke für {0}", "Corner en faveur de {0}"],
  ["@L'arbitro lascia correre: vantaggio", "The referee waves play on: advantage", "Der Schiedsrichter lässt laufen: Vorteil", "L'arbitre laisse jouer : avantage"],
  ["@Fine del primo tempo", "That's half time", "Halbzeit", "C'est la mi-temps"],
  ["@Finisce qui!", "It's all over!", "Aus und vorbei!", "C'est terminé !"],
  ["@Triplice fischio: fine partita", "Final whistle: full time", "Schlusspfiff: Spielende", "Coup de sifflet final : fin du match"],
]);
