// Editor delle squadre (src/22_team_editor.js)
// Ogni riga: [italiano, inglese, tedesco, francese]
addTranslations([
  ["Le mie squadre", "My teams", "Meine Teams", "Mes équipes"],
  ["Crea la tua squadra: nome, colori, forza, formazione e giocatori. Si salva su questo computer e la trovi nella partita rapida contro l'IA.", "Create your own team: name, colours, strength, formation and players. It's saved on this computer and you'll find it in quick matches against the AI.", "Erstelle dein eigenes Team: Name, Farben, Stärke, Formation und Spieler. Es wird auf diesem Computer gespeichert und du findest es im Schnellspiel gegen die KI.", "Crée ton équipe : nom, couleurs, force, formation et joueurs. Elle est enregistrée sur cet ordinateur et tu la retrouves dans le match rapide contre l'IA."],
  ["Sigla", "Short name", "Kürzel", "Abréviation"],
  ["Allenatore", "Coach", "Trainer", "Entraîneur"],
  ["Maglia di casa", "Home kit", "Heimtrikot", "Maillot domicile"],
  ["Maglia da trasferta", "Away kit", "Auswärtstrikot", "Maillot extérieur"],
  ["La forza della squadra decide gli attributi; qui scegli nomi, numeri, caratteristica e piede. I primi 11 sono i titolari.", "The team's strength sets the attributes; here you choose names, numbers, trait and foot. The first 11 are the starters.", "Die Teamstärke bestimmt die Werte; hier wählst du Namen, Nummern, Eigenschaft und Fuss. Die ersten 11 sind die Stammspieler.", "La force de l'équipe fixe les attributs ; ici tu choisis noms, numéros, caractéristique et pied. Les 11 premiers sont les titulaires."],
  ["Salva", "Save", "Speichern", "Enregistrer"],
  ["Nomi casuali", "Random names", "Zufällige Namen", "Noms au hasard"],
  ["Modifica", "Edit", "Bearbeiten", "Modifier"],
  ["Nuova squadra", "New team", "Neues Team", "Nouvelle équipe"],
  ["Panchina", "Bench", "Ersatzbank", "Banc"],
  ["Caratteristica", "Trait", "Eigenschaft", "Caractéristique"],
  ["Piede", "Foot", "Fuss", "Pied"],
  ["Portiere", "Goalkeeper", "Torhüter", "Gardien"],
  ["Difensore", "Defender", "Verteidiger", "Défenseur"],
  ["Centrocampista", "Midfielder", "Mittelfeldspieler", "Milieu"],
  ["Attaccante", "Forward", "Stürmer", "Attaquant"],
  ["Forza {0}", "Strength {0}", "Stärke {0}", "Force {0}"],
  ["Non hai ancora squadre tue: creane una, poi la trovi nella partita rapida tra le altre squadre.", "You don't have any teams of your own yet: create one, then you'll find it among the other teams in quick matches.", "Du hast noch keine eigenen Teams: Erstelle eins, dann findest du es im Schnellspiel bei den anderen Teams.", "Tu n'as pas encore d'équipe à toi : crées-en une, tu la retrouveras parmi les autres dans le match rapide."],
  ["Al massimo {0} squadre: eliminane una per crearne un'altra.", "At most {0} teams: delete one to create another.", "Höchstens {0} Teams: Lösche eins, um ein neues zu erstellen.", "Au maximum {0} équipes : supprimes-en une pour en créer une autre."],
  ["Scrivi il nome della squadra", "Enter the team name", "Gib den Namen des Teams ein", "Écris le nom de l'équipe"],
  ["I numeri di maglia vanno da 1 a 99", "Shirt numbers go from 1 to 99", "Rückennummern gehen von 1 bis 99", "Les numéros de maillot vont de 1 à 99"],
  ["Il numero {0} è usato due volte", "Number {0} is used twice", "Die Nummer {0} ist doppelt vergeben", "Le numéro {0} est utilisé deux fois"],
  ["Ogni giocatore ha bisogno di un nome", "Every player needs a name", "Jeder Spieler braucht einen Namen", "Chaque joueur a besoin d'un nom"],
  ["Non riesco a salvare su questo computer", "Can't save on this computer", "Speichern auf diesem Computer nicht möglich", "Impossible d'enregistrer sur cet ordinateur"],
  ["{0} salvata: la trovi nella partita rapida", "{0} saved: you'll find it in quick matches", "{0} gespeichert: Du findest es im Schnellspiel", "{0} enregistrée : tu la retrouves dans le match rapide"],
]);
