// Carriera da allenatore (src/24_manager.js)
// Ogni riga: [italiano, inglese, tedesco, francese]. Le frasi con @ servono solo a trf() nel codice.
addTranslations([
  ["Carriera da allenatore", "Manager career", "Trainerkarriere", "Carrière d'entraîneur"],
  ["Nuova carriera", "New career", "Neue Karriere", "Nouvelle carrière"],
  ["Apri la carriera", "Open the career", "Karriere öffnen", "Ouvrir la carrière"],
  ["Vai alla carriera", "Go to the career", "Zur Karriere", "Aller à la carrière"],
  ["Abbandona la carriera", "Abandon the career", "Karriere aufgeben", "Abandonner la carrière"],
  ["Sicuro? Abbandona", "Sure? Abandon", "Sicher? Aufgeben", "Sûr ? Abandonner"],
  ["Guida una squadra per più stagioni: mercato, giovani che crescono, premi a fine campionato.", "Lead a team over several seasons: transfers, young players developing, prize money at the end of the league.", "Führe ein Team über mehrere Saisons: Transfers, Talente, die sich entwickeln, Prämien am Saisonende.", "Dirige une équipe sur plusieurs saisons : mercato, jeunes qui progressent, primes en fin de championnat."],
  ["Scegli una squadra e guidala stagione dopo stagione: campionato a 8 squadre con andata e ritorno, mercato, giovani che crescono e giocatori che invecchiano.", "Choose a team and lead it season after season: an 8-team league, home and away, transfers, young players developing and others getting older.", "Wähle ein Team und führe es Saison für Saison: Liga mit 8 Teams, Hin- und Rückspiel, Transfers, Talente, die sich entwickeln, und Spieler, die älter werden.", "Choisis une équipe et dirige-la saison après saison : championnat à 8 équipes en aller-retour, mercato, jeunes qui progressent et joueurs qui vieillissent."],
  ["@Carriera · {0}", "Career · {0}", "Karriere · {0}", "Carrière · {0}"],
  ["@Budget {0}", "Budget {0}", "Budget {0}", "Budget {0}"],
  ["Chiudi la stagione", "Close the season", "Saison abschliessen", "Clôturer la saison"],
  ["Vai al campionato", "Go to the league", "Zur Meisterschaft", "Aller au championnat"],
  ["@Stagione finita: campione {0}. Chiudendola arrivano i premi, i giocatori crescono o invecchiano e parte il nuovo calendario.", "Season over: {0} are champions. When you close it, prize money arrives, players develop or age and the new fixture list starts.", "Saison vorbei: Meister ist {0}. Beim Abschliessen gibt es die Prämien, die Spieler entwickeln sich oder altern und der neue Spielplan beginnt.", "Saison terminée : champion {0}. En la clôturant, les primes arrivent, les joueurs progressent ou vieillissent et le nouveau calendrier commence."],
  ["@Stagione {0} chiusa: {1}º posto, premio {2}", "Season {0} closed: place {1}, prize {2}", "Saison {0} abgeschlossen: Platz {1}, Prämie {2}", "Saison {0} clôturée : {1}e place, prime {2}"],
  ["Rosa", "Squad", "Kader", "Effectif"],
  ["Mercato", "Transfers", "Transfermarkt", "Mercato"],
  ["I primi 11 sono i titolari. Clicca un giocatore e poi un altro per scambiarli.", "The first 11 are the starters. Click a player and then another to swap them.", "Die ersten 11 sind die Stammspieler. Klicke auf einen Spieler und dann auf einen anderen, um sie zu tauschen.", "Les 11 premiers sont les titulaires. Clique sur un joueur puis sur un autre pour les échanger."],
  ["Posto", "Position", "Position", "Poste"],
  ["Età", "Age", "Alter", "Âge"],
  ["Potenziale", "Potential", "Potenzial", "Potentiel"],
  ["Valore", "Value", "Wert", "Valeur"],
  ["Prezzo", "Price", "Preis", "Prix"],
  ["vivaio", "academy", "Nachwuchs", "formé au club"],
  ["Vendi", "Sell", "Verkaufen", "Vendre"],
  ["svincolato", "free agent", "vereinslos", "libre"],
  ["Un giocatore fuori ruolo (in rosso) gioca peggio.", "A player out of position (in red) plays worse.", "Ein Spieler auf der falschen Position (rot) spielt schlechter.", "Un joueur hors de son poste (en rouge) joue moins bien."],
  ["Mercato vuoto: nuovi giocatori a fine stagione.", "Transfer list empty: new players at the end of the season.", "Transfermarkt leer: neue Spieler am Saisonende.", "Mercato vide : nouveaux joueurs en fin de saison."],
  ["@Budget {0}. Il mercato si rinnova a ogni stagione; chi vende un giocatore lo rimpiazza con un ragazzo del vivaio.", "Budget {0}. The transfer list is renewed every season; a club that sells a player replaces him with an academy youngster.", "Budget {0}. Der Transfermarkt erneuert sich jede Saison; wer einen Spieler verkauft, ersetzt ihn durch einen Nachwuchsspieler.", "Budget {0}. Le mercato se renouvelle à chaque saison ; un club qui vend un joueur le remplace par un jeune formé au club."],
  ["Giocatore non più disponibile", "Player no longer available", "Spieler nicht mehr verfügbar", "Joueur plus disponible"],
  ["La rosa è piena: al massimo {0} giocatori", "The squad is full: at most {0} players", "Der Kader ist voll: höchstens {0} Spieler", "L'effectif est complet : au maximum {0} joueurs"],
  ["Budget insufficiente", "Not enough budget", "Budget reicht nicht", "Budget insuffisant"],
  ["Servono almeno {0} giocatori in rosa", "You need at least {0} players in the squad", "Es braucht mindestens {0} Spieler im Kader", "Il faut au moins {0} joueurs dans l'effectif"],
  ["Non puoi vendere l'unico portiere", "You can't sell your only goalkeeper", "Du kannst deinen einzigen Torhüter nicht verkaufen", "Tu ne peux pas vendre ton seul gardien"],
  ["In porta va un portiere", "A goalkeeper must play in goal", "Ins Tor gehört ein Torhüter", "Il faut un gardien dans les buts"],
  ["Acquisto fatto: è nella tua rosa", "Signed: he's in your squad", "Verpflichtet: Er ist in deinem Kader", "Recrutement fait : il est dans ton effectif"],
  ["Ancora nessuna stagione conclusa.", "No seasons completed yet.", "Noch keine Saison abgeschlossen.", "Aucune saison terminée pour l'instant."],
  ["@campione {0}", "champions {0}", "Meister {0}", "champion {0}"],
  ["@premio {0}", "prize {0}", "Prämie {0}", "prime {0}"],
  ["@Cresciuti: {0}", "Improved: {0}", "Verbessert: {0}", "En progrès : {0}"],
  ["@Ritirati (al loro posto un ragazzo del vivaio): {0}", "Retired (replaced by an academy youngster): {0}", "Zurückgetreten (ersetzt durch einen Nachwuchsspieler): {0}", "Retraités (remplacés par un jeune formé au club) : {0}"],
  ["Riserve", "Substitutes", "Ersatzspieler", "Remplaçants"],
  ["Salvataggio della carriera non riuscito", "Couldn't save the career", "Karriere konnte nicht gespeichert werden", "Impossible d'enregistrer la carrière"],
]);
